openshift-eng/art-tools

doozer/doozerlib/cli/images_streams.py

re: [ART-7462](https://issues.redhat.com/browse/ART-7462)
accoring to https://github.com/openshift/cluster-update-keys/pull/47#issuecomment-1664730578
after creating an alignment bug CI will check if it has a bug to depend on if it's not non-GA version
we need to check if a similar bug in higher version exist and try to link it

[ART-7462] set alignment bug's depends

---

doozer/doozerlib/cli/images_streams.py

This is failing the sync-for-ci job
target_release is not under jira_config (https://github.com/openshift-eng/ocp-build-data/blob/openshift-4.14/bug.yml)

Fix target_release key fetch

---

doozer/doozerlib/golang_builder_FIPS_wrapper.sh
doozer/doozerlib/source_modifications.py

cherry pick doozer@2963326 from PR https://github.com/openshift-eng/doozer/pull/811

[ART-7273] add go wrapper script in doozer

---

doozer/doozerlib/cli/images_streams.py

if the upstream_image exists in stream config, mirror it to ocp private by config upstream_image_mirror

[ART-4761] mirror builder image streams of ocp-private namespace

---

doozer/doozerlib/image.py

If one introduces or changes an attribute in the stream definition in streams.yml, this will result in a new config_digest for all consuming images, which results in mass rebuilds. In the context of product rebuilds, we are only interested if the key `image` of the streams entry changes. This commit makes that happen.

mass-rebuilds: only for streams.<stream>.image attribute

---

doozer/.devcontainer/dev.Dockerfile
doozer/doozerlib/olm/bundle.py

Introduce logic to label bundles differently depending on the group release mode, which can make bundles available either to future releases or in pre-release indexes.
[This hack run](https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/hack/job/lmeyer/job/lmeyer-dev/job/dev-build%252Folm_bundle/38/console) against [this config](https://github.com/openshift-eng/ocp-build-data/pull/3424/files) produced [local-storage-operator-metadata-container-v4.14.0.202308281027.p0.g089e32e.assembly.stream-2](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2655730) which I added to a [test advisory](https://errata.devel.redhat.com/advisory/119637) along with dependencies so we can really exercise this new capability.

[ART-7318][ART-5526] introduce doozer operator_index_mode for pre-releases

---

doozer/doozerlib/cli/release_gen_payload.py
doozer/tests/cli/test_gen_payload.py

If a package is already listed in exempted_packages, don't make a noise in assembly_issues.

gen-payload: respect exempted_packages option

---

doozer/doozerlib/distgit.py
doozer/doozerlib/exectools.py
doozer/doozerlib/metadata.py
doozer/tests/test_distgit/test_generic_distgit.py

Updates gen-payload and images:rebase commands to auto-create missing distgit branches.
This is a bit hacky and doesn't work for rpms.

Train Doozer to auto-create missing distgit branches

---

doozer/doozerlib/cli/release_gen_payload.py

When debugging assembly issues it's important to know the rhcos build_id and nvr,
so we are sure about which rhcos & nvr has the inconsistency
- `./doozer --group openshift-4.11 inspect:stream FAILED_CONSISTENCY_REQUIREMENT`
```
Assembly does not permit: 
[RHCOS and 'driver-toolkit' should use the same build of package 'kernel', but RHCOSBuild:x86_64:411.86.202308300701-0 has kernel-modules-4.18.0-372.70.1.el8_6 and driver-toolkit-container-v4.11.0-202308310342.p0.g28589b0.assembly.stream has kernel-4.18.0-372.71.1.el8_6, 
RHCOS and 'driver-toolkit' should use the same build of package 'kernel-rt', but RHCOSBuild:x86_64:411.86.202308300701-0 has kernel-rt-devel-4.18.0-372.70.1.rt7.228.el8_6 and driver-toolkit-container-v4.11.0-202308310342.p0.g28589b0.assembly.stream has …
```

Include rhcos build_id & image nvr in assembly issue

---

pyartcd/pyartcd/pipelines/build_microshift.py

Missed microshift since it was not built in ocp4

kick off scan after microshift build

---

pyartcd/pyartcd/pipelines/ocp4_scan.py

[ocp4_scan](https://saml.buildvm.openshift.eng.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Focp4_scan/517575/console) job has a warning `Task was destroyed but it is pending!` after releasing the lock
I believe this should fix it

[ocp4_scan] Wait for redis lock manager connection destroy op

---

pyartcd/pyartcd/pipelines/build_microshift.py

Reverts openshift-eng/art-tools#36
Connection not allowed from ocp-artifacts to buildvm

Revert "kick off scan after microshift build"

---

pyartcd/pyartcd/pipelines/ocp4.py
pyartcd/pyartcd/record.py

Right now we are not resistant to rpm build failures, as we are to images.
If for some reason an rpm rebase/build fails, we are blocked and fail to build
images & produce nightlies, which can be very bad.
Test run https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Focp4/46517/console

[ocp4] Handle rpm build failures

---

doozer/doozerlib/distgit.py
doozer/tests/test_distgit/test_image_distgit/test_image_distgit.py

In the current code, we get when building on a new branch:
```
fatal: The current branch rhaos-4.13-rhel-9 has no upstream branch.
To push the current branch and set the remote as upstream, use
git push --set-upstream origin rhaos-4.13-rhel-9
```
We cannot configure `git` to do `push.autoSetupRemote`, as our git is too old. So move away from rhpkg to push, and use git directly.

distgit: Push to origin

---

pyartcd/pyartcd/pipelines/promote.py

Recently we had a case where rc promotion jumped the gun and went in parallel with prepare-rel, and 
4.14.0-rc.0 didn't get image advisory embedded in it's metadata, and a bunch
of unexpected things happened which confused us ([slack thread](https://redhat-internal.slack.com/archives/C04L1FPFHNH/p1694072265386539))
We have a check in place which complains if this happens, 
make it apply for candidate assemblies as well.

[promote] Make sure image advisory exists for candidate-type assemblies

---

pyartcd/pyartcd/pipelines/ocp4.py
pyartcd/pyartcd/plashets.py
pyartcd/pyartcd/util.py
pyartcd/tests/test_util.py

This PR will account for changes in `group.yaml`, where we can set the release phase for a specific group to be `eol`

Handle EOL release phase

---

pyartcd/pyartcd/pipelines/build_microshift.py
pyartcd/pyartcd/pipelines/promote.py
pyartcd/pyartcd/util.py
pyartcd/tests/test_util.py

- Don't skip advisory prep if build is pinned or PR is not created - do it again (reentrant behavior)
- Check if expected builds are pinned - if not create PR
- Add wait and retry for moving advisory to QE
- Refactor / simplify slack thread communication
Test run: https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fbuild-microshift/579/console
Slack thread: https://redhat-internal.slack.com/archives/C048BG69N8H/p1694115877311999

[build-microshift] - Don't skip advisory prep and other job enhancements

---

doozer/doozerlib/image.py

Reverts openshift-eng/art-tools#20

mass-rebuilds: only for `streams.<stream>.image` attribute

---

pyartcd/config.example.toml
pyartcd/pyartcd/pipelines/prepare_release.py
pyartcd/pyartcd/pipelines/promote.py
pyartcd/pyartcd/util.py
pyartcd/tests/test_util.py

https://issues.redhat.com/browse/ART-7674
- No longer send qe email on prepare, no updates when advisories / release-jira is updated (which is a rare case)
- Instead send qe email once as part of promote
- Create new subtask on release-jira for this, mark task closed when completed, so that if promote runs again, we don't send repeated emails.
- Select subtasks based on title rather than fixed number which can be brittle/wrong
release ticket template: https://issues.redhat.com/browse/ART-4223
Should go with https://github.com/openshift-eng/aos-cd-jobs/pull/3950
Test run: https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/hack/job/sidsharm-aos-cd-jobs/job/build%252Fpromote-assembly/19/console

ART-7624 Send qe email during promote rather than prepare

---

pyartcd/pyartcd/pipelines/build_microshift.py

Follow up to https://github.com/openshift-eng/art-tools/pull/31
This was somehow missed in #31 - fixing that
Test run: https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fbuild-microshift/592/console

Don't skip advisory prep if builds are pinned

---

pyartcd/pyartcd/jenkins.py
pyartcd/pyartcd/locks.py
pyartcd/pyartcd/pipelines/build_microshift.py
pyartcd/pyartcd/pipelines/cleanup_locks.py
pyartcd/pyartcd/pipelines/gen_assembly.py
pyartcd/pyartcd/pipelines/ocp4.py
pyartcd/pyartcd/pipelines/operator_sdk_sync.py
pyartcd/pyartcd/pipelines/review_cvp.py
pyartcd/pyartcd/runtime.py
pyartcd/pyartcd/slack.py
pyartcd/tests/test_jenkins.py

Must go with https://github.com/openshift-eng/aos-cd-jobs/pull/3959
The actual change is represented by setting identifiers for all locks created by `ocp4` equal to the Jenkins build path.
The build path is the build URL minus the host name; so given a build URL as https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Focp4/46870/, all locks created within that run will be identified as `job/aos-cd-builds/job/build%252Focp4/46870`.
This identifier will be then used by a scheduled lock cleanup procedure, which will release all the locks who are identified by a build that's no longer running.
A [test ocp4 build](https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/hack/job/dpaolell/job/ocp4/238/) created `build-lock-4.10` with value …

ART-7628 Store Jenkins build path as lock identifier

---

pyartcd/pyartcd/jenkins.py
pyartcd/pyartcd/pipelines/ocp4_scan.py
pyartcd/pyartcd/pipelines/olm_bundle.py
pyartcd/pyartcd/pipelines/promote.py
pyartcd/pyartcd/pipelines/rebuild.py

Provide all lock-using jobs with the capability of tracking Jenkins builds:
- ocp4_scan
- rebuild
- olm_bundle
- promote

ART-7628 Store Jenkins build path as lock value

---

pyartcd/pyartcd/locks.py
pyartcd/tests/test_locks.py

Using `:` as a separator in Redis keys allows for a better visualization in the UI.
Tested with:
```
import asyncio
from pyartcd import redis
from pyartcd.locks import LockManager
async def main():
lock_manager = LockManager([redis.redis_url()])
locks = await lock_manager.get_locks()
for lock in locks:
print(f'{lock} - {await lock_manager.get_lock_id(lock)}')
print('-----------------------------------------')
locks = await lock_manager.get_locks('4.5')
for lock in locks:
print(f'{lock} - {await lock_manager.get_lock_id(lock)}')
if __name__ == '__main__':
asyncio.new_event_loop().run_until_complete(main())
```

Use : separator for lock names

---

pyartcd/pyartcd/pipelines/build_sync.py
pyartcd/pyartcd/redis.py

Currently, we store build-sync fail counters on Redis even when the count is 0. To improve data observability, this PR proposes to keep only those > 0, so that it will be evident at a first glance what versions have been failing to sync.

Only keep fail counters > 0

---

doozer/doozerlib/metadata.py

We can get this error when a distgit branch doesn't exist, log it so we know
which image/rpm has the issue
Test run https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Focp4_scan/528137/console

Log cgit url error

---

doozer/doozerlib/assembly_inspector.py

tags
`IMPERMISSIBLE` is not generated anymore.

gen-assembly: Generate MISSING_SHIP_OK_TAG for kernels without ship-ok

---

elliott/elliottlib/cli/find_builds_cli.py
elliott/elliottlib/errata.py
elliott/tests/test_errata.py
elliott/tests/test_find_builds_cli.py

https://issues.redhat.com/browse/ART-2892 
- Find and attach rhcos brew builds for a release if they exist - to the image advisory. 
- Rhcos nvr names follow a pattern - constructed using the build id and arch fetched from rhcos images in the assembly - (example https://brewweb.engineering.redhat.com/brew/packageinfo?packageID=80343)
- If rhcos nvr is not found, do nothing
- We also need to set file attributes in Errata Tool for `coreos-assembler-git.tar.gz` that comes with every rhcos nvr. Without this advisory cannot transition to QE
- filemeta API - https://errata.devel.redhat.com/documentation/developer-guide/api-http-api.html#advisories
- [filemeta discussion on slack](https://redhat-internal.slack.com/archives/GDBRP5YJH/p1690812515872239)
- filemeta view - …

 ART-2892 Attach rhcos builds to payload advisory #578 

---

pyartcd/tests/test_jenkins.py

pyartcd unit tests are currently failing on
```
File "/home/dpaolell/develop/github.com/openshift/art-tools/pyartcd/tests/test_jenkins.py", line 72, in test_get_build_url_and_path
self.assertEqual(jenkins.get_build_url(), None)
AssertionError: 'build-url' != None
```

Make jenkins test environment independent

---

elliott/elliottlib/cli/find_bugs_sweep_cli.py
pyartcd/pyartcd/pipelines/prepare_release.py

This allows us to permit bugs that may have component-build mismatch due to some
reason, but are still valid to ship. This mismatch can be due to rpm components being
mentioned in image bugs or base image bugs whose builds we don't ship but still we
would want to ship the bugs
I also discovered that we can fail with a not obvious error when a subtask does not have any description 
set which is the reason for [327b8d3](https://github.com/openshift-eng/art-tools/pull/71/commits/327b8d3911a04fb48001694cec7fb958f091f650)
See https://github.com/openshift-eng/ocp-build-data/pull/3549
Test run: https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fprepare-release/858/console

attach-cve-flaws: Permit explicitly included bugs

---

pyartcd/pyartcd/locks.py
pyartcd/pyartcd/pipelines/ocp4.py
pyartcd/pyartcd/pipelines/ocp4_scan.py
pyartcd/pyartcd/pipelines/olm_bundle.py
pyartcd/pyartcd/pipelines/promote.py
pyartcd/pyartcd/pipelines/rebuild.py
pyartcd/tests/pipelines/test_ocp4.py
pyartcd/tests/pipelines/test_promote.py

This PRs introduces a `run_with_lock()` function that acts like a wrapper for the try/lock/except/finally operations. This will make it easier for us to write code that runs a coroutine in a locked context upon certain conditions.
Test runs:
- [ocp4_scan](https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Focp4_scan/531150/console)
- [ocp4](https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Focp4/47084/console)

Wrap try/lock/except/finally operations in locks.run_with_lock()

---

pyartcd/pyartcd/locks.py
pyartcd/pyartcd/pipelines/ocp4.py
pyartcd/tests/test_locks.py

When running a build in `test` assembly, compose lock may not be acquired if there's another compose build ongoing for the same version. This leads to undesired waits and longer testing times. Making this lock assembly aware will let us build plashets for `test` assembly without uselessly blocking on resource acquisition
Seeking for lgtm, approve labels

Make compose lock assembly aware

---

elliott/elliottlib/cli/verify_attached_bugs_cli.py
elliott/tests/test_verify_attached_bugs_cli.py

Got the following error:
```
TypeError: categorize_bugs_by_type() missing 1 required positional argument: 'permitted_bug_ids'
```
The bug was introduced by https://github.com/openshift-eng/art-tools/commit/9f3b49306db5eb7af1614244614300d848747099

Fix TypeError in verify-attached-bugs

---

doozer/doozerlib/cli/__main__.py
doozer/doozerlib/cli/scan_osh.py
doozer/doozerlib/runtime.py
pyartcd/pyartcd/__main__.py
pyartcd/pyartcd/jenkins.py
pyartcd/pyartcd/pipelines/brew_scan_osh.py
pyartcd/pyartcd/pipelines/ocp4.py

Find all the builds tagged into our candidate tags, get the last brew event ID from the saved file `event.json` in workspace. Run scans for all of the builds with brew event after the last run. If there is no last run, get all the latest builds and run the scans.
Successful test [run](https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/hack/job/ashwin-aos-cd-jobs/job/build%252Fscan-osh-new/19/console).

[ART-7730] Trigger SAST scans for builds in candidate tags

---

doozer/requirements.txt

PyGithub 2.1 is currently raising this error:
```
File "/usr/local/lib/python3.9/site-packages/github/GithubRetry.py", line 74, in __init__
kwargs["allowed_methods"] = kwargs.get("allowed_methods", Retry.DEFAULT_ALLOWED_METHODS.union({"GET", "POST"}))
AttributeError: type object 'Retry' has no attribute 'DEFAULT_ALLOWED_METHODS'
```
Pinning a specific version that proved to be working in a local environment.
Context: https://redhat-internal.slack.com/archives/GDBRP5YJH/p1696419743125039?thread_ts=1696419695.085749&cid=GDBRP5YJH

Pin PyGithub

---

pyartcd/pyartcd/jenkins.py
pyartcd/pyartcd/pipelines/promote.py
pyartcd/tests/pipelines/test_promote.py

ec.0 promote job [failed](https://saml.buildvm.openshift.eng.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fpromote-assembly/857/) on readJSON jenkins pipeline step flaking for perfectly valid json, rerunning it did the job - but [missing](https://redhat-internal.slack.com/archives/CJARLA942/p1696352245035539) cincinnati PRs can cause unecessary delays. The remaining steps outside of pyartcd promote.py are sending release message on umb, create cincinnati PRs, validating rhsas - I would like to move the cincinnati step inside pyartcd, so all important steps are done before the possibility of flaking on json
Should go with https://github.com/openshift-eng/aos-cd-jobs/pull/3983
Requesting /lgtm

Move cincinnati PR creation to promote.py

---

elliott/elliottlib/cli/attach_cve_flaws_cli.py
elliott/tests/test_attach_cve_flaws_cli.py

`elliott attach-cve-flaws` failed to create CVE mapping exclusion for RHCOS builds (https://redhat-internal.slack.com/archives/C03JYDGPX8F/p1695894086384359?thread_ts=1695893433.497649&cid=C03JYDGPX8F).
The problem is that `Erratum.errata_builds` doesn't include RHCOS builds. This PR changes to another API get attached builds.

Fix CVE mapping for RHCOS

---

elliott/elliottlib/cli/common.py
elliott/elliottlib/cli/move_builds_cli.py
elliott/elliottlib/cli/verify_attached_operators_cli.py
elliott/tests/test_verify_attached_operators.py

Automate pre-release gathering of bundle dependencies to a single advisory.
https://issues.redhat.com/browse/ART-7781

[ART-7781] --gather-dependencies for elliott verify-attached-operators

---

pyartcd/pyartcd/pipelines/gen_assembly.py

When creating a candidate or standard release, there can be a case when we do not have
a matching set of nightlies for all arches - we've been seeing this issue when
creating 4.14 Release candidates ([job](https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fgen-assembly/673/)) - this is due to x64 Release Controller running behind due
to pending nightlies, from other arch RCs.
In this case we still want to use x64 nightly as the basis for the RC, and then let the other arch
builds be selected accordingly by the brew event, and manually fit in RHCOS images. If anything
is inconsistent, build-sync will warn/complain, so allowing this gets us to the next step
requesting /lgtm and /approve

[gen-assembly] Allow limiting arches for all assembly types

---

doozer/doozerlib/cli/__main__.py
doozer/doozerlib/cli/gen_assembly_helper.py

Sometimes we need to manually hack in a particular rhcos build in an assembly,
or find pullspecs for some arches which were excluded when running gen-assembly,
this helps with that.
```
$ ./doozer --group openshift-4.14 gen-assembly:rhcos 414.92.202309222337-0
...
rhcos:
machine-os-content:
images:
aarch64: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:1d3f7859caf06708720482372bfaf36571fe0a8565093cebac21a5feb4dc97d0
ppc64le: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:cbc8861b311be4bc900f4b53179995317eb4c2f1ce25814ceff7b2be30ebc3ff
s390x: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:a5d0b8cd2ba52feb9076f7f1f269f8c8b3aed546e5dfd92ca13e13e1405125c8
x86_64: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:74ea50e311c11a3aa4257397f9fd2ac1208ec22dc62b4c5a6a615fdd …
```

gen-assembly rhcos helper

---

pyartcd/pyartcd/pipelines/ocp4.py

Notifying about a mass rebuild before acquiring the lock can be misleading. This PR proposes to be a little more verbose (acceptable in case of mass rebuilds, that do not happen every day) and make it clear:
- when a version wants to mass rebuild (acquiring the lock)
- when the mass rebuild has actually started (lock acquired)
- when the mass rebuild has terminated (lock released)
Follows https://github.com/openshift-eng/art-tools/pull/94

Notify about mass rebuilds when they actually start/complete

---

pyartcd/pyartcd/pipelines/build_microshift.py

Don't error out the job, if ocp-artifacts can't connect to buildvm. Report back in slack

Update microshift sync error message

---

doozer/doozerlib/cli/scan_sources.py

https://issues.redhat.com/browse/ART-7954
Tested with https://github.com/openshift-eng/ocp-build-data/pull/3643
```
./doozer --assembly=stream --group 'openshift-4.15'@4.15-update-build-data-org --data-path https://github.com/locriandev/ocp-build-data --images openshift-base-nodejs config:scan-sources
2023-10-18 10:02:54,087 INFO openshift-base-nodejs config_digest sha256:5fa2beca671ca46d957547e08ad3cfba1b0b512c57994757c8d82896a4956963 is differing from sha256:734bb25abfe89ce7f032a202d62f21725288e8b69ed809f3f643d62a9b7a2878
2023-10-18 10:02:54,090 INFO $22: ['git', 'log', '-1', '--format=%s'] - [cwd=/tmp/oit-or_of314.tmp/ocp-build-data]: Executing:cmd_gather
2023-10-18 10:02:54,092 INFO Time elapsed (hh:mm:ss.ms) 0:00:00.002366 in exectools.py:167 from scan_sources.py:203:rc, …
```

[ART-7954] Ignore image config change on noop commit message

---

doozer/doozerlib/cli/release_gen_payload.py

I traced the lifecycle of an image that the release controller failed to import. The job shows no error mirroring, but the mirroring operation lasts exactly 30 seconds.
If an exception is swallowed, neither the release controller nor heterogeneous payloads stand a chance, so do not proceed.

Fail on image mirroring timeout

---

elliott/elliottlib/cli/common.py
elliott/elliottlib/cli/verify_attached_operators_cli.py

When we move builds, there are usually checks running on an advisory
which block it from moving to QE, so don't fail on that.
Also update print statements for the new `--gather-dependencies` flag.

[verify-attached-operators] gather-dependencies Don't fail on move state error

---

doozer/doozerlib/cli/scan_sources.py

Follow up to https://github.com/openshift-eng/art-tools/pull/110
Test
- File that has noop commit - `./doozer --assembly=stream --group 'openshift-4.15'@4.15-update-build-data-org --data-path https://github.com/locriandev/ocp-build-data --images atomic-openshift-cluster-autoscaler config:scan-sources`
- File without noop commit - `./doozer --assembly=stream --group 'openshift-4.15'@4.15-update-build-data-org --data-path https://github.com/locriandev/ocp-build-data --images openshift-base-nodejs config:scan-sources`

ART-7954 scan-sources:noop - Fetch commit for the metadata file

---

pyartcd/pyartcd/pipelines/build_microshift.py

Potentially fixes error `Exception: [ErrataException("Erratum 122497: base: Validation failed: Errata Fetch Malware Scanning results job hasn't finished, please wait\n")]`
Since tests are taking longer to finish, increasing retry count to `5` and interval to `1200` seconds
_Requesting lgtm and approve_

[build_microshift] Increase timeout to change to advisory to QE

---

.github/workflows/doozer-unit-tests.yaml
.github/workflows/elliott-unit-tests.yaml
.github/workflows/pyartcd-unit-tests.yaml
doozer/doozerlib/__init__.py
doozer/doozerlib/cli/__init__.py
doozer/setup.py
elliott/elliottlib/__init__.py
elliott/elliottlib/cli/common.py
elliott/pyproject.toml
pyartcd/pyartcd/__init__.py
pyartcd/pyartcd/cli.py
pyartcd/setup.py

- Add `artcd --version`.
- Fix `elliott --version` and `doozer --version` commands
- Provide `elliottlib.__version__`, `doozerlib.__version__`, and `pyartcd.__version__` to get versions in program.

Fix package version prints

---

doozer/doozerlib/cli/scan_sources.py
pyartcd/pyartcd/pipelines/ocp4_scan.py

When scanning sources, and before checking for any changes, we'll do a rebase from `openshift` into `openshift-priv` if the public upstream has newer contents. This will let us build the latest updates and reduce delays between PRs merge time and their actual availability in a nightly.
This is the proposed workflow:
- check if a component has a public upstream; if not, no need to rebase. Otherwise,
- check if commit SHAs on public and private upstreams match; if they do, no need to rebase (quick API call, no need to clone anything. Otherwise, clone repo and
- check if public upstream is an ancestor of the private one. If so, private has newer content, thus no need to rebase. Otherwise
- attempt a fast-forward; if successful, push to priv and mark the repo as changed (will trigger a …

ART-3506 Rebase openshift-priv if needed

---

elliott/elliottlib/util.py

This is to prepare for upcoming change https://github.com/openshift-eng/ocp-build-data/pull/3723
which adds ci image with golang-builder in its name, which can confuse elliott.
```
$ ./elliott go -n ci-openshift-golang-builder-latest-container-v1.0.0-20231018.el9.p0.g21ff43a.assembly.test
Following nvrs are built with openshift-golang-builder-container-v1.20.10-202310161945.el9.gbbb66ea:
ci-openshift-golang-builder-latest-container-v1.0.0-20231018.el9.p0.g21ff43a.assembly.test
```
Looking for /lgtm and /approve

[elliott go] Be exact when looking for golang builder image

---

pyartcd/pyartcd/jenkins.py
pyartcd/pyartcd/pipelines/cleanup_locks.py

In case a build has been aborted (thus leaving an orphan lock in Redis), and then manually removed by a user, the clean up procedure will complain that the build associated to a lock cannot be found in Jenkins. Currently, it will display a warning and skip that lock.
This leads to locks that are never clean up. This PR proposes to delete those locks for which associated builds cannot be found. The only side effect I am seeing is that if we run `pyartcd` locally, we'll be creating locks with random IDs. These will be garbage collected by the cleanup procedure. It seems reasonable to me, as we shouldn't be creating those locks outside of a Jenkins context, and we might forgot to clean them up.

Delete locks if associated build cannot be found

---

elliott/elliottlib/cli/attach_cve_flaws_cli.py
elliott/tests/test_attach_cve_flaws_cli.py

re: [ART-7731](https://issues.redhat.com/browse/ART-7731)
doc only want update solution for image advisory, our default value of image advisory already have SHA text included, so no need to update solution section when converting RHBA to RHSA

ART-7731 not update solution for doc

---

doozer/doozerlib/cli/scan_sources.py
pyartcd/pyartcd/pipelines/ocp4_scan.py

-  `_do_shas_match()` updated to use `git ls-remote` to compare commit SHAs on private/public upstrams without calling GitHub API
- if `ocp4-scan` is built with `DRY_RUN` set to True, pass the `--dry-run` option to `doozer config:scan-sources`; this will not perform the rebase, only print what it would have done
- re-enable the currently disabled rebase procedure, by adding the `--rebase-priv` flag to doozer
Test run: https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Focp4_scan/553872/console

ART-8041 Use git ls-remote instead of GitHub API

---

doozer/doozerlib/golang_builder_FIPS_wrapper.sh

In one case, a component was using 'go install ...' to perform the build instead of directly running 'go build'. The FIPS mitigations were not fully applied because the script was only looking for build invocations.

Treat go-install just as go-build

---

pyartcd/pyartcd/pipelines/build_microshift.py

Resolves error encountered at https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fbuild-microshift/707/consoleFull
Also move advisory to qe before running verify

Advisory id should be passed as string

---

elliott/elliottlib/errata.py
elliott/tests/test_errata.py

Got an error when running this command in promote-assembly job:
```
File "/mnt/workspace/jenkins/working/cd-builds_build_promote-assembly/art-tools/elliott/elliottlib/errata.py", line 667, in _get_image_name
return pattern.sub(r'openshift\1/', list(repo['docker']['target']['repos'].keys())[0])
IndexError: list index out of range
```
By looking at this issue, it seems to me that Errata Tool has changed its response message format of the API.

Fix advisory-images command

---

doozer/doozerlib/assembly.py
doozer/doozerlib/cli/__init__.py
doozer/doozerlib/cli/release_gen_payload.py
doozer/doozerlib/telemetry.py
doozer/requirements.txt
pyartcd/pyartcd/cli.py
pyartcd/pyartcd/exectools.py
pyartcd/pyartcd/pipelines/build_sync.py
pyartcd/pyartcd/telemetry.py
pyartcd/requirements.txt

- pyartcd: Add tracing for build-sync pipeline job.
- doozer: Add tracing for releases:gen-payload command.
This can be enabled by setting env var `TELEMETRY_ENABLED=1`.
Inter-process trace context is propagated through env var `TRACEPARENT`.
Currently traces are printed to stderr. In the future production traces
should be forwarded to a collector.
Requires https://github.com/openshift-eng/art-tools/pull/99 to include pyartcd/elliott/doozer versions in traces.

Add experimental distributed tracing with OpenTelemetry

---

doozer/doozerlib/cli/scan_sources.py

For safety reasons, we only rebase one component at the time at each ocp4-scan run. This was intended to avoid disasters when deploying a dangerous feature for the first time.
Rebase has now been running for a while, and Splunk can be used to monitor its actions:
- [this search](https://rhcorporate.splunkcloud.com/en-US/app/rh_openshift_art/search?q=search%20host%3Dbuildvm*%20index%3Djenkins_console%20%7C%20search%20%22Fast-forwarded%22&display.page.search.mode=smart&dispatch.sample_ratio=1&workload_pool=standard_perf&earliest=-30d%40d&latest=now&display.page.search.tab=events&display.general.type=events&sid=1699348347.1350805_7AF866D2-E4C8-447C-A52A-318F2E6F81AF) shows the fast-forward operations into openshift-priv
- [this one](https://rhcorporate.splunkcloud.com/en-US/app/rh_openshift_a …

ART-3506 Do not limit rebase into -priv to one component

---

doozer/doozerlib/comment_on_pr.py
doozer/doozerlib/distgit.py
doozer/tests/test_comment_on_pr.py
pyartcd/pyartcd/pipelines/ocp4.py
pyartcd/pyartcd/pipelines/ocp4_scan.py
pyartcd/tests/pipelines/test_ocp4.py

The comment on PR feature aims to comment on the PR that kicked off an ocp4 build for images. The feature was disabled because multiple messages were being posted on the same PR ([example](https://github.com/openshift/network-tools/pull/75)). But it was because I was checking whether the entire message was there. For new messages, the NVR will change. This issue is now fixed by checking if there is any comment with `[ART PR BUILD NOTIFIER]`

[ART-6149] Fix comment on PR feature

---

doozer/doozerlib/distgit.py

We don't want to [comment on upstream PRs](https://github.com/openshift/cluster-olm-operator/pull/32#issuecomment-1809702693) for test builds

Comment on source PR only for stream

---

pyartcd/pyartcd/pipelines/build_microshift.py

Fix messages like this: https://redhat-internal.slack.com/archives/C05FEGT8SH2/p1700026353265139?thread_ts=1700026352.836499&cid=C05FEGT8SH2

Fix microshift-sync link in slack

---

elliott/elliottlib/cli/create_cli.py
pyartcd/pyartcd/pipelines/prepare_release.py

**boilerplate_name** in the create advisory function need to be one of the type ['rpm', 'microshift', 'metadata', 'image', 'extras'] with match the key in errata template
**impetus** is used for advisory metadata info need to be one of [standard, cve, ga, test]
**kind** is used for advisory class that need to be one of [rpm, image]

ART-7731 use actual advisroy type for release

---

doozer/doozerlib/cli/scan_osh.py
pyartcd/pyartcd/pipelines/brew_scan_osh.py

Ticket: https://issues.redhat.com/browse/ART-7926
Policy document [here](https://docs.google.com/document/d/1GsT3tvw5qf3sOSAkTSVWnMIO6vzIuirhsVhhsbK_qf0/edit#heading=h.uilnzpc6uuc7)
Proposed improvement requests to osh-cli
-  https://issues.redhat.com/browse/OSH-376
- https://issues.redhat.com/browse/OSH-390
This will significantly reduce the time to search for scan results. But moving forward with a less efficient approach due to urgency from ProdSec.
- New feature `--create-jira-tickets`:
Finds the last successfully completed scan for a brew package for a particular version and creates a an OCPBUGS ticket if found. ProdSec only wants us to look at `scan-results-imp` file ([example](https://cov01.lab.eng.brq2.redhat.com/osh/task/361037/log/sriov-network-operator-contai …

[ART-7926] Create OCPBUGS tickets to track vulnerabilities

---

pyartcd/pyartcd/pipelines/promote.py

art-dashboard release page could be really useful for people to keep track of advisories for a OCP release
_Ready to merge. Requesting /lgtm and /approve_

Adding art-dash link to promote email

---

doozer/doozerlib/cli/scan_osh.py

Fixes issue in [job](https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fscan-osh/13773/console), where `nvrs_for_scans` is an empty list

Skip when no nvrs to scan

---

pyartcd/pyartcd/pipelines/brew_scan_osh.py

Reverts openshift-eng/art-tools#178
Looks like scan-osh is a bit different from other jobs. Will collect all issues and create one PR

Revert "[scan-osh] Add version to title"

---

doozer/doozerlib/cli/scan_osh.py

Before, if we use the `--check-triggered` option, it will filter out the NVRs that already have been sent for scanning. With is update, it will retain a copy of the initial list of NVRs so that tickets can be raised.
Also order the builds by ascending order of brew event so that the latest build will be attached to OCPBUGS ticket, if we are raising it

[scan-osh] check JIRA tickets for all NVR components

---

doozer/doozerlib/cli/scan_osh.py

Skip all RPMs from OCPBUGS workflow run

[scan-osh] OCPBUGS workflow only for container images

---

doozer/doozerlib/cli/scan_osh.py

We only want to update the description, since other fields can be edited by humans

[scan-osh] Update only description when there is a new build

---

doozer/doozerlib/cli/scan_osh.py

Due to an upstream bug, sometimes we don't have the scan-imp file. Lets skip that component now.

[scan-osh] Skip component if can't file imp file

---

doozer/doozerlib/cli/images_streams.py
elliott/elliottlib/bzutil.py

Jira admins changed the current field to "Target Version - old"
this is the new "Target Version"
https://issues.redhat.com/rest/api/2/field

Use new target version field

---

doozer/doozerlib/cli/__main__.py
pyartcd/pyartcd/util.py

`--assembly` option duplicates what we already have as a global Runtime option.
Also handle cases where the provided assembly is not found. This also covers the case where `--assembly` is not provided, thus defaulting to `test` assembly.

doozer config:read-assembly remove redundant param "assembly"

---

elliott/elliottlib/bzutil.py

OCPBUGS-21035 got ON_QA in October, got back to Assigned, got fixed again. The logic for establishing if this was fixed at the cutoff time is short circuited, as the question "was it ON_QA or higher before cutoff time?" is Yes.
This changes the query to ask for the status at the cutoff time.
The `WAS` operator is explained here: https://support.atlassian.com/jira-software-cloud/docs/jql-operators/

bug sweep: look more precise at cutoff event

---

doozer/doozerlib/cli/rpms.py

Follows https://github.com/openshift-eng/art-tools/pull/209
Since microshift is disabled, it won't show up in this command, without specifying the disabled flag. We need this option so that our SAST pipeline can see which all RPMs are managed by us.
_Requesting /lgtm and /approve_

Include disabled rpms flag for rpms:print

---

doozer/doozerlib/cli/scan_osh.py

Recently we had issues in which a new OCPBUGS ticket was opened even though no new issues were found. Seems like this happens when there are two scans for the same NVR. When ART triggers a scan, we check to see if there is none triggered for that NVR. So if we comment on the ticket, we will be able to see which two scans the automation looked at, at that point in time, since the status changes after a while.

[scan-osh] Comment on bugs ticket with scan urls

---

doozer/doozerlib/cli/scan_osh.py

-  dry-run option should continue instead of returning so that more than one package can be checked.
- After popping `open_issues` it will always be empty, to using `issue.key` to display the ticket name.

[scan-osh] (minor fixes) Dry run should continue, update logs

---

doozer/doozerlib/cli/scan_osh.py

Alongside https://github.com/openshift-eng/ocp-build-data/pull/3973
Till now only scan results of images were being checked. This PR starts looking at RPMs that ART is managing.
Test ticket that got raised: https://issues.redhat.com/browse/ART-8415

[ART-7926] [scan-osh] Enable OCPBUGS pipeline for ART managed RPMs

---

pyartcd/pyartcd/pipelines/promote.py

rhel-coreos annotions can be empty, get rhcos version from release

ART-8427: get rhcos version from release

---

doozer/doozerlib/cli/scan_osh.py

Updates in this PR related to OCPBUGS pipeline feature:
- Exclude bundle builds (their NVRs will contain either `metadata-container` or `bundle-container`)
- Include base images
- Include non-release images

[scan-osh] include base, non-release images, skip bundle builds

---

doozer/doozerlib/cli/scan_osh.py

group.yml will activate for all images. If we need to disable any particular image, we can override in that image config, by setting it to false

[scan-osh] enable OCPBUGS workflow by default

---

doozer/doozerlib/cli/scan_osh.py

If its the first time we are creating a ticket for a component, we don't need to comment on the ticket like [this](https://issues.redhat.com/browse/OCPBUGS-24468?focusedId=23591413&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-23591413).

[scan-osh] skip comment if skip_diff_check is enabled

---

doozer/doozerlib/cli/scan_osh.py
pyartcd/pyartcd/jenkins.py
pyartcd/pyartcd/pipelines/ocp4.py
pyartcd/tests/pipelines/test_ocp4.py

We had been triggering the job after ocp4 since our initial requirement was to scan images that we were building. Since the requirement had evolved to scan everything in our candidate tags, a scheduled job was setup for that purpose. 
During the scheduled job, all the brew builds since the previous run will be collected and the workflow executed.

[scan-osh] trigger only for scheduled job

---

doozer/doozerlib/cli/release_gen_payload.py
doozer/doozerlib/image.py
doozer/doozerlib/metadata.py
doozer/doozerlib/repodata.py
doozer/tests/cli/test_gen_payload.py
doozer/tests/test_metadata.py

- Introduce new config "exempt_rpms" intended to replace "exempted_packages". Right now both of them will be effective.
- Accept glob pattern matching 
After we have moved over all ocp-build-data branches from exempted_packages to exempt_rpms, 
I'll make a PR to remove the exempted_packages config from here

scan-sources pattern match for exempted packages

---

doozer/doozerlib/cli/__main__.py
doozer/doozerlib/cli/config.py

Refactoring `doozer config:*` to a separate file `config.py` in an effort to make the `__main__.py` more readable

Refactor doozer config:* commands to separate file

---

doozer/doozerlib/cli/scan_osh.py

For RPMs, we need to raise one ticket per rhel version, not ocp version. Hence updating the workflow to reflect that, while including optimizations. This will be a periodic scan set to run every hour.
How the new workflow will look like:
- Retrieve all builds from brew candidate tags, from [erratatool.yml](https://github.com/openshift-eng/ocp-build-data/blob/e2ec932f1594e3f5be49ab6d1b9003218c6f81ce/erratatool.yml#L8)
- Get all the latest builds from those tags
- If scan issues exist for those NVRs, raise a ticket (if there isn't already one)
- RPM tickets will be raised with title having rhel version as the prefix, while images will OCP version as the prefix.
Note:
Since this new workflow will immediatelly open tickets for a version, since all latest builds are checked (in the previous …

[ART-7926] [scan-osh] Update  OCPBUGS workflow

---

doozer/doozerlib/cli/scan_osh.py

Follows https://github.com/openshift-eng/art-tools/pull/247
`listTagged(extra=True)` does not have `source`

[scan-osh] get source URL from getBuild

---

doozer/doozerlib/distgit.py

This PRs introduces 2 changes during images rebase:
1. Also rebase base images (rhel) as well as golang builders
2. If we're trying to match upstream config during rebase, add an extra layer to the Dockerfile to make sure that upstream RHEL version matches the one we have configured locally. Break the build otherwise.
This will let developers use their preferred builder versions before feature freeze, but will enforce that there is agreement upon an image RHEL version

ART-8476 doozer images:rebase assert RHEL version equivalence in Dockerfiles

---

doozer/doozerlib/distgit.py

```
File "/mnt/workspace/jenkins/working/aos-cd-builds/build%2Focp4/art-tools/doozer/doozerlib/distgit.py", line 1652, in _update_image_config
for alt_config in alt_configs:
TypeError: 'NoneType' object is not iterable
2023-12-18 20:06:22,615 ERROR [containers/ironic-rhcos-downloader] 'NoneType' object is not iterable
```

Fix altconfig getter

---

pyartcd/pyartcd/locks.py
pyartcd/pyartcd/pipelines/build_sync.py

[First build](https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/hack/job/dpaolell/job/build-sync/6/console) (lock acquired)
[Second build](https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/hack/job/dpaolell/job/build-sync/7/console) (trying to acquire the lock)

Protect build-sync for stream assembly with a Lock

---

doozer/doozerlib/cli/images_health.py
doozer/tests/test_images_health.py

This commit integrates Art-Dash links into the health:images reports. The goal is to enhance accessibility and traceability of the reports by providing direct links to Art-Dash for detailed build histories. This streamlines the process for analyzing build concerns and improves overall efficiency.
Key Changes:
- `generate_art_dash_history_link` to create Art-Dash URLs based on build records.
- Updated `images_health` to incorporate these Art-Dash links.
- Modified YAML output in `images_health` to handle URLs correctly and prevent YAML dump from adding unwanted quotes.
This enhancement is part of ongoing efforts to improve our build monitoring tools, simplifying the workflow for developers and release managers. A regex post-processing step has been added to ensure clarity and readability …

[ART-8256] Add Art-Dash Link to Health:Images Reports

---

doozer/doozerlib/assembly_inspector.py
doozer/doozerlib/cli/release_gen_payload.py
doozer/tests/cli/test_gen_payload.py

Enhance `doozer release:gen-payload` command to check external rpms
installed in RHCOS and group images.
Use following config to enable external package check for RHCOS and
group images.
```yaml
check_external_packages:
- name: cri-o
tag: rhaos-{MAJOR}.{MINOR}-rhel-{RHCOS_EL_MAJOR}-candidate
condition: match
- name: containernetworking-plugins
tag: rhaos-{MAJOR}.{MINOR}-rhel-{RHCOS_EL_MAJOR}-candidate
condition: match
- name: NetworkManager
tag: rhaos-{MAJOR}.{MINOR}-rhel-{RHCOS_EL_MAJOR}-candidate
condition: greater_equal
```

[ART-8416] Add support for checking external packages

---

doozer/doozerlib/cli/images_streams.py

When opening an alignment PR, it can be useful to track the URL of the Jenkins run that caused this PR to be open, for debugging purposes. The URL will be provided in a separate comment, thus leaving the PR description unchanged.

Track Jenkins job run on alignment PRs

---

pyartcd/pyartcd/pipelines/build_sync.py

```
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

Fix fail count comparison

---

doozer/doozerlib/util.py

The [job](https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/scheduled-builds/job/sync-ci-images/) is currently broken because
```
File "/mnt/workspace/jenkins/working/scheduled-builds/sync-ci-images/art-tools/doozer/doozerlib/util.py", line 255, in what_is_in_master
raise IOError('Unable to find which openshift release resides in master')
OSError: Unable to find which openshift release resides in master
```
https://raw.githubusercontent.com/openshift/release/master/ci-operator/config/openshift/images/openshift-images-master.yaml response appears to have changed:
```
promotion:
to:
- name: "4.16"
namespace: ocp
```

Fix sync-ci-images

---

doozer/doozerlib/cli/images_streams.py

[sync-ci-images](https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/scheduled-builds/job/sync-ci-images/) is still breaking with:
```
TypeError: create_comment() missing 3 required positional arguments: 'commit', 'path', and 'position'
```
Replacing `create_comment()` with `create_issue_comment()` should fix that

Fix PR comment creation

---

elliott/elliottlib/cli/__main__.py
elliott/elliottlib/cli/get_golang_versions_cli.py
elliott/elliottlib/util.py
elliott/tests/test_get_golang_versions_cli.py

To support https://issues.redhat.com/browse/ART-8426
Reviving https://github.com/openshift-eng/elliott/pull/543 
Since we're supporting different go versions in a payload with canonical_builders_from_upstream config option,
it's useful to get builder info for all images in a payload to compare.
I extracted out code from verify-payload to get nvrs from payload, so it could be used here as well.
```
$ ./elliott -g openshift-4.16 go -r registry.ci.openshift.org/ocp/release:4.16.0-0.nightly-2023-12-19-195550 --report -o json
...
[
{
"builder_nvr": "openshift-golang-builder-container-v1.20.10-202310161945.el9.gbbb66ea",
"building_count": 65
},
{
"builder_nvr": "openshift-golang-builder-container-v1.21.3-202311211941.el9.g7b42730",
"building_count": 55
},
{
"builder_nvr": …
```

ART-8426 Support showing go version for payload

---

artcommon/artcommonlib/arch_util.py
artcommon/tests/test_arch_util.py
doozer/doozerlib/assembly_inspector.py
doozer/doozerlib/cli/gen_assembly_helper.py
doozer/doozerlib/cli/get_nightlies.py
doozer/doozerlib/cli/release_gen_assembly.py
doozer/doozerlib/cli/release_gen_payload.py
doozer/doozerlib/image.py
doozer/doozerlib/rhcos.py
doozer/doozerlib/util.py
doozer/tests/test_util.py
elliott/elliottlib/cli/find_builds_cli.py
elliott/elliottlib/cli/find_unconsumed_rpms.py
elliott/elliottlib/cli/rhcos_cli.py
elliott/elliottlib/cvp.py
elliott/elliottlib/rhcos.py
elliott/elliottlib/util.py
elliott/tests/test_find_builds_cli.py
pyartcd/pyartcd/pipelines/build_microshift.py
pyartcd/pyartcd/pipelines/build_sync.py
pyartcd/pyartcd/pipelines/operator_sdk_sync.py
pyartcd/pyartcd/pipelines/promote.py
pyartcd/pyartcd/util.py

Move these functions from doozer/elliott into artcommon as they're duplicated:
- go_arch_for_brew_arch
- go_suffix_for_arch
- brew_arch_for_go_arch
- brew_suffix_for_arch
Also move arch names/suffixes to artcommon. Improve unit tests

Move duplicated functions to artcommon

---

elliott/elliottlib/cli/get_golang_versions_cli.py
elliott/tests/test_get_golang_versions_cli.py

```
elliott -g openshift-4.16 go -r registry.ci.openshift.org/ocp/release:4.16.0-0.nightly-2023-12-22-051418
```
is currently breaking with `AttributeError: module 'elliottlib.rhcos' has no attribute 'get_container_configs'`

Fix elliott go command

---

doozer/doozerlib/cli/release_gen_assembly.py
pyartcd/pyartcd/pipelines/gen_assembly.py

https://issues.redhat.com/browse/ART-8114
Design doc: https://docs.google.com/document/d/1S_ivD8Sh85LuZKnClqvoRvIhn4hNJQA76jpfUaFZjUA/edit
- Add `--prerelease` flag to gen-assembly, to indicate a candidate assembly is a prerelease 
- https://github.com/openshift-eng/aos-cd-jobs/pull/4069
- ECs are always prerelease
- Inherit advisories and release jira from last EC in RC.0
- Do not inherit prerelease advisory
- Configure operator index mode to prerelease when indicated.
Prepare release will use these appropriately: https://github.com/openshift-eng/art-tools/pull/263
```
$ doozer --assembly stream --group openshift-4.15 --arches x86_64 release:gen-assembly --name rc.1 from-releases --nightly 4.15.0-0.nightly-2023-12-19-033450 --prerelease
...
group:
advisories:
extras: 123982
image: 123983 …
```

ART-8114 gen-assembly configures prerelease advisories

---

elliott/elliottlib/cli/find_bugs_sweep_cli.py
elliott/elliottlib/errata.py
pyartcd/pyartcd/pipelines/build_microshift.py
pyartcd/pyartcd/pipelines/prepare_release.py
pyartcd/pyartcd/slack.py

https://issues.redhat.com/browse/ART-8115
Summary
- Add and use `--permissive` mode to `elliott find-bugs:sweep` to avoid erroring out on invalid bugs when we prep ECs and RCs.
- Build and attach bundle builds to prerelease advisories
- Skip attach-cve-flaws when we're prepping a prerelease assembly
- Gather dependencies from other advisories when prepping prerelease advisory
- Use `rhose async auto` release for preGA advisories - with https://github.com/openshift-eng/ocp-build-data/pull/4101
- Bring all prep-release slack messages in a single thread

ART-8115 Modify prepare-release job for prereleases

---

doozer/doozerlib/cli/scan_osh.py

- Adding `order by created ASC` to ensure that JIRA search results are consistant. Previous ticket is retrieved using `closed_issues.pop()`
- Update regex, to handle descriptions like [this](https://issues.redhat.com/browse/OCPBUGS-23695)

[scan-osh] Fix JIRA search query issue and update regex

---

elliott/elliottlib/cli/__main__.py

get_container_configs has been moved to artcommonlib.

Fix verify-payload command

---

elliott/elliottlib/bzutil.py

Sometimes a CVE tracker may have invalid pscomponent labels.
We were asked by ProdSec to not correct this kind of labels by ourselves. To unblock our pipeline, I would like to introduce a new label format `art:pscomponent:<component>` to temporarily override this label.

Allow to override pscomponent label for CVE trackers

---

pyartcd/pyartcd/pipelines/prepare_release.py

If a prerelease advisory is detected, skip populating the rpm advisory

[ART-8625] skip populating rpm advisory, if prerelease

---

doozer/doozerlib/cli/scan_osh.py

Since logs are not sequential, this will make it easier to debug

[scan-osh] better error message

---

doozer/doozerlib/olm/bundle.py

Remove `operator_index_mode` from `group.yml`. We directly specify the field in assembly config during gen assembly.
Alongside https://github.com/openshift-eng/art-tools/pull/296

[prerelease] remove operator index mode group.yml

---

doozer/doozerlib/cli/scan_osh.py

Earlier builds were replacing later builds since for RPMs we do not consider OCP version.

[scan-osh] Fix RPM ticket update bug

---

doozer/doozerlib/olm/bundle.py

add a comment as to why we're not using `ga-plus` for now.

doozer olm/bundle: ga-plus explanation

---

doozer/doozerlib/cli/scan_osh.py

The characters `~` and `_` need to be included since microshift nightly NVR contains it. Eg: `microshift-4.16.0~0.nightly_2024_01_05_154400-202401052128.p0.g0467b5a.assembly.microshift.el9`

[scan-osh] update regex for microshift nightly

---

doozer/doozerlib/cli/scan_osh.py

`containernetworking-plugins-1.4.0-1.rhaos4.15.el8` was being recognized as a container instead of an RPM as it should be. Updating to "-container"

[scan-osh] Fix container classification bug

---

doozer/doozerlib/cli/scan_osh.py

Container builds like `cnf-tests-container-v4.13.4-5` do not have stream

[scan-osh] some builds do not have stream

---

elliott/elliottlib/cli/verify_attached_bugs_cli.py

OCPBUGS-26416 status was closed with Obsolete, we should not block this with invalid status

support bug close status with Obsolete

---

elliott/elliottlib/cli/__main__.py
elliott/elliottlib/cli/find_bugs_golang_cli.py
elliott/elliottlib/runtime.py
elliott/elliottlib/util.py
pyartcd/tests/pipelines/test_promote.py

https://issues.redhat.com/browse/ART-8426
```bash
$  ./elliott -g openshift-4.14 --assembly 4.14.8 find-bugs:golang --update-tracker
2024-01-10 23:38:00,625 INFO Cloning config data from https://github.com/openshift-eng/ocp-build-data.git
2024-01-10 23:38:01,732 INFO Using branch from group.yml: rhaos-4.14-rhel-8
2024-01-10 23:38:01,743 INFO Constraining brew event to assembly basis for 4.14.8: 55461598
2024-01-10 23:38:03,534 INFO Searching for open security trackers with target version 4.14.0,4.14.z assigned to ART
2024-01-10 23:38:04,280 INFO Found 7 bugs
2024-01-10 23:38:04,280 INFO Bugs by component: {'openshift': ['OCPBUGS-16101', 'OCPBUGS-17330'], 'openshift-golang-builder-container': ['OCPBUGS-16107', 'OCPBUGS-16276', 'OCPBUGS-17336', 'OCPBUGS-20203'], 'microshift': …
```

ART-8426 Find golang trackers and determine if they are fixed

---

doozer/doozerlib/cli/__main__.py

Fix `sync-for-ci`. 
Test run: https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fsync-for-ci/224781/console

Pass reposync enabled repos to invocation

---

art-cluster/pipelines/config/argocd/project/art-cd/common/art-cd-image/base.yaml
art-cluster/pipelines/config/argocd/project/art-cd/common/image/base.yaml
art-cluster/pipelines/config/argocd/project/art-cd/common/secrets/art_quay_dev.yaml
art-cluster/pipelines/config/argocd/project/art-cd/common/secrets/aws-doomsday-bucket-readonly.yaml
art-cluster/pipelines/config/argocd/project/art-cd/quay-doomsday-backup/base/doomsday-pipeline-task.yaml
art-cluster/pipelines/config/argocd/project/art-cd/quay-doomsday-backup/base/doomsday-pipeline.yaml
art-cluster/pipelines/data/project/art-cd/image/Containerfile.base
art-cluster/pipelines/data/project/art-cd/image/files/etc/yum.repos.d/pulp.repo
art-cluster/pipelines/data/project/art-cd/image/files/etc/yum.repos.d/rcm-tools.repo

For https://issues.redhat.com/browse/ART-8241
New in this PR:
- Setting art-tools as the home for our all our pipeline config, except ones that need to be kept secret, which shall remain in art-config
- New directory structure for our future pipelines
- Base image config for our future pipelines (migrating from` aos-cd-jobs/tekton-pipelines`)
- Tekton pipeline for quay backup as mentioned in the ticket including their argocd config

[ART-8241] Add pipeline for quay backup

---

elliott/elliottlib/cli/__main__.py
elliott/elliottlib/cli/find_builds_cli.py
elliott/elliottlib/cli/remove_builds_cli.py
elliott/elliottlib/cli/verify_attached_operators_cli.py

- Extract out removing builds flags from `find-builds` into `remove-builds`
- Deprecate remove flags from `find-builds`
- This follows our pattern of `attach-bugs`, `remove-bugs` and `find-bugs` being separate; reducing code paths in build sweep and cleaning it up overall, which helps in discovering and fixing issues faster
- I did not discover this flag being used in any of our pipeline code.
- `./elliott -g openshift-4.14 --assembly 4.14.9 remove-builds --all --use-default-advisory image --noop`
- NVR that is not attached to advisory - `./elliott -g openshift-4.14 --assembly 4.14.9 remove-builds openshift-enterprise-deployer-container-v4.14.0-202401121302.p0.g286cfa5.assembly.stream --use-default-advisory image --noop`
- NVR that is attached to advisory - `./elliott -g openshift-4.14 …

elliott - remove builds cli

---

doozer/doozerlib/repodata.py
doozer/tests/test_repodata.py

Discovered during CentOS Stream 9.4 migration. Some files in the repo are compressed with xz instead of gz.
This was resulting in build-sync failure with:
```
gzip.BadGzipFile: Not a gzipped file (b'\xfd7')
```

Support decompressing xz repo files

---

pyartcd/pyartcd/pipelines/images_health.py

Mention just the count on the main message and dump the details in the thread.
Using reference from [art attention](https://github.com/openshift-eng/aos-cd-jobs/blob/32ee80a778ec40e4044e133b89b2c09ad18b00f4/scheduled-jobs/scanning/unresolved-art-threads/unresolved-thread-notification.py#L123-L138)

Update images health message

---

doozer/doozerlib/cli/release_gen_payload.py

We don't want non-critical assembly issues to show up on Release Controller info bubble.
Going with a minimal change right now, as there are bigger changes planned like deprecating or 
splitting the `outdated_rpms_in_stream_build` code

Ignore outdated_rpms_in_stream_build assembly issue for RC inconsistency

---

pyartcd/pyartcd/pipelines/promote.py

Trigger the tekton pipeline on cluster (configs [here](https://github.com/openshift-eng/art-tools/tree/main/art-cluster/pipelines/config/argocd/project/art-cd/quay-doomsday-backup/base)) which backs up the promoted payload.]
Needs https://github.com/openshift-eng/aos-cd-jobs/pull/4076

[ART-8241] Backup promoted payloads to AWS

---

doozer/doozerlib/distgit.py
doozer/tests/test_distgit/test_generic_distgit.py
doozer/tests/test_distgit/test_image_distgit/test_image_distgit.py
doozer/tests/test_distgit/test_image_distgit/test_push_image.py

Use the correct distgit branch and build target when using `alternative_upstream` config
Ref. [ART-8476](https://issues.redhat.com/browse/ART-8476)
Test build [ose-baremetal-runtimecfg-container-v4.16.0-202401241117.p0.g448f2b7.assembly.test](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2868302) used rhel8 builders, picked up the right branch ([rhaos-4.16-rhel-8](https://pkgs.devel.redhat.com/git/containers/baremetal-runtimecfg/log/?h=rhaos-4.16-rhel-8)) and was tagged into `rhaos-4.16-rhel-8-candidate` tag

ART-8476 canonical builders

---

art-cluster/pipelines/config/argocd/project/art-cd/quay-doomsday-backup/base/cluster-role-binding.yaml

Should fix `Error: failed to list PipelineResources from namespace art-cd: pipelineresources.tekton.dev is forbidden: User "system:serviceaccount:art-cd:pipeline" cannot list resource "pipelineresources" in API group "tekton.dev" in the namespace "art-cd"
`

Allow pipeline user to trigger tekton pipelines

---

pyartcd/pyartcd/pipelines/build_microshift.py
pyartcd/pyartcd/slack.py

- Add support for reactions in slack message
- Add `:art-attention:` for Microshift sync, until we can automatically trigger it from microshift build

Support for reactions, :art-attention: for microshift-sync

---

doozer/doozerlib/distgit.py

see https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Focp4/51685/consoleFull
```
>>> import bashlex
>>> bashlex.parse('[ -f abc ] && echo yes')
[ListNode(parts=[CommandNode(parts=[WordNode(parts=[] pos=(0, 1) word='['), WordNode(parts=[] pos=(2, 4) word='-f'), WordNode(parts=[] pos=(5, 8)
word='abc'), WordNode(parts=[] pos=(9, 10) word=']')] pos=(0, 10)), OperatorNode(op='&&' pos=(11, 13)), CommandNode(parts=[WordNode(parts=[] pos
=(14, 18) word='echo'), WordNode(parts=[] pos=(19, 22) word='yes')] pos=(14, 22))] pos=(0, 22))]
>>> bashlex.parse('[[ -f abc ]] && echo yes')
File "<stdin>", line 1, in <module>
File "/home/jdelft/.local/lib/python3.11/site-packages/bashlex/parser.py", line 601, in parse
parts = …
```

bashlex uses POSIX-1834 standard

---

doozer/doozerlib/cli/release_gen_payload.py

when in build-sync logs, after scanning all images and doing checks the output is
permitted: false and so viable: false the job will fail and it is  misleading to have a warning here.
**WARNING Assembly is not permitted. Will not apply changes to imagestreams.**

log severity change

---

artcommon/artcommonlib/util.py
artcommon/tests/test_util.py
doozer/doozerlib/distgit.py
doozer/tests/test_distgit/test_image_distgit/test_image_distgit.py

If there is no matching "when" clause but ART and upstream rhel versions match, apply canonical builders

Use canonical builders when rhel versions match

---

pyartcd/pyartcd/locks.py
pyartcd/tests/test_locks.py

In our current locks when lock timeout is reached they silently expire, no exception is raised. This is an expected pattern in redis, the lib we use implements https://redis.io/docs/manual/patterns/distributed-locks/ and sets keys with an expiration time.
But it's unexpected for us. We've had a pattern of using BIG job-wide locks, since we started using locks in jenkins. From what I remember there was no expiry time in jenkins locks, so as long as the `lock() {do something}` ran, it kept the lock active.
We're in the middle of these 2 approaches, and bad things can happen without us noticing. 
Therefore set lock timeouts to a BIG value, effectively not relying on them (until we change our lock use pattern)

Set default lock timeout to a BIG value

---

pyartcd/pyartcd/slack.py

`The server responded with: {'ok': False, 'error': 'channel_not_found'}`

Fix slack reaction error

---

artcommon/artcommonlib/util.py
artcommon/tests/test_util.py
doozer/doozerlib/distgit.py

`util.merge_objects()` is failing when we try and merge configs during rebase, by throwing this Exception:
```
AttributeError: 'dict' object has no attribute 'move_to_end'
```
This could be solved by casting the object into an OrderedDict, still it has problems when overriding existing keys: it will not preseve tested leaves. More details in [this thread](https://redhat-internal.slack.com/archives/GDBRP5YJH/p1706796879603389?thread_ts=1706774096.594939&cid=GDBRP5YJH)

Fix rebase with a deep_merge() function

---

pyartcd/pyartcd/slack.py

PR https://github.com/openshift-eng/art-tools/pull/369 swapped the order of 2 optional parameters, but missed updating say_in_thread.

Fix say_in_thread method

---

art-cluster/pipelines/config/argocd/project/art-cd/common/pipeline-list-role.yaml
art-cluster/pipelines/config/argocd/project/art-cd/common/pipeline-list-rolebinding.yaml

To fix error `Error: failed to list PipelineResources from namespace art-cd: pipelineresources.tekton.dev is forbidden: User "system:serviceaccount:art-cd:pipeline" cannot list resource "pipelineresources" in API group "tekton.dev" in the namespace "art-cd"`

Add pipeline list role for art-cd

---

doozer/doozerlib/cli/release_gen_payload.py

in case the inconsistencies are only about  AssemblyIssueCode.OUTDATED_RPMS_IN_STREAM_BUILD the msgs will be empty

report nothing when list of inconsistencies is empty

---

doozer/doozerlib/go.real

This symlink prevents ArgoCD from working with art-tools repo.

Remove go.real symlink

---

elliott/elliottlib/metadata.py

Fixes error `AttributeError: 'ImageMetadata' object has no attribute 'branch_el_target'`

Add missing branch_el_target func in elliott

---

art-cluster/pipelines/config/argocd/project/art-cd/quay-doomsday-backup/base/doomsday-pipeline.yaml

Reverts openshift-eng/art-tools#377
Not required, since the problem was with `tkn` client on build vm. It was an old version.

Revert "[tekton] Update tekton pipeline api version"

---

doozer/doozerlib/distgit.py

Brew build targets are not `alternative_upstream` aware. This should fix it:
https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Focp4/51955/console

Update metadata.config after merging alternative_upstream

---

artcommon/artcommonlib/util.py

fix the error of https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fgen-assembly/802/console
we convert the date format for advisory usage, need to convert back when doing date calculation

fix date format

---

elliott/elliottlib/cli/find_bugs_sweep_cli.py

fix https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fpromote-assembly/1003/consoleFull

set operator_bundle_advisory default value to metadata

---

doozer/doozerlib/metadata.py
elliott/elliottlib/metadata.py

Follows changes in https://github.com/openshift-eng/art-tools/pull/361
Fixes error like
```
OSError: No builds detected for using prefix: 'ci-openshift-golang-builder-latest-container-v4.16.', extra_pattern: '*', assembly: 'stream', build_state: 'COMPLETE', el_target: 'None'
```
that is caused by, for example, `.el8` build being the latest one, and we're looking for el9 builds. We'll filter out the build because of [this check](https://github.com/openshift-eng/art-tools/blob/main/doozer/doozerlib/metadata.py#L483)

Use .el<version> suffix to find Brew builds

---

doozer/doozerlib/cli/release_gen_payload.py

After the introduction of `.el<version>` suffixes in Brew builds, we are getting empty builds lists after [filtering them out](https://github.com/openshift-eng/art-tools/blob/main/doozer/doozerlib/metadata.py#L485).
When doing so, `branch_el_target()` reads from the image metadata, which must be updated to use the `alternative_upstream` stanza when using canonical builders. This el target must match the one indicated by the build suffix. If we don't consider the alternative_upstream config, we'll get el9 branches (read from the image main config) for .el8 builds, and we'll filter these builds out thus not finding any.
Unfortunately, to do so we need to clone distgits and do the upstream intended rhel version check.

build-sync: fix runtime initialization

---

doozer/doozerlib/cli/config.py

To fix https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fpromote-assembly/998/console
doozer is expecting http://download-node-02.eng.bos.redhat.com/brewroot/packages/libgcrypt/1.10.0/10.el9_0/ to be alive but looking at http://download-node-02.eng.bos.redhat.com/brewroot/packages/libgcrypt/1.10.0/ the naming convention is little different, so skip it in that case
Test run
https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fpromote-assembly/1002/console
2024-02-07 20:36:03,843 WARNING Failed to find RPM brewroot directory /mnt/redhat/brewroot/packages/libgcrypt/1.10.0/10.el9/src

Make sure brewroot dir exists

---

doozer/doozerlib/comment_on_pr.py

Since PR in build feature was intended for upstream repos, skipping ocp-build-data, for comments like this [one](https://github.com/openshift-eng/ocp-build-data/pull/4386#issuecomment-1941647714).

[ART-8912] Skip ocp-build-data for pr in build feature

---

doozer/doozerlib/metadata.py
elliott/elliottlib/metadata.py

Fixes https://github.com/openshift-eng/art-tools/pull/402. Using `branch_el_target()` go compose the search pattern lead to an error, as this is drawn from group.yml and can differ from the actual rhel target we're interested in. So for example in 4.14 it was always finding el8 builds for `openshift-clients`, that in turn has both rhel 8 and 9 build targets.

Use multiple search patterns when looking for builds

---

pyartcd/pyartcd/pipelines/operator_sdk_sync.py

yaml.load is allowed to construct arbitrary Python objects, whereas yaml.safe_load limits this ability to simple objects like integers, lists, dictionaries, ...

Use yaml.safe_load instead of yaml.load

---

doozer/doozerlib/image.py
doozer/doozerlib/metadata.py

Fix for https://saml.buildvm.openshift.eng.bos.redhat.com:8888/job/scheduled-builds/job/sync-ci-images/94192/
`OSError: No builds detected for using prefix: 'ci-openshift-golang-builder-latest-container-v4.16.', extra_pattern: '*', assembly: 'stream', build_state: 'COMPLETE', el_target: 'None'`
Test
`doozer --assembly stream --group openshift-4.16  images:streams gen-buildconfigs -o test.yml`

Fix rhel pattern when None

---

doozer/doozerlib/cli/release_gen_assembly.py

Same as https://github.com/openshift-eng/art-tools/pull/395, for `release:gen-assembly`

Honor canonical builders from upstream in gen-assembly

---

artcommon/artcommonlib/build_util.py
doozer/doozerlib/distgit.py
doozer/tests/test_distgit/test_image_distgit/test_image_distgit.py
elliott/elliottlib/cli/find_builds_cli.py
elliott/elliottlib/metadata.py
elliott/tests/test_metadata.py

For pre-releases, canonical builders will be enabled and `alternative_upstream` configs will be defined for many components. This feature requires distgits to be cloned (discussion [here](https://redhat-internal.slack.com/archives/C06625LHXQS/p1708975115881139?thread_ts=1708610009.547359&cid=C06625LHXQS)) in order to take the alternative_upstream into consideration, but Elliott knows nothing about them and it is not trivial to teach him.
As an alternative, we can hack `find-builds` like this: if canonical builders are enabled and `alternative_upstream` is defined for an image, it most likely means that upstream is behind ART's main config with respect to the rhel target. Therefore, when looking for builds, Elliott can consider a downgraded (-1) rhel target to find, for example, `.el8` …

Fix elliott find-builds

---

pyartcd/pyartcd/jenkins.py

Needed by https://github.com/openshift-eng/aos-cd-jobs/pull/4089

Set SKIP_PLASHETS to False for scheduled ocp4 builds

---

artcommon/artcommonlib/util.py
artcommon/tests/test_util.py
doozer/doozerlib/util.py
pyartcd/pyartcd/pipelines/build_microshift.py
pyartcd/pyartcd/pipelines/build_sync.py
pyartcd/pyartcd/pipelines/operator_sdk_sync.py
pyartcd/pyartcd/pipelines/promote.py
pyartcd/pyartcd/pipelines/tag_rpms.py
pyartcd/pyartcd/util.py

Instead of sending a Slack notification every time `tag-rpms` fails for any reason, catch any `ChildProcessError` exception thrown by Doozer (meaning something went wrong when tagging/untagging packages) and send a notification every 5 failures. Use a fail counter to handle this periodicity, just like `build-sync` does.
Needs https://github.com/openshift-eng/aos-cd-jobs/pull/4097 to merge along

Tag rpms spam on a schedule

---

doozer/doozerlib/cli/olm_bundle.py

Reverts openshift-eng/art-tools#459
https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Folm_bundle/10969/console is failed

Revert "olm-bundle:rebase-and-build clone distgits if needed"

---

doozer/doozerlib/cli/olm_bundle.py

Re-revert https://github.com/openshift-eng/art-tools/pull/459, but do not prevent cloning
Tested with:
```
doozer --assembly=stream --group=openshift-4.14 olm-bundle:rebase-and-build -- sriov-network-operator-container-v4.14.0-202403112340.p0.g7a362a5.assembly.stream.el8
```

olm-bundle: clone distgits when needed do not prevent cloning

---

doozer/doozerlib/repodata.py
doozer/tests/test_repodata.py

Switch to `defusedxml` to prevent issues reported by Snyk. 
`xml.etree.ElementTree` import in `doozer/doozerlib/repodata.py` is kept because `defusedxml.ElementTree` does not have `Element` class which is used in type annotations.

Use secure xml parser

---

doozer/doozerlib/cli/__main__.py

fix error `find: ‘/mnt/jenkins-workspace/reposync/4.6’: No such file or directory`

create reposync dirs if not exist

---

doozer/doozerlib/cli/release_gen_payload.py

There is an additional `$` to remove.

build-sync: Fix registry auth again

---

pyartcd/pyartcd/pipelines/operator_sdk_sync.py

in new version of tar --preserve-order is not supported, instead
> In -c, -r, or -u mode, each specified file or directory is added to the archive in the order specified on the command line.  By default, the contents of each directory are also archived.

fix operator_sdk_sync job

---

doozer/doozerlib/image.py

https://issues.redhat.com/browse/ART-9243
This was added 4 years ago in https://github.com/openshift-eng/doozer/pull/311 but is no longer valid for images, only for rpms

ART-9243 Remove "buildroot change" rebuild reason for images

---

pyartcd/pyartcd/pipelines/build_microshift.py
pyartcd/pyartcd/slack.py

Reverts openshift-eng/art-tools#487
Rolling back cause microshift build was [failing](https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fbuild-microshift/38/consoleFull)

Revert "Refactor slack, support for emojis"

---

artcommon/artcommonlib/util.py
pyartcd/pyartcd/pipelines/gen_assembly.py

If `gen-assembly` is run with `IN_FLIGHT_PREV = none` and a custom assembly (e.g. `art1234`), pyartcd will try to infer the inflight prev from the release schedule, and fail to do so. It is now throwing an exception, which prevents us from running gen-assembly with custom assemblies.
The proposed fix is to skip fetching the release date for custom assemblies, where IN_FLIGHT_PREV and PREVIOUS shall be None
[Test run ](https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fgen-assembly/13/console) (broke because `koji.GenericError: No such build: 'ubi8-container-416.94.202403121338-0-1136'`)

Do not fetch the release date for custom assemblies

---

doozer/doozerlib/image.py
elliott/elliottlib/imagecfg.py

Alternative upstream section may override image name (e.g. https://github.com/openshift-eng/ocp-build-data/blob/f82bb057fef0f20ab67f34b3270742b9191b6e84/images/nmstate-console-plugin.yml#L54).
Currently when alternative upstream is effective, the image_name and image_name_short fields of ImageMetadata object don't respect the alternative upstream override.
The root cause of this issue is that the `ImageMetadata.name` and `ImageMetadata.name_in_short` are not updated after an alternative upstream config is applied. This PR fixes this issue by changing those two fields to properties to make sure their values are always up to date.

ART-9251: olm_bundle: Fix operand name resolution

---

elliott/elliottlib/cli/find_builds_cli.py

When reporting on found builds for an assembly, do not filter out builds that are attached to an advisory
```
$ elliott --assembly 4.15.5 -g openshift-4.15 find-builds -k rpm
...
Found 9 builds: 
conmon-2.1.7-10.rhaos4.15.el9
cri-o-1.28.4-5.rhaos4.15.git159b3c8.el8
cri-o-1.28.4-5.rhaos4.15.git159b3c8.el9
fuse-overlayfs-1.10-2.rhaos4.15.el8
libslirp-4.4.0-4.rhaos4.15.el8
openshift-4.15.0-202403180038.p0.gf1b5f6c.assembly.stream.el8
openshift-4.15.0-202403180038.p0.gf1b5f6c.assembly.stream.el9
slirp4netns-1.1.8-2.rhaos4.15.el8
toolbox-0.1.0-2.rhaos4.15.el8
```

find-builds: Report on all found builds

---

doozer/doozerlib/metadata.py
elliott/elliottlib/metadata.py

Currently we only get a single warning that goes like this:
```
No builds detected for using prefix: 'openshift-base-nodejs-container-v4.16.', extra_pattern: '*', assembly: 'test', build_state: 'COMPLETE', el_target: 'None'
```
This is the final message of an iterative process that attempts to find builds by progressively broadening the search pattern. It would be useful to see what queries are being attempted. Since it's happened in the past that `None` made it as a string into the search pattern, let us also assert that this is never happening. Crash otherwise (so we notice and fix).

latest_build_list(): log the search pattern when no builds are found

---

doozer/doozerlib/repodata.py

Recently when preparing [4.12.54](https://github.com/openshift-eng/ocp-build-data/pull/4570/files) we saw a case where a 4.12 image (ose-agent-installer-node-agent) 
contained non-latest rpms. This was being flagged by [build-sync](https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fbuild-sync/255/consoleFull) 
```
ose-agent-installer-node-agent:
- code: CONFLICTING_INHERITED_DEPENDENCY
msg: Expected image to contain assembly override dependencies NVR runc-1.1.6-5.2.rhaos4.12.el8
but found runc-1.1.6-5.1.rhaos4.12.el8 installed
permitted: false
- code: CONFLICTING_INHERITED_DEPENDENCY
msg: Expected image to contain assembly override dependencies NVR containernetworking-plugins-1.4.0-1.1.rhaos4.12.el8
but found …
```

Populate all non-modular rpms

---

art-cluster/pipelines/config/argocd/project/art-cd/fips-scanning/pipeline-task.yaml

`privileged: true` required for `check-payload`

[fips-tekton] fix, keep dry run for now

---

pyartcd/pyartcd/pipelines/build_microshift.py

Our logic doesn't validate assembly name for found nvrs, so it just goes with unshipped builds.
This can result in cases like this one https://github.com/openshift-eng/ocp-build-data/pull/4614/files 
where 4.15.7 build was pinned and attached to 4.15.8 
Tested with https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fbuild-microshift/81/console

Make sure assembly name matches found microshift build

---

elliott/elliottlib/cli/find_bugs_sweep_cli.py

Tested with https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fprepare-release/30/console

find-bugs:sweep - Skip attaching bugs if advisory is not present

---

doozer/doozerlib/runtime.py

This was leading to 2 different branches being checked out when running a command,
which inits runtime twice. It was because we overwrite the values that are passed to us, 
and the second time we init those are not available to us.
Double init'ng runtime looks to be an anti-pattern that we should get rid of, for now this 
should suffice.
Test:
doozer --assembly=4.13.39 --data-path=https://github.com/mbiarnes/ocp-build-data --working-dir . --group=openshift-4.13@prep-assembly-definition-4.13 release:gen-payload
Before:
INFO On commit: af871f15b5f638ac3ade385b8051eb5ebd6596b8 (prep-assembly-definition-4.13)
INFO On commit: 3620494c9c8910decf208453e72de95ba00f2cd6 (openshift-4.13)
After
INFO On commit: af871f15b5f638ac3ade385b8051eb5ebd6596b8 (prep-assembly-definition-4.13)
INFO On commit: …

Do not reinit group_commitish

---

elliott/elliottlib/bzutil.py
elliott/elliottlib/cli/verify_attached_bugs_cli.py

Discover cases when a 4.14 bug that is attached to an advisory, has a 4.15 parent bug which is not attached to any advisory.
```
$ elliott --assembly 4.14.21 -g openshift-4.14 verify-attached-bugs
...
Regression possible: Verified bug OCPBUGS-21217 is a backport of bug OCPBUGS-22034 which is on Verified but not attached to any advisory
```

Verify blocking bugs are attached to an advisory

---

pyartcd/pyartcd/pipelines/gen_assembly.py
pyartcd/pyartcd/pipelines/ocp4.py
pyartcd/pyartcd/pipelines/promote.py
pyartcd/pyartcd/pipelines/scan_for_kernel_bugs.py
pyartcd/pyartcd/pipelines/tag_rpms.py

Due to our jira instance being quite volatile we've been getting a lot of jira related job failures,
each of these job failures posts a lengthy traceback in slack which doesn't help.
Even otherwise traceback.format_exc from pyartcd aren't helpful and do not get to the actual error, so remove them

Do not post traceback to slack

---

elliott/elliottlib/bzutil.py

If anything goes wrong with the request to JIRA API at compile time, pyartcd won't compile. even if the pipeline run is not doing anything with elliott or jira.
So lets override it later

[ART-9446] Populate jira mappings 

---

pyartcd/pyartcd/pipelines/check_bugs.py

test job: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fcheck-bugs/35/console
in the test job it param has "--version 4.17 --version 4.16 --version 4.15 --version 4.14 --version 4.13 --version 4.12 --version 4.11 --version 4.7 --version 3.11" which is the list of choice we could build, but for check bugs job we only need check active release

only check bug for active release

---

pyartcd/pyartcd/__main__.py
pyartcd/pyartcd/pipelines/rebuild_golang_rpms.py
pyartcd/pyartcd/pipelines/update_golang.py
pyartcd/requirements.txt

https://issues.redhat.com/browse/ART-5994
Automate https://art-docs.engineering.redhat.com/sop/update-golang/ 
These commands are intended to be part of a job that release-artists can run, multiple times and depending on the state of things the pipeline decides to wait or take action & also run manually if needed.
The happy path would be:
- Someone/we create an ART ticket with qe approved golang builds.
- A release artist runs `update-golang --create-ticket` which
- validates golang nvrs
- checks if builds are already tagged and available in buildroot, if they are - complains.
- creates cwfconf ticket description, which release artist takes and creates a ticket with
- After/before the cwfconf ticket resolves, when we run `update-golang` - it 
- checks if golang-builder-container exists …

ART-5994 Automate golang update SOP

---

doozer/doozerlib/image.py
doozer/doozerlib/metadata.py

When `complete_before_event` is not set, we are not passing the `completeBefore` keyword argument to the Koji wrapper. As a consequence, a timestamp is getting auto assigned as follows:
```
elif method_name == 'listBuilds':
if 'completeBefore' not in kwargs and 'createdBefore' not in kwargs:
kwargs = kwargs or {}
kwargs['completeBefore'] = self.___before_timestamp
```
This has been acting as a filter to our build search, preventing us from picking up the latest news in some cases

Doozer: set completeBefore appropriately when searching for builds

---

elliott/elliottlib/rhcos.py

Using previous work done from https://github.com/openshift-eng/art-tools/pull/464 
Test:
(This was failing before)
elliott --quiet -g openshift-4.16 rhcos -r 4.16.0-0.nightly-2024-04-24-091844 -p kernel

Adjust elliott rhcos to new image label

---

doozer/doozerlib/cli/scan_fips.py

Since they are not used for shipping

[fips scan] skip CI builds

---

doozer/doozerlib/image.py
doozer/doozerlib/metadata.py

Reverts openshift-eng/art-tools#562
That change has proven to be harmful in case of named assemblies, where the brew event filtering wasn't properly applied to builds

Revert "Doozer: set completeBefore appropriately when searching for builds"

---

doozer/doozerlib/cli/config_plashet.py

os.system logs differently and it leads to weird behavior like
logs appearing at the end when the command breaks,
and not appearing if it succeeds.

Use cmd_assert instead of os.system

---

pyartcd/pyartcd/pipelines/promote.py

Ref https://issues.redhat.com/browse/ART-9550
Pipeline run has a defualt cutoff time of `1h`. Sometimes, the mirroring takes more time that that and hence will fail ([example](https://console-openshift-console.apps.artc2023.pc3z.p1.openshiftapps.com/k8s/ns/art-cd/tekton.dev~v1~PipelineRun/doomsday-pipeline-run-6rmp4)). Increasing to `4h` taking into account of retries

[tekton] [ART-9550] doomsday pipeline, increase timeout to 4hrs

---

art-cluster/pipelines/config/argocd/project/art-cd/fips-scanning/pipeline-task.yaml
art-cluster/pipelines/config/argocd/project/art-cd/fips-scanning/pipeline.yaml
doozer/doozerlib/cli/scan_fips.py
pyartcd/pyartcd/__main__.py
pyartcd/pyartcd/pipelines/ocp4.py
pyartcd/pyartcd/pipelines/scan_fips.py

Ref. https://issues.redhat.com/browse/ART-8272
The scan will clone payload images locally. This caused buildvm storage to be used up completely. Setting up scan on the cluster since pod storage is transient and independent. No need to clean images now, since the pod will be deleted after the run.
ocp4 test run [successful](https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/hack/job/ashwin-aos-cd-jobs/job/build%252Focp4/52/)
cluster pipeline [successful](https://console-openshift-console.apps.artc2023.pc3z.p1.openshiftapps.com/k8s/ns/art-cd/tekton.dev~v1~PipelineRun/fips-pipeline-run-tx62m)
Needs https://github.com/openshift-eng/aos-cd-jobs/pull/4139

[fips-pipeline] [ART-8272] Migrate scan to cluster

---

elliott/elliottlib/build_finder.py
elliott/elliottlib/bzutil.py
elliott/elliottlib/cli/find_bugs_golang_cli.py
elliott/elliottlib/cli/find_builds_cli.py
elliott/pyproject.toml

Bunch of fixes and enhancements for `elliott find-bugs:golang`
- Support `cve_id` as a property of our `Bug` class. This will appear for trackers and flaw bugs.
- The command right now finds bugs and start analyzing immediately. Instead 
- report on trackers and CVEs by default ([prettytable](https://pypi.org/project/prettytable/) makes the report look very nice and readable)
- `--analyze` flag to do analysis on found bugs
- Do not analyze bugs that don't appear to be golang compiler bugs (like golang lib bugs). Report / warn about them and exit
- Better jira comment when `--fixed-in-nvr` is passed
- Require `--art-jira` when updating tracker
- Remove noisy prints, move logs info -> debug

elliott find-bugs:golang enhancements

---

pyartcd/pyartcd/pipelines/ocp4.py

If there are no successful builds, skip triggering the job

[tekton] skip triggering if no ocp4 builds

---

doozer/doozerlib/olm/bundle.py

When building the bundle, the current branch and target rely on the global configuration, but some images have been migrated to RHEL 9 while the global configuration remains set to RHEL 8. To ensure consistency and accuracy in the build process, it is imperative to honor the specific configuration of each image. Therefore, this pull request aims to optimize build system to correctly identify and apply the specific configuration for each image instead of solely relying on the global configuration.
test job: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Folm_bundle/271/console

use branch in image config

---

Makefile
art-cluster/pipelines/config/argocd/project/art-cd/fips-scanning/pipeline-task.yaml

Openshift is automatically delimiting if the line length is tool long. Adding commands to the makefile for now
Successful [run](https://console-openshift-console.apps.artc2023.pc3z.p1.openshiftapps.com/k8s/ns/art-cd/tekton.dev~v1~PipelineRun/fips-pipeline-3wab09/logs)

[fips] update Makefile to support default python

---

doozer/doozerlib/cli/scan_osh.py

So that it doesn't pollute logs

[sast] change debug

---

art-cluster/pipelines/config/argocd/project/art-cd/common/image/base.yaml

So that art-cd build config will automatically trigger new builds when we push to art-tools

[artcluster] setup webhooks to trigger art-cd build auto

---

doozer/doozerlib/cli/olm_bundle.py
doozer/doozerlib/olm/bundle.py
doozer/tests/test_olm_bundle.py

If distgit branch doesn't exist, fail fast
```
./doozer --group=openshift-4.16 --assembly ec.6 olm-bundle:rebase-and-build --dry-run
ERROR One or more bundle branches do not exist: ['containers/ose-smb-csi-driver-operator-bundle/rhaos-4.16-rhel-8', 'containers/dpu-operator-bundle/rhaos-4.16-rhel-8']
```

Get missing bundle branches first

---

doozer/doozerlib/cli/olm_bundle.py
doozer/doozerlib/olm/bundle.py
doozer/tests/test_olm_bundle.py
pyartcd/pyartcd/pipelines/prepare_release.py

When preparing prerelease assembly like ECs, we set `operator_index_mode: pre-release` 
in assembly definition. This gets used by olm-bundle:rebase-and-build to set the appropriate 
labels on the bundle image. These are different for ECs and normal stream builds that we do.
So we cannot reuse normal stream builds that we build everyday via olm_bundle job for ECs,
or any assembly that has something different for `operator_index_mode` config than what's in
group.yml for the group. 
To get around this we opted to force rebuild bundle images for prerelease everytime, (except
when advisory was already populated which then we skipped). But this isn't perfect. We've been
seeing the bundle rebase and build command failures where it would fail if distgit branch doesn't
exist or if a rebase/build …

Select existing bundle image for assembly if delivery labels match

---

ocp-build-data-validator/validator/json_schemas/assembly_group_config.schema.json
ocp-build-data-validator/validator/json_schemas/rhcos.schema.json

4.16+ do not have `machine-os-content` anymore, make that property optional. Also, permit `allow_missing_brew_rpms` in group.yml.

Fix rhcos validator

---

pyartcd/pyartcd/util.py

Right now we're getting emails for build failures of images that we own (ci golang builders)
on our team address. Reroute these to art automation address.

Use art automation address for art image build fail emails

---

pyartcd/tests/pipelines/test_promote.py

Fixing tests from https://github.com/openshift-eng/art-tools/pull/609
Tests remain to be updated for that particular bit. So set skip flag, until
we update them

Tests are not updated for sigstore yet

---

doozer/doozerlib/cli/images.py
doozer/doozerlib/cli/images_streams.py

Allow images:print to filter based on what is in payload and support `{owners}` pattern.

Add owners support to images:print

---

pyartcd/pyartcd/pipelines/build_sync.py

compression app.ci backup from ~60mb to ~10mb
app.ci-backup.tar.gz in previous job:  https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fbuild-sync/1672/artifact/
after compress: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fbuild-sync/1690/artifact/

compression log for build_sync

---

artcommon/artcommonlib/exectools.py
elliott/elliottlib/cli/find_bugs_sweep_cli.py

Our job logs have considerably increased in length, making them hard to parse through.
- Make the cmd_gather `time elapsed` information debug
- Don't double warn in elliott find-bugs sweep

Cleanup prepare-release logs

---

doozer/doozerlib/cli/__main__.py
doozer/doozerlib/cli/olm_bundle.py
doozer/doozerlib/olm/bundle.py

Follow up to https://github.com/openshift-eng/art-tools/pull/582/files
This also deprecates `olm-bundle:build` and `olm-bundle:rebase` commands.
We don't use these anywhere in the pipeline since we always want to build and
rebase as a single operation. Supporting these now takes extra effort (with refactoring)
so remove them.

Fix olm bundle invocations

---

art-cluster/pipelines/config/argocd/project/art-cd/fips-scanning/pipeline-task.yaml
pyartcd/pyartcd/pipelines/scan_fips.py

- Remove `--dry-run`
- Message to `art-cluster-monitoring` for now, till where are confident the pipeline is not reporting false positives

[artc-fips] remove dry-run, message to art-cluster-monitoring

---

pyartcd/pyartcd/pipelines/gen_assembly.py

Depending on timing logics, it may happen that latest amd64 nightly does not have an equivalent set across all arches. In this case, release-artists might want to investigate and see if this is acceptable, or if a manual intervention is required to capture latest nightly changes.

gen-assembly: notify when non-latest green amd64 nightly is selected

---

elliott/elliottlib/cli/find_builds_cli.py

As part of `find-builds --attach` when we try make API request to ErrataTool to enable cdn repos, 
it can fail with `requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://errata.devel.redhat.com/api/v1/erratum/125775/metadata_cdn_repos`
This happens when we ask it to operate on cdn repos that do not exist. Reason is 
because we have a misconfig in our erratatool.yml file / or we haven't created them yet.
So enable what can be enabled and then complain.
see: [107](https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fprepare-release/107/consoleFull)
https://errata.devel.redhat.com/api/v1/erratum/125775/metadata_cdn_repos

Validate cdn repos

---

pyartcd/pyartcd/pipelines/prepare_release.py
pyartcd/pyartcd/pipelines/scan_fips.py

Slack reactions do not require `:` before and after

Fix reaction bug

---

pyartcd/pyartcd/pipelines/scan_fips.py

`sys.exit(1)` if there is a FIPS issue, so that the pipeline turns red, on the cluster

[fips] Error out if there is an issue

---

artcommon/artcommonlib/assembly.py

Permits are usually not allowed in standard assemblies. But after embargo lift, we would like to explicitly add the permit so that we make consciously publish private builds to public image streams.

allow EMBARGOED_CONTENT in standard permits

---

pyartcd/pyartcd/pipelines/prepare_release.py

Using the same logic as advance advisory prep. If pre-release is detected, drop all builds from metadata advisory and attach builds to pre-release advisory only (skipping metadata advisory prep).

Skip metadata population during pre-release

---

elliott/elliottlib/cli/find_builds_cli.py
elliott/elliottlib/cli/remove_builds_cli.py

This changes the stdin invocation to 
```
echo sriov-network-operator-metadata-container-v4.16.0.202404221110.p0.g3b79f5e.assembly.stream.el9-7 | 
./elliott --assembly ec.6 -g openshift-4.16 find-builds -k image -f -
```
to better adjust for other cli options we have

Dont try to read stdin by default

---

pyartcd/pyartcd/pipelines/update_golang.py

Since otherwise it will be added as string
```
[' ', '-', '-', 'p', 'u', 's', 'h']
```

golang builder append --push bug

---

doozer/doozerlib/rpm_builder_go_wrapper.sh

Seems like golang changed between 1.21 and 1.22, where `GOOS=windows` stopped to do the right thing by disabling CGO. This surfaced with builds of openshift-clients in 4.17 after updating the rhel9 build root to go-1.22.
This change helps the compiler in the build root to not try CGO when the target is windows.
Successful build with this change: https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=3070403
Fixes https://issues.redhat.com/browse/OCPBUGS-32516

rpm fips wrapper: Explicitly allow no CGO for GOOS=windows

---

doozer/doozerlib/distgit.py
doozer/tests/test_distgit/test_resolve_image_from_upstream_parent.py

Ref. [ART-7129](https://issues.redhat.com/browse/ART-7129)
Currently we are trusting upstream with whatever `FROM` clause they use. If, for example, a 4.16 component has 
```
FROM registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.21-openshift-4.15
```
we would use `oc` to infer the exact pullspec for a 4.15 builder, and use that in the downstream Dockerfile. Even with matching {MAJOR}.{MINOR} builders, we would simply get the latest pullspec associated with that floating tag, which could lead to unexpected behavior.
This PR changes the way we rebase upstream desired builders: for a given CI pullspec, we determine the builder X.Y and the RHEL version, and look for a matching entry in `streams.yml`. For example:
- `rhel-8-golang-1.21-openshift-4.15` for a 4.16 image would match the …

Match upstream builders by finding a suitable entry in streams.yml

---

doozer/doozerlib/constants.py
doozer/doozerlib/k_distgit.py
doozer/doozerlib/repos.py

Needed to access ocp-artifacts with `sslverify`. Setting `sslcacert` in `.repo` files ([docs](https://dnf.readthedocs.io/en/latest/conf_ref.html)).
Brew does this under the hood with `ADD tls-ca-bundle.pem /tmp/tls-ca-bundle.pem`. Example log [here](https://download-01.beak-001.prod.iad2.dc.redhat.com/brewroot/packages/ose-installer-container/v4.16.0/202405281506.p0.gd61ee0a.assembly.stream.el9/data/logs/x86_64.log)

set custom cert for konflux

---

doozer/doozerlib/k_distgit.py
doozer/doozerlib/repos.py

- In some images, `/etc/yum.repos.d/` exists, but it is empty
- `sslcacert` only for ocp-artifacts

[konflux] fix Dockerfile step, sslcacert only for ocp-artifacts

---

doozer/doozerlib/constants.py
doozer/doozerlib/distgit.py
doozer/doozerlib/k_distgit.py

- Use `super()` for better overrides, with less code duplication.
- Use brew registry for konflux for now

Optimize overrides, use brew registry for Konflux

---

doozer/doozerlib/distgit.py

This proposes that we only look at `cachito.enabled` config as the source of truth,
first in the meta config, then in the global config. And ignore the pkg_managers 
config if the global config is disabled.
Should go with config changes, https://github.com/openshift-eng/ocp-build-data/pull/4900

Respect cachito global config

---

pyartcd/pyartcd/pipelines/update_golang.py

Should go with https://github.com/openshift-eng/aos-cd-jobs/pull/4164
Several improvements for update-golang script
- Detect if running in jenkins env - don't try to do jenkins operations if not
- Add `--confirm` for confirming rebase and build, this is so when we run locally we don't accidently build. Jobs should have it enabled by default https://github.com/openshift-eng/aos-cd-jobs/pull/4164 
- Check streams.yml after building missing builders and notify of updates.
- Update jira ticket instructions to be precise and only apply for rhel8
- Remove ticket instructions for non-module builds and instead print out tagging instructions
- Add check if module build is directly tagged in override tag and untag instructions
Test:
```
./artcd -v --config config.example.toml update-golang …
```

Update golang script tweaks

---

artcommon/artcommonlib/release_util.py
artcommon/tests/test_util.py
pyartcd/pyartcd/pipelines/build_sync.py
pyartcd/pyartcd/pipelines/check_bugs.py
pyartcd/pyartcd/util.py

Currently, we need to move the release state to `release` in order to start signing artifacts. This is the side effects of triggering bugs checks for a release, that might not be GA yet.
The proposal is to add a new `signing` state, so that we can start signing artifacts, while still preventing bugs checks for that release.
This PR suggests a more structured approach to release states, so that we can compare values and assert, for example, that `'release' > 'pre-release'` and the like.

ART-9793 Handle the new 'signing' phase

---

pyartcd/pyartcd/pipelines/scan_fips.py

ART is getting too many pings for this ([example](https://redhat-internal.slack.com/archives/GDBRP5YJH/p1716775222592649))

Do not set art-attention icon on FIPS failure messages

---

elliott/elliottlib/cli/verify_attached_bugs_cli.py
elliott/elliottlib/runtime.py
elliott/tests/test_verify_attached_bugs_cli.py
pyartcd/pyartcd/pipelines/check_bugs.py

Make sure next version is GA for doing regression checks
Relies on `software_lifecycle`  config in group.yml
Test: elliott --assembly 4.15.12 -g openshift-4.15 verify-attached-bugs

Regression alerts only if next version is GA

---

pyartcd/pyartcd/pipelines/scan_fips.py

Exit with `1` even for dry-run

[fips-scan] Refactor exit

---

art-cluster/pipelines/data/project/art-cd/image/Containerfile.base

Since `requests` was installed by an RPM, it wasn't letting `pip install` upgrade it to the newer version

[art cluster] Fix Dockerfile install error

---

doozer/doozerlib/image.py

Reverts openshift-eng/art-tools#686
This removes a field from existing configuration, and thus triggers rebuilds. Mass rebuilds in 4.16 and 4.17 are unwanted at the moment, hence the revert.

Revert "Ignore okd config changes for triggering production builds"

---

pyartcd/pyartcd/pipelines/promote.py

https://github.com/openshift/enhancements/pull/1633 is proposing the use of ClusterImagePolicy/ImagePolicy in order to verify sigstore signatures on a release payload. This is replacing direct CVO based verification of simple signing (based on GPG and filestores).
We want testing by the release controller to exercise validation of the sigstore based signature, so it is necessary to sign the release payload before adding it to the release controller.

Sigstore sign release payloads prior to adding to the release controller

---

doozer/doozerlib/olm/bundle.py

Follow up to https://github.com/openshift-eng/art-tools/pull/608
When trying to match labels, we missed the case when a label would be present in 
found image that we do not want or want it to be false. To get around this always set prerelease label to 
whatever state it is in (true/false)

Set prerelease label in bundle build always

---

doozer/doozerlib/olm/bundle.py

This reverts https://github.com/openshift-eng/art-tools/pull/690.
The problem is ET marks a build as prerelease even if the label is set to "false".
So only set label to "true" when applicable, and then check it is not set when 
operator_index_mode is different

Check prerelease label explicitly

---

pyartcd/pyartcd/s3.py

promote can fail while reading the json that artcd produces. The json includes logs from aws s3 interactions. This ensures that stdout of the aws gets redirected to stderr.

promote: Fix invalid json

---

elliott/elliottlib/cli/find_bugs_golang_cli.py
elliott/elliottlib/cli/get_golang_report_cli.py

The goal of this PR is to report and exit early if a fix isn't found for a CVE flaw bug, 
when running "find-bugs:golang --analyze". 
This is done by using something we developed for use in `elliott go:report`. A compilation
of what's in streams.yml and in buildroots.
```
[{'go_version': '1.20.12', 'building_image_count': 227, 'building_rpm_count': 5}, 
{'go_version': '1.19.13', 'building_image_count': 1}]
```
Specifically in case like
- CVE-XYZ has fixed_in_versions as 1.22.3, 1.21.5
- openshift-4.15 is on 1.20 and does not use 1.22/1.21
- So we know that CVE-XYZ fix is not fixed for 4.15 since fixed_in_versions and versions in streams/buildroot are incompatible.
- This is unless a `--fixed-in-nvr` is passed to the command which is useful in case a special 1.20 nvr exists which contains …

find-bugs golang: Check if fixed-in-version is compatible with what's in-use

---

doozer/requirements.txt
elliott/pyproject.toml
pyartcd/requirements.txt

8.4.0 is broken:
```
File "/mnt/jenkins-workspace/aos-cd-builds_build_ocp4_scan/art-venv/lib64/python3.9/site-packages/tenacity/__init__.py", line 653, in <module>
from tenacity.asyncio import AsyncRetrying  # noqa:E402,I100
ModuleNotFoundError: No module named 'tenacity.asyncio'
```

Pin tenacity 8.3

---

pyartcd/pyartcd/oc.py
pyartcd/pyartcd/pipelines/promote.py

Currently the `openshift-install-rhel9-amd64.tar.gz` archive contains the file `artcd_working/to_mirror/openshift-v4/x86_64/clients/ocp/4.16.0-rc.4/openshift-baremetal-install`. Change this to the desired value, which is `openshift-install-fips`.

ART-9934: Clean up FIPS installer archive paths

---

elliott/elliottlib/cli/find_builds_cli.py
elliott/elliottlib/errata.py
pyartcd/pyartcd/pipelines/prepare_release.py

https://issues.redhat.com/browse/ART-8684
Introduce `--clean` and `--dry-run` flags to `elliott find-builds`
`--clean` removes all builds in advisory that were not found as part of build sweep.
```
$ elliott -g openshift-4.16 --assembly rc.4 find-builds -k image --non-payload 
--use-default-advisory extras --clean --dry-run
...
Default advisory detected: 125774
Found 48 builds, of which 11 are new.
2024-06-13 11:20:47,741 INFO 11 builds are already attached to given advisory
2024-06-13 11:20:47,741 INFO Fetching advisory
No eligible builds found. To include shipped builds, use --include-shipped
2024-06-13 11:20:53,543 INFO Removing builds from advisory that were not found in build sweep: 6
openshift-enterprise-egress-router-container-v4.16.0-202405041048.p0.ga26ca1f.assembly.stream.el8 …
```

ART-8684 Automatically remove invalid builds

---

elliott/elliottlib/bzutil.py
elliott/elliottlib/cli/verify_attached_bugs_cli.py
elliott/elliottlib/errata.py
pyartcd/pyartcd/pipelines/prepare_release.py

Right now verify-attached-bugs considers advance advisory if there are bugs
attached to it, but that is not always true and it is not correct logic. So correct that
Test:
`elliott --assembly rc.4 -g openshift-4.16 verify-attached-bugs --verify-bug-status --skip-multiple-advisories-check`

Tweak verify bugs for advance advisory

---

elliott/elliottlib/cli/verify_attached_bugs_cli.py
elliott/elliottlib/errata.py
elliott/tests/test_verify_attached_bugs_cli.py

Using Erratum(..) from errata_tool to initialize advisory is very slow and error prone for big GA advisories, 
It makes an http call for each build attached to the advisory (and more things) which 
we do not need and we hit timeout error in ET often which crashes us.
So instead use raw erratum api to fetch bugs for these advisories
`./elliott --assembly rc.4 -g openshift-4.16 verify-attached-bugs --verify-bug-status --skip-multiple-advisories-check
`

verify-attached-bugs: Use raw advisory fetch to be fast and less error prone

---

pyartcd/pyartcd/pipelines/promote.py

Ref [ART-6673](https://issues.redhat.com/browse/ART-6673), talked with QE to create a pr to QE [release-tests repo](https://github.com/openshift/release-tests), commit the release info in their repo. QE then will know the release is ready for test
the created pr looks like https://github.com/openshift/release-tests/pull/188

ART-6673 notify QE release ready through update QE release repo

---

elliott/elliottlib/cli/create_cli.py
elliott/elliottlib/errata_async.py
elliott/tests/test_errata_async.py
pyartcd/pyartcd/pipelines/prepare_release.py

Due to an issue in Errata Tool, if batch is enabled for an ET Release,
newly created advisories will be implicitly added to an open batch.
This has caused chaos because our ET release (RHOSE ASYNC - AUTO) is
shared among multiple teams (ART, CPaaS, etc) and advisories for
different OCP releases are prepared in parallel.
I would like to propose a new CLI option `--batch-id` for the `elliott
create` command, so that we can explicitly specify the batch ID when
creating an advisory. To achieve this, raw Errata REST API is used since
the errata_tool library doesn't expose that field.
Also updated prepare_release job to use the new CLI option.

prepare-release: Explicitly add newly created advisory to batch

---

pyartcd/pyartcd/pipelines/promote.py

Since `--` is present in the command, the option has to be before that
Error
```error: "--import-mode=PreserveOriginal" must be of the form <stream_name>:<tag>
2024-06-20 20:03:30,340 pyartcd:ERROR Error promoting release images: Process ['oc', 'tag', '--', 'quay.io/openshift-release-dev/ocp-release:4.15.19-aarch64', 'ocp-arm64/release-arm64:4.15.19', '--import-mode=PreserveOriginal'] exited with code 1.
```

fix --import-mode=PreserveOriginal command

---

elliott/elliottlib/cli/create_cli.py

There is an issue in
https://github.com/openshift-eng/art-tools/pull/697, where `elliott create` command doesn't print newly created advisory ID to stdout. This breaks prepare-release job and causes 0 populated to releases.yml (e.g. https://github.com/openshift-eng/ocp-build-data/commit/52a2b2f8c5920cb734a30eb824862d657aa529f7)

Fix newly created advisory ID being set to 0

---

pyartcd/pyartcd/pipelines/promote.py

test job: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fpromote-assembly/167/console
in the job we have such log
```
2024-06-21 03:09:44,975 pyartcd:INFO Update QE's release tests repo...
2024-06-21 03:09:45,377 pyartcd:INFO Updating QE release repo
2024-06-21 03:09:45,979 pyartcd:INFO Created fork branch ref refs/heads/4.15.19
2024-06-21 03:09:48,737 pyartcd:INFO PR https://github.com/openshift/release-tests/pull/199 merged info qe repo
2024-06-21 03:09:50,400 pyartcd:INFO Closed subtask ART-9970
```
its updated QE's repo by https://github.com/openshift/release-tests/pull/199

fix yaml load function

---

pyartcd/pyartcd/constants.py
pyartcd/pyartcd/pipelines/rebuild.py
pyartcd/pyartcd/plashets.py
pyartcd/tests/pipelines/test_rebuild.py

`ocp-artifacts` is being migrated to a new place. To make this transition smoother, the plan is to:
- start producing plashets on both (old and new one) hosts
- let the world know we're migrating
- after a reasonable time, give a final notice and decommission the old host
This PR tackles the first point. This [ocp4 build](https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4/3575/console) rebuilt 4.7 plashets, after having wiped them out manually on current ocp-artifacts VM. The result is  visible on both indexes:
- https://ocp-artifacts.hosts.prod.psi.rdu2.redhat.com/pub/RHOCP/plashets/4.7/
- https://ocp-artifacts-art--runtime-int.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/pub/RHOCP/plashets/4.7/

ART-9503 Handle multiple plashet host locations

---

pyartcd/pyartcd/pipelines/rebuild_golang_rpms.py
pyartcd/tests/test_rebuild_golang_rpms.py

tested locally with 
`artcd -v --working-dir=$HOME/tmp/art-tools --config=$HOME/Development/git/OpenShift/aos-cd-jobs/config/artcd.toml --dry-run rebuild-golang-rpms --ocp-version=4.17 --art-jira=[ART-9118](https://issues.redhat.com//browse/ART-9118) golang-1.22.2-1.module+el8.10.0+21789+dd446cb3`
and get
```
2024-06-14 12:42:27,488 pyartcd.pipelines.rebuild_golang_rpms:INFO cri-o/rhaos-4.17-rhel-8 - Current release in specfile: 2.rhaos4.17.git%{shortcommit0}
2024-06-14 12:42:27,590 pyartcd.pipelines.rebuild_golang_rpms:INFO cri-o/rhaos-4.17-rhel-8 - New release in specfile: 3.rhaos4.17.git%{shortcommit0}
```
have still to look if this works also for other RPMs since they could have different release field.

Fix release bumps for non ART RPMs

---

doozer/doozerlib/assembly_inspector.py
doozer/tests/test_assembly_inspector.py

early-kernel-ship-ok tag is not required to check now

ART-9555 deprecate kernel ship-ok tag check for assembly

---

artcommon/artcommonlib/logutil.py
doozer/doozerlib/runtime.py
doozer/tests/test_runtime.py
elliott/elliottlib/runtime.py

This PR improves log handling logic in following items:
- New helper function `setup_logging` is added to `artcommonlib` to set up logging for doozer and elliott in a common way.
- Logging level provided by command line and formatter strings are configured to the root logger, so that they are proprogated to child loggers obtained through `logging.getLogger`.
- No need to pass `runtime.logger` everywhere to log with configured options.  `logging.getLogger(__name__)` is able to obtain a logger from a different module without coupling Runtime.
- RedactingFilter is added to remove sensitive information like passwords, tokens, and keys from logs.

Improve log handling

---

doozer/doozerlib/cli/images_streams.py
doozer/doozerlib/distgit.py
doozer/doozerlib/util.py

Alongside https://github.com/openshift-eng/ocp-build-data/pull/5002
Upstream Dockerfiles are sometimes incorrectly named as `.rhel7` or `.rhel8` when their actual contents are rhel9. Added a new `dockerfile_fallback` field in ocp-build-data, so that we can raise upstream PRs without the need for coordinating the PR merge with ocp-build-data
- Refactor the logic to find the dockerfile name to `resolve_dockerfile_name` in doozer `utils.py`
- Use that function in rebase and upstream pr logic so that we consistently give back the same name

[ART-9923] support dockerfile_fallback field

---

elliott/elliottlib/runtime.py

Follow up to https://github.com/openshift-eng/art-tools/pull/725
Without a valid debug.log path, we log debug messages to console.
So init this as how we do it for doozer.

Init elliott debug.log

---

pyartcd/pyartcd/signatory.py

sign-container-identity for https://issues.redhat.com/browse/ART-10052 . This simplifies trusting an image when the repo matches the signed identity.

Add identity when using cosign

---

art-cluster/pipelines/config/argocd/project/art-cd/common/secrets/exd-ocp-buildvm-bot-prod-keytab.yaml
art-cluster/pipelines/config/argocd/project/art-cd/fips-scanning/pipeline-task.yaml

- Updating keytab to be pulled from AWS
- Setting `--dry-run` until we turn the scans back on

[fips-scan] rotate keytab

---

doozer/doozerlib/cli/config_plashet.py

IMA signing currently can take very long. The slowness is addressed through SIGNSERVER-267. Until that is deployed and fixed, waiting is the better option. Bumping timeout to 5 hours.
About IMA:
- this was enabled globally for rhel9 in [RHELPLAN-93951](https://issues.redhat.com//browse/RHELPLAN-93951)
- it was requested (but not followed through on) with [RHELWF-9941](https://issues.redhat.com//browse/RHELWF-9941)
- to see if an rpm was ima signed, compare:
```sh
rpm -q --queryformat "[%-10{FILENAMES} %{FILESIGNATURES} \n]" -p https://rhsm-pulp.corp.redhat.com/content/eus/rhel9/9.2/x86_64/baseos/os/Packages/b/bash-5.1.8-4.el9.x86_64.rpm
rpm -q --queryformat "[%-10{FILENAMES} %{FILESIGNATURES} \n]" -p https://rhsm-pulp.corp.redhat.com/content/dist/layered/rhel9/x86_64/rhocp/4.13/os/Packages …
```

Bump signing timeout radically

---

elliott/elliottlib/cli/verify_attached_bugs_cli.py
elliott/tests/test_verify_attached_bugs_cli.py

Wrap validate methods in try-except and have exceptions go to the report at the end.
This is so that even if we break, we always report on previously completed validations.
Move reporting to `report()` in BugValidator class
Test:
`./elliott -g openshift-4.16 --assembly stream verify-bugs --output slack`

verify-bugs: Report consistently

---

elliott/elliottlib/cli/find_bugs_sweep_cli.py
pyartcd/pyartcd/pipelines/prepare_release.py
pyartcd/pyartcd/pipelines/promote.py

We try to move microshift advisory to QE in prep and promote,
at which time it doesn't have any builds and always fails,
which leads to noisy logs and complains. So skip that.

Do not attempt to move microshift advisory to QE

---

elliott/elliottlib/cli/find_bugs_golang_cli.py
pyartcd/pyartcd/pipelines/ocp4.py

This will allow golang tracker bugs to be moved regularly as appropriate, 
as part of ocp4. This will help us to not miss updating trackers after bulds are present after bump.
The command find-bugs:golang is smart and will only move 
bugs it verifies are fixed, so running it multiple times redundantly is not a risk.

Run golang bug sweep as part of ocp4

---

doozer/doozerlib/cli/images_streams.py
doozer/doozerlib/distgit.py
doozer/doozerlib/metadata.py
doozer/doozerlib/util.py

Right now images:streams prs open breaks because of this.
We don't need the absolute path of Dockerfile but just the filename, 
so we do not need to pass in source_path.

Fix resolve dockerfile name

---

doozer/doozerlib/cli/scan_osh.py

Since we started added `.el8` at the end, test build NVRs look like `assembly.test.el*`. Updating logic so that its excluded correctly.

[sast pipeline] update test build filtering logic

---

doozer/doozerlib/metadata.py

Follows https://github.com/openshift-eng/art-tools/pull/772, where we accidentally included a regression to the fallback logic. We need to fallback when the file does not exist, not the field itself.

Fix fallback logic

---

doozer/doozerlib/cli/images_streams.py
doozer/doozerlib/distgit.py
doozer/doozerlib/metadata.py

Rollsback https://github.com/openshift-eng/art-tools/pull/718 and https://github.com/openshift-eng/art-tools/pull/778
Alongside https://github.com/openshift-eng/ocp-build-data/pull/5104

rollback fallback

---

doozer/doozerlib/metadata.py
elliott/elliottlib/metadata.py

There are couple of bugs in our get_latest_build code which results in things like 
```
./doozer --assembly=stream --working-dir ../../ --group openshift-4.16 
--images=ci-openshift-golang-builder-latest.rhel9 
--rpms=openshift config:scan-sources
2024-07-16 13:35:03,475 doozerlib    WARNING [rpms/openshift] No builds found using pattern 
openshift-4.16.*.assembly.stream.elrhaos-4.16-rhel-8-candidate*
2024-07-16 13:35:05,421 doozerlib    WARNING [rpms/openshift] No builds found using pattern 
openshift-4.16.*.g*aba1e8d*.assembly.stream.elrhaos-4.16-rhel-8-candidate*
2024-07-16 13:35:05,826 doozerlib    WARNING [rpms/openshift] No builds found using pattern 
openshift-4.16.*.assembly.stream.elrhaos-4.16-rhel-9-candidate*
2024-07-16 13:35:07,794 doozerlib    WARNING [rpms/openshift] No …
```

Fix get_latest_build patterns 

---

doozer/doozerlib/comment_on_pr.py
doozer/tests/test_comment_on_pr.py

When one github repository builds more than one image, allow every build to post a comment on pr. Fix misleading comments
An example on how the notifier looks like can be found [here](https://github.com/lgarciaaco/ovn-kubernetes/pull/9)

Allow multiple comments on pr

---

pyartcd/pyartcd/s3.py

Commands were expected to be passed as `[]`

fix promote cloudflare command

---

elliott/elliottlib/cli/create_cli.py
elliott/elliottlib/errata_async.py
pyartcd/pyartcd/pipelines/prepare_release.py

This is to resolve the issue of advisory publish date field being set and stuck in the past,
when we update the associated batch publish date to something else. In such a case errata-tool library 
cannot perform operations on it
```
ElliottFatalError("Error finding or attaching bugs: [ErrataException('Erratum 136272: publish_date_override: cannot be
set before 2024-Jul-24 which is determined by batch date of the advisory or ship_date of release\\n')]. See logs for 
more information.")
```
[slack_ref](https://redhat-internal.slack.com/archives/C06625LHXQS/p1721412549172059?thread_ts=1721411461.605679&cid=C06625LHXQS)

Don't set publish date if batch is provided

---

art-cluster/pipelines/config/argocd/project/art-cd/fips-scanning/pipeline-task.yaml

Fixes error
`pkg_resources.DistributionNotFound: The 'setuptools>=70.0.0' distribution was not found and is required by pyartcd
`

[fips scan] bump setuptools

---

pyartcd/pyartcd/pipelines/promote.py

after https://issues.redhat.com/browse/ART-9441 complete, the operator-framework has been added into payload in 4.16+, using similar logic to extract binaries from it in promote job

ART-9443 update extract_opm to support multi rhel binaries

---

elliott/elliottlib/cli/change_state_cli.py
pyartcd/pyartcd/pipelines/build_microshift.py
pyartcd/pyartcd/pipelines/prepare_release.py
pyartcd/pyartcd/pipelines/promote.py
pyartcd/tests/pipelines/test_promote.py

We try and move advisories to QE and alert in slack if we fail. But 
sometimes we run prep/promote jobs when advisories in REL_PREP, or 
even SHIPPED_LIVE to do something else. In those cases we don't want to 
error and be alerted when we cannot move advisory from those advanced
states to QE. So introduce a `--from` flag in elliott change-state which indicates 
that we should not operate if advisory is not in that state. Then we use 
`--from NEW_FILES` in our promote and prep pipelines.

Only alert when advisory cannot move from new_files to qe

---

doozer/doozerlib/metadata.py
doozer/tests/test_metadata.py
elliott/elliottlib/metadata.py
elliott/tests/test_metadata.py

This fixes the issue of not properly finding builds for ci golang builder images (because they share brew package for el8 and el9 builds happening in parallel). It was happening because we were only fetching latest build (for any el version), since https://github.com/openshift-eng/art-tools/pull/402  and then filtering out builds that did not match `branch_el_target` later, which resulted in no builds.
This would result in both images (el8 and el9) fetching builds by the same pattern (not including el version) and 
one would randomly get it's latest and other one would not.
Now since all our nvrs include ".el" suffix in them (it's been a while since we introduced them), use it by default. 
Before:
```
./doozer --assembly=stream --working-dir ../../ --group openshift-4.16 \ …
```

scan-sources: Always search images by el_target

---

pyartcd/pyartcd/pipelines/promote.py
pyartcd/pyartcd/util.py

Since /latest is a symlink, cloudfront does not instantly update when we update the clients. Need to manually invalidate

invalidate cloudfront cache during promote

---

doozer/doozerlib/source_resolver.py
pyartcd/pyartcd/pipelines/update_golang.py

- Use `yaml.load` since its from the `YAML` package
- Set default value for `has_public_upstream` (follow up from https://github.com/openshift-eng/art-tools/pull/756)

[golang builder] rename yaml safe_load to load

---

doozer/doozerlib/distgit.py
doozer/doozerlib/image.py
doozer/doozerlib/metadata.py
doozer/doozerlib/rpmcfg.py
doozer/tests/test_distgit/test_image_distgit/test_image_distgit.py

In function `_mapped_image_from_member`, the embargo state (private_fix flag) is set to its parent member's state. This is wrong.
The assumption is that when one of the parent images has an embargo, the child image is considered embargoed as well.
Also moving private_fix and image_build_method fields from ImageDistGitRepo class to Metadata.

Fix a bug in image embargo detection

---

art-cluster/pipelines/config/argocd/project/art-cd/fips-scanning/pipeline-task.yaml
art-cluster/pipelines/config/argocd/project/art-cd/fips-scanning/pipeline.yaml
artcommon/artcommonlib/constants.py
doozer/doozerlib/cli/scan_fips.py
pyartcd/pyartcd/pipelines/ocp4.py
pyartcd/pyartcd/pipelines/scan_fips.py

- Add the `--all-images` flag to the doozer `images:scan-fips` command
- Update artcd to to run for all active ocp4 versions
- Remove trigger from ocp4
Follow up PR will be raised after this has been deployed on cluster, to setup the scheduled job, which in turn will trigger the pipeline. Right now, these changes are only add the "scan all latest images" part and remove the code from ocp4 which calls the pipeline after every successful run.

[fips scan] [ART-10376] periodically scan all latest builds

---

ocp-build-data-validator/validator/schema/image_schema.py
ocp-build-data-validator/validator/schema/releases_schema.py

Tweak to print offending json path with message
```
Validating 1 file(s)...
Schema mismatch: ../../ocp-build-data/releases.yml
Returned error: $.releases.4.15.26.assembly.members.images[4]: 'why' is a required property
$.releases.4.15.26.assembly.members.images[5]: 'why' is a required property
$.releases.4.15.26.assembly.permits[0]: Additional properties are not allowed ('why' was unexpected)
```

ocp-build-data-validator: Print json path with message

---

doozer/doozerlib/cli/release_gen_assembly.py

Inherit advisories and jira ticket if they exist for a standard assembly

[ART-10250] Reuse advisories and jira for assembly

---

doozer/doozerlib/cli/release_gen_payload.py
doozer/tests/cli/test_gen_payload.py

Multi nightlies on release controller aren't preserving the original manifest list, just the x86 component.

Add importPolicy PreserveOriginal for image tags

---

doozer/doozerlib/image.py

Exclude delivery from image digest calculation.
This is required by https://github.com/openshift-eng/ocp-build-data/pull/5235 to prevent mass rebuilds.

Exclude delivery from digest calculation

---

ocp-build-data-validator/validator/json_schemas/image_config.base.schema.json

Adds delivery property to image config schema used by ocp-build-data-validator.

Add delivery to validator image config schema

---

doozer/doozerlib/cli/scan_fips.py

To error out if neither `--nvrs` nor `--all-images` is specified

[fips-scan] error out if no flag set

---

art-cluster/pipelines/data/project/art-cd/image/Containerfile.base

Latest version of `setuptools` has issue `TypeError: canonicalize_version() got an unexpected keyword argument 'strip_trailing_zero'`. Pinning to older version for now

[fips-scan] pin setuptools to fix ./install.sh error

---

doozer/doozerlib/cli/scan_sources.py

We keep getting random failures in ocp4_scan, due to calling async func `does_image_need_change` from sync code. Trying to fix it once again

Fix RuntimeError: await wasn't used with future

---

artcommon/artcommonlib/build_util.py
doozer/doozerlib/distgit.py
doozer/doozerlib/image.py
doozer/tests/test_distgit/support.py
doozer/tests/test_distgit/test_generic_distgit.py
doozer/tests/test_distgit/test_image_distgit/test_image_distgit.py
doozer/tests/test_distgit/test_image_distgit/test_push_image.py
doozer/tests/test_distgit/test_resolve_image_from_upstream_parent.py
doozer/tests/test_metadata.py

This PR intends to move some fields that are useful for both Distgit-Brew build and Konflux build, so that the rebase status can be shared regardless of the rebase method.

[ART-10504] Doozer: Move some fields from ImageDistGitRepo to ImageMetadata

---

pyartcd/pyartcd/pipelines/build_rhcos.py

Currently set to 4 hours. Seeing many failed `build/rhcos` jobs because 
```
Waited too long for builds to complete
```
(e.g. [here](https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Frhcos/6261/console))

Set the RHCOS build timeout to 6 hours

---

ocp-build-data-validator/validator/json_schemas/assembly_group_config.schema.json
pyartcd/pyartcd/pipelines/promote.py
pyartcd/tests/pipelines/test_promote.py

Enable `oc adm release new --next [...]`
We do not in our normal process require populating a payload's "next" edges.
In normal flow, each release's "next" edges are the following release's "previous" edges
But in case we miss adding an edge in "previous" list, we can add it in a "next" list
Example: 4.13.a and 4.14.b are shipping together in a week. 4.14.b has 4.13.a in its "previous" list.
Due to new requirements we re-promote 4.13 which becomes 4.13.(a+1) 
4.14.b does not have 4.13.(a+1) in its "previous" list. 
So we need to add 4.14.b in 4.13.(a+1)'s "next" list, 
to make that upgrade path available to customers who will be on 4.13.(a+1),
without repromoting 4.14.
See: https://github.com/openshift-eng/ocp-build-data/pull/5260 …

Enable promote with upgrades_next edges

---

doozer/doozerlib/cli/scan_fips.py
pyartcd/pyartcd/pipelines/scan_fips.py

After podman image prune command runs, it dumps out the SHAs of the images that it actually pruned, this was being returned to the parent arcd command and `json` started to complain since it wasn't in an actual json format. Moving to artcd will fix it.

[fips-scan] refactor clean images to artcd

---

elliott/elliottlib/bzutil.py
elliott/tests/test_bzutil.py

ref [ART-9920](https://issues.redhat.com/browse/ART-9920)
Prodsec will start creating new format of CVE bug with type `Vulnerability`, and `Vulnerability` type of bug has some useful customfield that we can use to simplify our check
the example bug has these fields is [OCPBUGS-36952](https://issues.redhat.com/browse/OCPBUGS-36952)
* customfield_12324749 --> `CVE ID` field, we can use this field to get cve id, no need to do string match
* customfield_12324751 --> `Upstream Affected Component` field, we can use this field to get pscomponent
* customfield_12324750 --> `Embargo Status` field, we can use this field as flag to check embargo status

[ART-9920] add new cve type field

---

doozer/doozerlib/cli/images_health.py

Add a retry to supersede errors like
```
mysql.connector.errors.OperationalError: 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 104
<<
```
as seen [here](https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/scanning/job/scanning%252Fimages-health/1073/console)

images-health: retry on DB connection error

---

elliott/elliottlib/errata.py

To retry when errors like [this](https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4/7343/consoleFull) arise:
```
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='errata.devel.redhat.com', port=443): Max retries exceeded with url: /api/v1/erratum/135492/builds (Caused by ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')))
```

Retry when fetching builds from Errata

---

pyartcd/pyartcd/pipelines/build_rhcos.py

Deprecated Retry options Retry.DEFAULT_METHOD_WHITELIST, Retry.DEFAULT_REDIRECT_HEADERS_BLACKLIST and Retry(method_whitelist=...) in favor of Retry.DEFAULT_ALLOWED_METHODS, Retry.DEFAULT_REMOVE_HEADERS_ON_REDIRECT, and Retry(allowed_methods=...) (Pull #2000) Starting in urllib3 v2.0: Deprecated options will be removed
https://github.com/urllib3/urllib3/blob/main/CHANGES.rst#1260-2020-11-10

replace deprecated function

---

doozer/doozerlib/cli/release_gen_payload.py

Use `exectool.manifest_tool` to run `manifest-tool` command. `exectool.manifest_tool` handles auto-retries.

Retry on manifest-tool errors

---

doozer/doozerlib/repodata.py

To fix errors as seen in https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4_scan/69301/console:
```
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host rhsm-pulp.corp.redhat.com:443 ssl:default [Connect call failed ('10.2.66.234', 443)]
```

RepodataLoader: retry on ClientConnectionError

---

doozer/doozerlib/distgit.py
doozer/doozerlib/olm/bundle.py

We should not build operators with invalid metadata references. This causes 
a bunch of problems down the line, when they fail csv validation or other issues 
when installing the image where references were not found and replaced correctly.
This was recently seen in 4.17 where we built bundle nvr for operator nvr with invalid refs 
[ose-metallb-operator-bundle-container-v4.17.0.202407130042.p0.g3fe67bc.assembly.stream.el9-2](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=3181361) and it was 
understandably failing cvp test after it was attached advisory. We want to save time and effort by failing 
earlier and working to resolve this kind of issue earlier.
Rebasing metallb operator with the problematic commit
```
$ ./doozer -g openshift-4.17 --assembly test …
```

[operator and bundle builds] Complain if image references not found

---

doozer/doozerlib/cli/get_nightlies.py

quay registry sometimes is flaky.

Retry `oc image info` for gen-assembly

---

pyartcd/pyartcd/pipelines/build_rhcos.py

Reduce [occurrences](https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Frhcos/6911/console) of `Exception: Waited too long for builds to complete`

Increase RHCOS timeout to 8 hours

---

doozer/doozerlib/cli/release_gen_payload.py
doozer/tests/cli/test_gen_payload.py
pyartcd/pyartcd/pipelines/build_sync.py

Ref https://issues.redhat.com/browse/ART-8080
The goal of this PR is to setup a new flow so that we can create embargoed nightlies (visible in the private release controller), so that QE and other stakeholders can test the payload well in advance of the embargo being lifted. Currently, we only start building after the embargo is lifted, and we immediately pin the build(s) in the payload and promote. Having the private builds earlier in the private release controller will let us follow the usual pattern of release, but with public nightlies. The flow can be summarized as follow:
- For STREAM:
- Only public builds are synced to public image streams (thereby to public nightlies), but both public and private builds are synced to private nightlies. Since we rebase from openshift to …

[ART-9330] [ART-8971] new embargo process

---

artcommon/artcommonlib/git_helper.py
artcommon/tests/test_git_helper.py
doozer/doozerlib/backend/build_repo.py
doozer/doozerlib/backend/rebaser.py
doozer/doozerlib/cli/__main__.py
doozer/doozerlib/cli/images_konflux.py
doozer/doozerlib/constants.py
doozer/doozerlib/runtime.py
doozer/tests/backend/test_build_repo.py

This PR adds Konflux rebase feature to Doozer. To rebase with Konflux, run `doozer -g openshift-x.y beta:images:konflux:rebase`.  This PR also contains a lot of refactoring code. We have to get this well tested before merging it to main.
The major part of this feature is in doozerlib/backend/rebaser.py. Most of the code there is taken from distgit.py with refactor, aiming to have a backend-independent implementation for the rebase logic.
/hold
This PR requires 
https://github.com/openshift-eng/art-tools/pull/854
https://github.com/openshift-eng/art-tools/pull/853
https://github.com/openshift-eng/art-tools/pull/855
https://github.com/openshift-eng/art-tools/pull/856
https://github.com/openshift-eng/art-tools/pull/857
https://github.com/openshift-eng/art-tools/pull/858
Note: Note: Build …

[ART-10504] Doozer: Add command for rebasing images with Konflux

---

doozer/doozerlib/cli/images_streams.py

In the reconciliation PRs that we raise, we log which Jenkins run created the PR, for easy debugging (example [here](https://github.com/openshift/operator-framework-olm/pull/853#issuecomment-2328085547)). But we don't seem to do so for the tickets that we create along with the PR (https://issues.redhat.com//browse/OCPBUGS-39506). 
This PR is a quick fix so that we start to log which Jenkins job run created the ticket, in the ticket description, so that its easier to debug.
_(PR untested)_

log jenkins build url in reconciliation ticket

---

doozer/doozerlib/backend/rebaser.py

Fix for
```
metadata_scripts_path = self._runtime.data_dir.joinpath("modifications")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'joinpath'
```

images:rebase - Fix modifications script path

---

.github/workflows/unit-tests.yaml
Makefile
install.sh
tox.ini

Replace `pip` with `uv` in CI, as it's showing significant improvements in performance.
By default, `uv venv --python 3.11` creates a Python 3.11 virtual environment at `./.venv`. This also simplifies the `venv` rule in the Makefile, as `uv` commands require that a virtual env is activated, or that a local env exists at `.venv`
Looking at the CI jobs for this PR, the `Create venv and install dependencies` step took less than 2 minutes, while it takes around 4 with pip (see for example [here](https://github.com/openshift-eng/art-tools/actions/runs/10770743899/job/29864744957), [here](https://github.com/openshift-eng/art-tools/actions/runs/10745829285/job/29805637933) and [here](https://github.com/openshift-eng/art-tools/actions/runs/10744242388/job/29800728516))

ART-10668 Replace pip with uv

---

doozer/doozerlib/cli/images_streams.py

jira query can't correctly find already opened bug,
eg, for [OCPBUGS-39455](https://issues.redhat.com/browse/OCPBUGS-39455) and [OCPBUGS-41308](https://issues.redhat.com/browse/OCPBUGS-41308)
old query find nothing
https://issues.redhat.com/issues/?jql=project%20%3D%20%22OpenShift%20Bugs%22%20%20AND%20summary%20~%20%22ART%20requests%20updates%20to%204.18%20image%20ose-operator-framework-tools-container%22%20AND%20statusCategory%20in%20(%22To%20Do%22%2C%20%22In%20Progress%22)
while https://issues.redhat.com/browse/OCPBUGS-39455?jql=project%20%3D%20%22OpenShift%20Bugs%22%20%20AND%20issueFunction%20in%20linkedIssuesOfRemote(%22url%22%2C%20%22https%3A%2F%2Fgithub.com%2Fopenshift%2Foperator-framework-olm%2Fpull%2F850%22) can find the already opened one

fix aligment bug search

---

pyartcd/pyartcd/pipelines/gen_assembly.py
pyartcd/pyartcd/slack.py
pyartcd/tests/pipelines/test_gen_assembly.py

- Add an option to skip `get_nightlies` i.e. skip nightly consistency check if necessary
- Small fix for slack dry-run option
Needs rebase if https://github.com/openshift-eng/art-tools/pull/925 merges first

add option to skip get_nightlies

---

doozer/doozerlib/cli/get_nightlies.py
doozer/doozerlib/constants.py
pyartcd/pyartcd/pipelines/gen_assembly.py

This change will allow get_nightlies to auto pick the set of consistent nightlies from private release controller
Tests:
- works with private nightlies [correctly](https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fgen-assembly/197/)
- works with public nightlies [correctly](https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fgen-assembly/198/)
Needs rebase if https://github.com/openshift-eng/art-tools/pull/924 is merged first

gen-assembly read from private nightlies

---

doozer/doozerlib/cli/__init__.py

This PR allows Doozer to raise an error if a version string like `--version=vv4.18` is passed through the command line.

Doozer: Disallow extra 'v' in version string

---

doozer/doozerlib/backend/konflux_image_builder.py
doozer/doozerlib/backend/rebaser.py
doozer/doozerlib/cli/images_konflux.py
doozer/doozerlib/constants.py
doozer/doozerlib/image.py

Adds logic to build child images with Konflux. Note since DB integration hasn't been fully done, currently we have to build the parent image and the child image together.
Also changes the default image repo to
`quay.io/openshift-release-dev/ocp-v4.0-art-dev-test`, which can be customized using `--image-repo` parameter.

Konflux: Support building child images

---

doozer/doozerlib/cli/rpms.py

Storing RPM builds in BigQuery will let us move away from Brew API calls to decide whether an image needs to be rebuilt because of RPM changes.
[Test build](https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4/8819/console) stored `ose-aws-ecr-image-credential-provider-4.18.0-202409182058.p0.g876afc6.assembly.test.el8` and `ose-aws-ecr-image-credential-provider-4.18.0-202409182058.p0.g876afc6.assembly.test.el9` in BigQuery:
```
SELECT * 
FROM `openshift-art.events.builds`
WHERE start_time > TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 24 HOUR)
AND `artifact_type` = 'rpm'
ORDER BY start_time DESC;
```

ART-10831 Store successful RPM Brew builds in BigQuery

---

artcommon/artcommonlib/git_helper.py
artcommon/artcommonlib/konflux/konflux_db.py
artcommon/tests/test_git_helper.py
doozer/doozerlib/backend/build_repo.py
doozer/doozerlib/distgit.py
doozer/tests/backend/test_build_repo.py

Storing failed builds in BigQuery will enable us to migrate images-health away from Brew API.
[Test build](https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4/8851/console) stored:
```
SELECT * 
FROM `openshift-gce-devel.art_test.builds`
WHERE start_time > TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 24 HOUR)
AND `outcome` = 'failure'
```

ART-10831 Store failed Brew image builds in BigQuery

---

artcommon/artcommonlib/bigquery.py
artcommon/artcommonlib/konflux/konflux_build_record.py
artcommon/artcommonlib/konflux/konflux_db.py
artcommon/artcommonlib/runtime.py
artcommon/requirements.txt
artcommon/tests/test_big_query.py
artcommon/tests/test_konflux_db.py
elliott/elliottlib/cli/find_konflux_builds_cli.py

- create a separate abstraction layer to model BigQuery interactions in `bigquery.py`
- introduce `sqlalchemy` to let us easily construct higher level queries from Python objects
- define `get_latest_builds()`
- add unit tests for Konflux DB and BigQuery abstractions
- improve `elliott find-k-builds` stub
The `get_latest_builds()` implementation uses a scanning pattern that aims to limit as much as possible the amount of data that BigQuery needs to scan to satisfy our requests. The builds table has been partitioned by `start_time`, and the search function performs queries within 3-month wide time intervals of `start_time`. In the most frequent scenario, we would find a build for each component in the first window; for hotfix builds where we are dealing with old assembly definitions we …

Define konflux_db.get_latest_builds()

---

elliott/elliottlib/cli/find_bugs_golang_cli.py

https://issues.redhat.com/browse/ART-10516
Sometimes we find that bugzilla flaw bugs are missing fixed_in_version CVE metadata. In that case, and
other cases we want to query Go vulnerability database to double the field, and
use it to determine fixed bugs.
Example:
`CVE-2024-24791`
- https://bugzilla.redhat.com/show_bug.cgi?id=2295310 is missing "Fixed in version"  field value
- https://pkg.go.dev/search?q=CVE-2024-24791
- https://vuln.go.dev/ID/GO-2024-2963.json
```
$ ./elliott -g openshift-4.17 find-bugs:golang --analyze
2024-09-02 13:28:04,709 elliottlib.cli.find_bugs_golang_cli INFO Current golang versions being used in 4.17: 
[{'go_version': '1.22.5', 'building_image_count': 244, 'building_rpm_count': 5}, {'go_version': '1.21.11', 
'building_image_count': 2}]
2024-09-02 13:28:04,709 …
```

ART-10516 Fetch and validate fixed in versions from go vulnerability DB

---

doozer/doozerlib/distgit.py

Using `image_meta.name` is wrong, because we have multiple images with the same `name`, but different distgit key. For example, `ci-openshift-build-root-latest.rhel8` and `ci-openshift-build-root-latest.rhel9`. 
We can still distinguish builds for these components in BigQuery using the `el_target` column, but only among successful ones. Failed builds won't store the rhel target (as it's being deducted from the build NVR), so actors like `doozer images:health` treat failed builds for the rhel8/rhel9 images as belonging to the same item.
The distgit key is currently the right way to uniquely define an image component. We will eventually need to purge references to `distgit`, but that can be addressed when time comes.

Use the distgit key as primary image name when storing Konflux builds

---

doozer/doozerlib/backend/konflux_image_build_pipelinerun.yaml
doozer/doozerlib/backend/konflux_image_builder.py
doozer/doozerlib/backend/rebaser.py

- Skip checks by default for now (since its failing the pipeline runs)
- Fix issue with successful / failed builds
- Replace dots with dashes, since openshift doesn't support dots

[konflux] skip-checks by default, replaces dots with dashes

---

pyartcd/pyartcd/pipelines/promote.py
pyartcd/pyartcd/pipelines/sigstore_sign.py
pyartcd/pyartcd/signatory.py

Software Product has stood up a rekor instance for TLOG submission. They also have a new prod key that we are supposed to be using, so allow signing with multiple keys to enable graceful transitions between signing keys.

Allow multiple signing keys and rekor tlog for cosign

---

artcommon/artcommonlib/bigquery.py
artcommon/tests/test_big_query.py

- initialize `bigquery.Client` with `project=constants.GOOGLE_CLOUD_PROJECT` (required since we're not feeding in an env var for the project
- remove extra `'` from values in query strings (not needed since [value_or_null()](https://github.com/openshift-eng/art-tools/blob/main/artcommon/artcommonlib/konflux/konflux_db.py#L46) got in)
Test build: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4/9106/console

Fix BigQueryClient

---

doozer/doozerlib/cli/release_gen_payload.py
pyartcd/pyartcd/pipelines/build_sync.py

The CRT 'release-tool' will allow TRT to revert a specific tag in an 4.x-art-latest integration stream to a previous value. When they do this, the implication is that the image they are reverting has an serious issue.
The release-tool directly replaces the bad image with a replacement image specified by TRT.
When this is done, ART should not immediately update the reverted tag with the bad image. To achieve this, 'release-tool' will leave an annotation on the reverted tag specifying the image that was reverted.
When gen-payload finds this annotation, it should only update the tag with a new image IFF the new image does not match the old image identified in the 'reverted-from' annotation.

Add sticky revert functionality to gen-payload

---

doozer/doozerlib/backend/rebaser.py

We have a lot of stream parant images defined in streams.yml, where short image names are used, such as
`openshift/golang-builder:tag`.
In order to reference those images in Konflux, we need to prepend the Brew registry URL.

[Konflux] Fix resolving short images in streams.yml

---

doozer/doozerlib/backend/konflux_image_builder.py

In images.py we collect failed builds as follows:
```
failed = [r for r in results if isinstance(r, Exception)]
if failed:
raise DoozerFatalError(f"Failed to build images: {failed}")
```
during refactoring, we removed the child function from raising a error if it fails, adding that back in

[konflux] Fail builds fix

---

elliott/elliottlib/bzutil.py
elliott/tests/test_bzutil.py

```
Flaw bug 2268195 does not have a CVE alias. Is it a CVE bug? These trackers 
reference the bug: ['OCPBUGS-29804']. If it is not a valid flaw bug
please remove references from the tracker bugs.
```

Log more when there is an invalid flaw bug

---

doozer/doozerlib/backend/rebaser.py

The brew.registry url is the registry-proxy url, but with the domain replaced by the former and the repo is `rh-osbs`. Also the golang builder's pullspec is openshift-golang-builder

[konflux] replace golang stream with brew.registry

---

elliott/elliottlib/bzutil.py

In order to process bugs like OCPBUGS-39183, which have multiple target versions but we couldn't remove the incorrect target version with archived flag set to True.

elliott: Filter out archived target versions

---

elliott/elliottlib/cli/verify_attached_bugs_cli.py
elliott/tests/test_verify_attached_bugs_cli.py

Right now we check for invalid status after filtering bugs by desired target release.
Sometimes we want to get info about invalid bug status before invalid target release check.
Example, when we have invalid target release 4.17.z when the desired is 4.17.0, the bug might
still be valid to be attached. But not if it has invalid bug status.

verify-bugs: Check for invalid bug status first

---

pyartcd/pyartcd/pipelines/promote.py

When doing `oc adm release new` in parallel, connection to quay has a good chance of erroring out
Run without this PR (red): https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fpromote-assembly/362/console
Run with this PR (green): https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fpromote-assembly/365
```
stream error: stream ID 11; INTERNAL_ERROR; received from peer
```

Promote arches in sequence

---

artcommon/artcommonlib/bigquery.py
artcommon/artcommonlib/konflux/konflux_build_record.py
artcommon/artcommonlib/konflux/konflux_db.py
doozer/doozerlib/backend/konflux_image_builder.py
doozer/doozerlib/cli/images_konflux.py
doozer/doozerlib/constants.py
doozer/doozerlib/distgit.py
elliott/elliottlib/cli/find_konflux_builds_cli.py

Changes
- Start recording konflux build at trigger time and complete time
- Some log message updates, post UI link and pipelinerun "message"
- Also record some extra info that is available for failed brew builds, like nvr from rebase time
- In elliott find-k-builds, add flags to search by engine/outcome and output to json
Test:
```
$ ./doozer --assembly test -g openshift-4.18 -i openshift-base-rhel9 --latest-parent-version
beta:images:konflux:build --konflux-kubeconfig ~/konflux.kubeconfig.p02 --konflux-namespace ocp-art-tenant
...
2024-10-01 18:33:33,719 doozerlib.backend.konflux_image_builder INFO [openshift-base-rhel9] Created PipelineRun:
https://konflux.apps.stone-prod-p02.hjvn.p1.openshiftapps.com/application-pipeline/workspaces/ocp-art/applications/ …
```

Start recording konflux builds 

---

artcommon/artcommonlib/konflux/konflux_db.py
artcommon/artcommonlib/util.py
doozer/doozerlib/backend/konflux_image_builder.py
doozer/doozerlib/cli/images_health.py
doozer/doozerlib/cli/olm_bundle.py
doozer/doozerlib/cli/release_gen_payload.py
doozer/doozerlib/distgit.py
doozer/doozerlib/runtime.py
pyartcd/pyartcd/pipelines/prepare_release.py
pyartcd/pyartcd/pipelines/update_golang.py
pyartcd/pyartcd/util.py

Weird things happen when we don't lock datetime.now() to UTC and run from our own local systems.

Always lock to datetime.UTC

---

doozer/doozerlib/backend/konflux_image_builder.py
doozer/doozerlib/distgit.py

Use cosign command to download sbom and extract installed rpms
`cosign download sbom quay.io/openshift-release-dev/ocp-v4.0-art-dev-test:ose-ironic-agent-rhel9-v4.18.0-20241002.145940 --platform linux/amd64`
https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4-konflux/121/console
```
$ ./elliott --assembly test -g openshift-4.18 -i openshift-base-rhel9 find-k-builds -k image -e konflux --output json
2024-10-02 17:52:13,760 art_tools.elliottlib.cli.find_konflux_builds_cli INFO Found 1 builds
{
"name": "openshift-base-rhel9",
"group": "openshift-4.18",
"version": "v4.18.0",
"release": "202410022059.p0.gb45ea65.assembly.test.el9",
"assembly": "test",
"source_repo": "https://github.com/openshift-eng/ocp-build-data",
"commitish": …
```

Populate installed pkgs in konflux build

---

doozer/doozerlib/backend/rebaser.py
doozer/doozerlib/runtime.py
elliott/elliottlib/cli/find_konflux_builds_cli.py

We are recording metadata.distgit_key in our DB record, so search by that at rebase time
and in find-k-builds.
Test run: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4-konflux/132/console

Search by distgit_key instead of name

---

art-cluster/pipelines/config/argocd/project/art-cd/quay-doomsday-backup/base/doomsday-pipeline-task.yaml
art-cluster/pipelines/data/project/art-cd/image/Containerfile.base
art-cluster/pipelines/data/project/art-cd/image/Containerfile.latest
pyartcd/pyartcd/__main__.py
pyartcd/pyartcd/pipelines/doomsday.py
pyartcd/pyartcd/pipelines/quay_doomsday_backup.py

Migrate doomsday pipeline to Python and add retries to running `oc adm release mirror ...` and `aws s3 sync ...` commands

Migrate doomsday pipeline to python

---

artcommon/artcommonlib/konflux/konflux_db.py

`search_builds_by_fields()` only logs the number of builds found, without specifying more details. This function has been written to be as flexible as possible, so it's not possible to know what params were specified to make the search. This makes log messages like `artcommonlib.konflux.konflux_db INFO Found 1 builds` quite useless. 
Proposing to set the debug level to DEBUG, to make our pipeline logs more readable.

Decrease konflux_db.search_builds_by_fields() log level

---

pyartcd/pyartcd/pipelines/build_microshift.py
pyartcd/pyartcd/slack.py

fix error
```
UserWarning: Although the channels parameter is still supported for smooth migration from legacy files.upload, we recommend using the new channel parameter with a single str value instead for more clarity.
The filetype parameter is no longer supported. Please remove it from the arguments.
```
update channels parameter to channel
remove filetype parameter
file parameter should accept file path string
and file_upload_v2 will call files.completeUploadExternal which seems only accept channel_id so set channel with id instead of its name

update file_upload_v2 parameters

---

doozer/doozerlib/cli/scan_sources.py

scan-sources first checks for upstream changes (new commits that have not been built yet) and marks those images that need a fresh rebuild. 
Then, it looks for other reasons to rebuild (e.g. configuration changes, dependency reasons. etc.). These are time consuming at should be skipped completely if the image has already been tagged for rebuild.
I expect this change to reduce the execution time for scan-sources.

scan-sources: skip unnecessary checks

---

doozer/doozerlib/backend/konflux_image_builder.py

When executing builds in mass rebuild we're noticing big wait times, 
and threads getting throttled when child images wait for parent. This should help a little.

Sleep instead of wait

---

pyartcd/pyartcd/plashets.py

To enable bootc image builds, we need microshift rpm available at build time in a plashet
See https://github.com/openshift-eng/ocp-build-data/pull/5345/files
Test run: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4/8011/console
https://ocp-artifacts.hosts.prod.psi.rdu2.redhat.com/pub/RHOCP/plashets/4.18/microshift/microshift-el9/latest/

Add microshift plashet repo config

---

doozer/doozerlib/backend/konflux_image_build_pipelinerun.yaml
doozer/doozerlib/backend/konflux_image_builder.py

Based on existing pattern, move overrides to code so that we can use the [template](https://github.com/openshift-priv/art-konflux-template/blob/main/.tekton/art-konflux-template-push.yaml) from openshift-priv/art-konflux-template

[konflux] move overrides to code

---

artcommon/artcommonlib/konflux/konflux_db.py
artcommon/tests/test_konflux_db.py

Needed by scan sources to add select clauses like `AND commitish LIKE  '%b45ea65%'`

Add extra pattern search to get_latest_build in Konflux

---

artcommon/artcommonlib/konflux/konflux_db.py
artcommon/artcommonlib/util.py
doozer/doozerlib/backend/konflux_image_builder.py
doozer/doozerlib/cli/images_health.py
doozer/doozerlib/cli/olm_bundle.py
doozer/doozerlib/cli/release_gen_payload.py
doozer/doozerlib/distgit.py
doozer/doozerlib/runtime.py
pyartcd/pyartcd/pipelines/prepare_release.py
pyartcd/pyartcd/pipelines/update_golang.py
pyartcd/pyartcd/util.py

`datetime.UTC` is supported only for python 3.11+
art-cd images on art-cluster are still on 3.9 (installation issues with 3.11). So we need to make sure that code is backwards compatible.
suggesting to use [datetime.timezone.utc](https://docs.python.org/3/library/datetime.html#datetime.timezone.utc), since they are the [same](https://docs.python.org/3/library/datetime.html#datetime.UTC)

make utc python backwards compatible

---

art-cluster/pipelines/data/project/art-cd/image/Containerfile.base

artcd does not work with python3.11 on cluster right now 
```
asdas@asdas-thinkpadp1gen3:~$ artcd -h
File "/home/dev/.venv/bin/artcd", line 5, in <module>
from pyartcd.__main__ import main
File "/home/dev/pyartcd/pyartcd/__main__.py", line 4, in <module>
from pyartcd.pipelines import (
File "/home/dev/pyartcd/pyartcd/pipelines/rebuild_golang_rpms.py", line 8, in <module>
from specfile import Specfile
File "/home/dev/.venv/lib64/python3.11/site-packages/specfile/__init__.py", line 8, in <module>
from specfile.specfile import Specfile
File "/home/dev/.venv/lib64/python3.11/site-packages/specfile/specfile.py", line 12, in <module>
import rpm
File "/home/dev/.venv/lib64/python3.11/site-packages/rpm/__init__.py", line 109, in <module>
initialize()
File …
```

artcd image rollback to python3.9

---

doozer/doozerlib/cli/rpms.py
doozer/doozerlib/rpm_builder.py
pyartcd/pyartcd/pipelines/build_microshift.py
pyartcd/pyartcd/slack.py

https://issues.redhat.com/browse/ART-10563 is going to add image builds for microshift-bootc image for named 
assemblies
Before that, sanitize the pipeline to be cleaner. 
- Separate methods for stream and named assemblies
- Extract out try-catch-slack outside of the pipeline class
- Fix and enable dry_run across the stack
Test run:
- for stream type assembly: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fbuild-microshift/1207/console
- for named assembly: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fbuild-microshift/1208/console

ART-10563 Refactor build-microshift pipeline

---

doozer/doozerlib/cli/rpms.py

jenkins [job](https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4/10024/console)
```
File "/mnt/jenkins-workspace/aos-cd-builds_build_ocp4@3/art-tools/doozer/doozerlib/cli/rpms.py", line 303, in _build_rpm
await update_konflux_db(runtime, rpm, record)
File "/mnt/jenkins-workspace/aos-cd-builds_build_ocp4@3/art-tools/doozer/doozerlib/cli/rpms.py", line 374, in update_konflux_db
if not runtime.dry_run:
^^^^^^^^^^^^^^^
AttributeError: 'Runtime' object has no attribute 'dry_run'
```
Updating logic, since we are already checking dry_run outside the function

fix konflux_db dry_run

---

doozer/doozerlib/backend/konflux_image_builder.py

```
2024-10-10 21:11:04,742 doozerlib.backend.konflux_image_builder INFO Konflux build info stored successfully
```
Since builds are running async, we don't know which distgit components build got stored correctly. Hence proposing to prepend the distgit name

[konflux] DB log print distgit name

---

artcommon/artcommonlib/bigquery.py
artcommon/artcommonlib/konflux/konflux_db.py
artcommon/tests/test_big_query.py
artcommon/tests/test_konflux_db.py

- make `bigquery.select()` async, to allow concurrent queries to the DB
- make `konflux_db.get_latest_build()` async to boost scan-sources for Konflux performance
- fix a small bug in `konflux_db.get_latest_build()` that was messing up log messages (fortunately, not the behavior of the function itself)

Konflux: make get_latest_build async

---

doozer/doozerlib/cli/images_konflux.py

This is useful for troubleshooting.

Konflux: Log with stack trace on build error

---

doozer/doozerlib/cli/release_gen_payload.py
doozer/tests/cli/test_gen_payload.py

Multi nightlies are different than single arch nightlies. Each update causes the release controller to run CI jobs vs single arch imagestream updates, where the release controller prevents nightlies from being created too often.
Currently, nearly every run on gen_payload is going to create a new multi-nightly. Limit this rate.

Slow down multi nightly creation

---

doozer/doozerlib/backend/konflux_image_builder.py
doozer/doozerlib/constants.py

Currently, Konflux has very low capacity and we must ensure we do not allocate more pipelines than the cluster can handle. According to previous discussions, we should limit concurrent builds to 2 for now. Setting an explicit constant to let us bump this number easily once we get a green flag.

Limit number of concurrent Konflux pipelines

---

doozer/doozerlib/cli/__main__.py
doozer/doozerlib/cli/scan_sources_konflux.py

First step towards the implementation for scan-sources for Konflux. This PR addresses the first reason to rebuild an image, namely a missing build for the latest upstream commit. Tested from a hackspace: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/hack/job/dpaolell/job/ocp4_scan/35/console

ART-10999 scan-sources for Konflux: check for upstream changes

---

elliott/elliottlib/cli/find_bugs_golang_cli.py
pyartcd/pyartcd/pipelines/ocp4.py
pyartcd/pyartcd/pipelines/rebuild_golang_rpms.py
pyartcd/pyartcd/pipelines/update_golang.py
pyartcd/pyartcd/runtime.py
pyartcd/tests/test_rebuild_golang_rpms.py

Changes:
- Consider latest pending and failed nightlies when determining if golang builder container is fixed for an OCP version
- Support passing `--cves` in `update_golang` and `rebuild_golang_rpms` jobs. This is useful to operate on trackers of CVEs that got fixed downstream.
- Support passing `--force-update-tracker` and `--component` in `update_golang` job and `find-bugs:golang` command. This is useful to update tracker bugs manually

Golang bugs changes to sweep bugs earlier

---

pyartcd/pyartcd/pipelines/ocp4.py

rh-pre-commit.version: 2.3.1
rh-pre-commit.check-secrets: ENABLED
fixes: 2024-10-18 05:17:28,375 art_tools.artcommonlib.exectools INFO Executing:cmd_assert_async ['elliott', '_**--assembly', 'stream--group=openshift', '4.18',**_ 'find-bugs:golang', '--analyze', '--update-tracker']
Usage: elliott [OPTIONS] COMMAND [ARGS]...
Try 'elliott -h' for help.
in ocp4 builds

fix construction of elliott cmd

---

doozer/doozerlib/backend/rebaser.py

Update-csv should generate pullspec in the form of `image-registry.openshift-image-registry.svc:5000/openshift/<image-name-short>:<uuid-tag>`.

konflux: Fix wrong bundle CSV pullspec with uuid tag

---

doozer/doozerlib/backend/konflux_image_builder.py

Right now we display the build log as 
```
24-10-18 14:26:42,009 doozerlib.backend.konflux_image_builder INFO PipelineRun 4-18-ose-cli-artifacts-z82js status: Unknown Tasks Completed: 3 (Failed: 0, Cancelled 0), Incomplete: 11, Skipped: 0.
2024-10-18 14:26:42,234 doozerlib.backend.konflux_image_builder INFO PipelineRun 4-18-ose-cli-artifacts-z82js status: Unknown Tasks Completed: 3 (Failed: 0, Cancelled 0), Incomplete: 11, Skipped: 0.
```
To keep the logs clean, we can remove the task details from being displayed, since it doesn't provide any useful insight, and print just the pipeline status. So the new log will look like:
```
24-10-18 14:26:42,009 doozerlib.backend.konflux_image_builder INFO PipelineRun 4-18-ose-cli-artifacts-z82js status: Unknown
2024-10-18 14:26:42,234 …
```

[konflux] update konflux log

---

art-cluster/pipelines/config/argocd/project/art-cd/quay-doomsday-backup/base/doomsday-pipeline-task.yaml
pyartcd/pyartcd/pipelines/quay_doomsday_backup.py

For quay backup pipeline running on cluster, sync only `x86_64` and `s390x` in 4.12 releases, since the other arches are deprecated

[art-cluster] quay backup override arches to sync from quay for 4.12 releases

---

doozer/doozerlib/backend/konflux_image_builder.py

We are seeing increased timeouts for ppc builds. The konflux team is working on increasing the resources, but lets temporarily increase retries for now.

[konflux] temporarily increase retries

---

doozer/doozerlib/backend/konflux_image_builder.py

ppc64le builds are running out of storage space (example [run](https://konflux.apps.stone-prod-p02.hjvn.p1.openshiftapps.com/application-pipeline/workspaces/ocp-art/applications/openshift-4-18/pipelineruns/4-18-ose-cli-artifacts-rpk2m/logs?task=build-images))
Proposing to use a bigger VM. Available VMs listed [here](https://github.com/redhat-appstudio/infra-deployments/blob/main/components/multi-platform-controller/production-downstream/host-config.yaml#L41C5-L41C16). Docs [here](https://konflux.pages.redhat.com/docs/users/getting-started/multi-platform-builds.html#ppc64le-2)

[konflux] use bigger ppc vm

---

doozer/doozerlib/cli/images_streams.py

The approach of updating the JIRA issue AFTER creating it, works.
This was tested by this script.:
```
from jira import JIRA
token_auth = "dont-leak-tokens"
client = JIRA("https://issues.redhat.com", token_auth=token_auth)
if client:
print(f"connected")
else:
print(f"can't connect")
issue_data = {
'project': {'key': 'ART'},
'issuetype': {'name': 'Bug'},
'labels': ['art:reconciliation', f'art:package:openshift-enterprise-hyperkube-container'],
'versions': [{'name': '4.10'}],  # Affects Version/s
'components': [{'name': 'daily-ops'}],
'summary': '[test] this ART ticket should be closed once it is not needed anymore',
'description': 'this ART bug is still for testing'
}
new_issue = client.create_issue(fields=issue_data)
print(f"Issue {new_issue.key} created successfully.")
#issue_key = …
```

ART-10624: set extra fields in reconciliation issues

---

doozer/doozerlib/backend/konflux_image_builder.py

Follows https://github.com/openshift-eng/art-tools/pull/1077
A component resource name must start with a lower case letter

[konflux] add ose-prefix

---

elliott/elliottlib/bzutil.py
elliott/elliottlib/cli/verify_attached_bugs_cli.py
elliott/elliottlib/errata.py

fix issue like https://redhat-internal.slack.com/archives/C04L1FPFHNH/p1729169691264399
use jira api
```
>> res=ErrataConnector()._post("/api/v1/jira/refresh", data=["OCPBUGS-43400"])
ValueError: too many values to unpack (expected 2)
>>> res=ErrataConnector()._post("/api/v1/jira/refresh", json=['OCPBUGS-43400'])
>>> res
<Response [200]>
>>> res.text
'[{"key":"OCPBUGS-43400","status":"Closed","updated":"2024-10-16T23:02:00Z"}]'
```

sync bug with errata before get from errata

---

doozer/doozerlib/backend/konflux_image_builder.py

Reverts openshift-eng/art-tools#1078
Not core issue. 
https://konflux.pages.redhat.com/docs/users/troubleshooting/index.html#no-space-left-on-device is the actual fix

Revert "[konflux] use bigger ppc vm"

---

doozer/doozerlib/backend/konflux_image_builder.py

Restrict to just x86 so that we can mass build and test konflux ocp4 scan. x86 builds on cluster, to builds are significantly faster than on other arches. ([thread](https://redhat-internal.slack.com/archives/C02CTEB3MMF/p1729778261627059?thread_ts=1729778032.439479&cid=C02CTEB3MMF))

[konflux] restrict arches to x86 temporarily

---

pyartcd/pyartcd/pipelines/quay_doomsday_backup.py

Since logs are extensive, hard to debug. `realtime` was set to True initially to make debugging easier, but we can remove that now

[artcluster] Quay backup reduce logs, remove realtime

---

doozer/doozerlib/cli/release_gen_assembly.py
doozer/doozerlib/util.py
ocp-build-data-validator/validator/json_schemas/releases.schema.json

(cherry picked from commit fa2cbfe96dc42db8bceeff43fb842d4290a7ae07)
permit new_versioning scheme to be None
(cherry picked from commit 3159ef44697bc324266c17042df787943753a414)
enhance validator by new_versioning scheme
(cherry picked from commit 0c489598512652494bc4ed54c1766802739fe33e) (cherry picked from commit 5ca196dfa6c4da3e3e4d0a6b1b8b6eb9a981848a)
rh-pre-commit.version: 2.3.1
rh-pre-commit.check-secrets: ENABLED

ART-10785: accept new_versioning scheme in standard assemably names

---

doozer/doozerlib/runtime.py

(cherry picked from commit 47d88c60d05939b7064326053d8a44009009bfd5)
rh-pre-commit.version: 2.3.1
rh-pre-commit.check-secrets: ENABLED

ART-10884: accept assembly name with new versioning scheme

---

artcommon/artcommonlib/util.py
elliott/elliottlib/cli/verify_attached_bugs_cli.py
elliott/tests/test_verify_attached_bugs_cli.py

add two API function, 
`get_next_release_schedule` will get the next release date for a stream release 
the pp API `schedule-tasks/?flags_and__in=dev&fields=path,date_finish` return list of dates like
```
{
"path": [
"OpenShift Container Platform (OCP) 4.16.z GA Release Schedule",
"4.16.z Release Cycle",
"4.16.25"
],
"date_finish": "2024-12-04"
},
{
"path": [
"OpenShift Container Platform (OCP) 4.16.z GA Release Schedule",
"4.16.z Release Cycle",
"4.16.26"
],
"date_finish": "2024-12-11"
},
```
`is_release_this_week` will check if the next release need to prepare this week
so when check regression bug issue, if we don't have next X+1 release need to prepare then blocker not attached to any advisory is expected.

ART-10995 fix false alarm for regression check

---

pyartcd/pyartcd/pipelines/gen_assembly.py

replace get latest accepted nightly method with latest API eg https://amd64.ocp.releases.ci.openshift.org/api/v1/releasestream/4.18.0-0.nightly/latest instead of filter from https://amd64.ocp.releases.ci.openshift.org/api/v1/releasestream/4.18.0-0.nightly/tags

ART-11093 simplify get latest accepted nightly function

---

artcommon/artcommonlib/util.py
elliott/elliottlib/cli/verify_attached_bugs_cli.py
elliott/tests/test_verify_attached_bugs_cli.py

Reverts openshift-eng/art-tools#1066
This has caused an error when promoting 4.12.68: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fpromote-assembly/402/consoleFull

Revert "ART-10995 fix false alarm for regression check"

---

elliott/elliottlib/cli/verify_attached_bugs_cli.py

blocker_advisories is not assigned when ErrataException occurs. We should retry `blocker_advisories = blocker.all_advisory_ids()` after calling `sync_jira_issue`.

Fix unbounded variable error for blocker_advisories

---

.github/workflows/unit-tests.yaml

```
E   ImportError: Failed to import system RPM module. Make sure RPM Python bindings are installed on your system.
```
[run](https://github.com/openshift-eng/art-tools/actions/runs/11630513728/job/32389618965?pr=1105)
pyartcd doesn't seem to work on python3.11, bumping down to 3.9 for now

fix gh workflow

---

doozer/doozerlib/backend/konflux_image_builder.py

`ose-installer-artifacts` errors out with OOM
```
taskRunSpecs:
- pipelineTaskName: build-images
stepSpecs:
- name: sbom-syft-generate
computeResources:
requests:
memory: 5Gi
limits:
memory: 10Gi
```
https://konflux.pages.redhat.com/docs/users/how-tos/configuring/overriding-compute-resources.html

[konflux] increase sbom-syft-generate task memory

---

pyartcd/pyartcd/pipelines/operator_sdk_sync.py

Release present in cincinnati fast channel doesn't mean that it is automatically visible on the customer portal. I'd rather check and close that subtask manually.

Don't close 'customer portal' subtask automatically

---

pyartcd/pyartcd/pipelines/ocp4.py
pyartcd/pyartcd/util.py

`get_signing_mode` was using the ocp-build-data branch from openshift-eng, when it should be using the value from `DOOZER_DATA_PATH` and `DOOZER_DATA_GITREF` params from Jenkins
Failed run: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/hack/job/ashwin-aos-cd-jobs/job/build%252Focp4/69/
Succeeded run:  https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/hack/job/ashwin-aos-cd-jobs/job/build%252Focp4/70

pass doozer data path for get_signing_mode

---

doozer/doozerlib/backend/konflux_image_build_pipelinerun.yaml

Manually reonboarded art-konflux-template [component](https://konflux.apps.stone-prod-p02.hjvn.p1.openshiftapps.com/application-pipeline/workspaces/ocp-art/applications/art-konflux-template/components/art-konflux-template) to pull in the latest konflux images. Looks like Konflux is not automatically raising PRs to that repo.
Reference file: https://github.com/openshift-priv/art-konflux-template/blob/main/.tekton/art-konflux-template-push.yaml

[konflux] update PLR template

---

doozer/doozerlib/backend/konflux_image_builder.py
doozer/doozerlib/cli/images_konflux.py

Till now we had been skipping post build steps so that we can get the builds working. But skipping them violates enterprise contract policy. So now is a good time to enable the checks and the hash out any issues if any.
But keeping the skip checks as a param if we need it in the future.

[konflux] skip-checks param

---

pyartcd/pyartcd/pipelines/promote.py
pyartcd/tests/pipelines/test_promote.py

Use the generated image stream to promote and not the reference nightlies, if they are present in the assembly. The reference nighlties should only be used for validation.
i.e. we should not use the `--from-release` param in `oc adm release new`

ART-10832: do not use reference nightlies for promotion

---

doozer/doozerlib/backend/konflux_image_builder.py
doozer/doozerlib/cli/config_plashet.py
doozer/doozerlib/plashet.py
doozer/doozerlib/util.py
elliott/elliottlib/runtime.py
pyartcd/pyartcd/__main__.py
pyartcd/pyartcd/jenkins.py
pyartcd/pyartcd/pipelines/build_microshift.py
pyartcd/pyartcd/pipelines/build_microshift_bootc.py
pyartcd/pyartcd/plashets.py
pyartcd/pyartcd/util.py

https://issues.redhat.com/browse/ART-10563
Should go after https://github.com/openshift-eng/aos-cd-jobs/pull/4270
Live run: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/hack/job/sidsharm-aos-cd-jobs/job/build%252Fbuild-microshift/37/
Summary of changes:
- At the end of build-microshift job, trigger build-microshift-bootc job, which:
- Find if a bootc image build exists for the given named assembly
- If not, prepare to build. Do plashet sync, if plashet sync is needed (make sure microshift rpm is one that's latest for assembly). And then finally rebase and build
- Upload `bootc-pullspec.txt` to mirror (https://mirror.openshift.com/pub/openshift-v4/x86_64/microshift/ocp-dev-preview/4.18.0-ec.1/el9/bootc-pullspec.txt) for each arch the image built for.
- Tweak to …

ART-10563 Build bootc image as part of build-microshift-bootc job

---

doozer/doozerlib/backend/konflux_image_build_pipelinerun.yaml

```
- metadata:
code: source_image.exists
msg: No source image references found
- metadata:
code: tasks.required_tasks_found
msg: One of "source-build", "source-build-oci-ta" tasks is missing
```
Enterprise Contract was failing because `build-source-image` was set to false. Since we always want in enabled, setting it to true. Can override it later if needed

ART-11251: [konflux] Build source image by default

---

doozer/doozerlib/backend/rebaser.py

Fixes Enterprise Contract issue
```
- metadata:
code: labels.disallowed_inherited_labels
msg: The "description" label should not be inherited from the parent image
- metadata:
code: labels.disallowed_inherited_labels
msg: The "summary" label should not be inherited from the parent image
```
Successful image generated in https://konflux.apps.stone-prod-p02.hjvn.p1.openshiftapps.com/application-pipeline/workspaces/ocp-art/applications/openshift-4-18/pipelineruns/ose-4-18-openshift-enterprise-base-rhel9-8gcwn
This change is only for konflux, since this function is part of `KonfluxRebaser` class

ART-11251: [konflux] set summary, description labels for rebase

---

pyartcd/pyartcd/__main__.py
pyartcd/pyartcd/jenkins.py
pyartcd/pyartcd/locks.py
pyartcd/pyartcd/pipelines/ocp4_konflux.py
pyartcd/pyartcd/pipelines/ocp4_scan_konflux.py
pyartcd/pyartcd/pipelines/scheduled/schedule_ocp4_scan_konflux.py

- Add pipeline to schedule ocp4-scan for Konflux
- Schedule ocp4-konflux only for x86
- Introduce per-version locks for Konflux builds and scans

Schedule ocp4-scan-konflux

---

doozer/doozerlib/backend/konflux_image_build_pipelinerun.yaml

Use updated image SHAs from https://github.com/openshift-priv/art-konflux-template/blob/main/.tekton/art-konflux-template-push.yaml

[konflux] Bump image SHAs

---

doozer/doozerlib/backend/rebaser.py

Follows: https://github.com/openshift-eng/art-tools/pull/1121
Set default dummy values for labels konflux is looking for, to fix EC issue
```
The "io.k8s.description" label should not be inherited from the parent image
```

ART-11251: [konflux] set dummy default labels

---

artcommon/artcommonlib/konflux/konflux_db.py
artcommon/tests/test_konflux_db.py

Update the function to allow us query for `WHERE name LIKE '%installer%'` or the like
Tested with art-build-history: https://konflux-build-history-hackspace-dpaolell.apps.artc2023.pc3z.p1.openshiftapps.com/search?name=installer&outcome=failure&group=-&assembly=stream&after=2024-11-13&engine=brew

Re-write konflux_db.search_builds_by_fields() to handle extra patterns

---

artcommon/artcommonlib/release_util.py
artcommon/tests/test_util.py
doozer/doozerlib/cli/scan_sources.py
doozer/doozerlib/cli/scan_sources_konflux.py
doozer/doozerlib/util.py
doozer/tests/test_util.py

Move `isolate_timestamp_in_release()` to artcommon

Move isolate_timestamp_in_release() to artcommon

---

doozer/doozerlib/backend/konflux_image_build_pipelinerun.yaml

Enterprise Contract policy requires us to keep task SHAs upto date. 
SHAs copied over from https://github.com/openshift-priv/art-konflux-template/pull/21

[konflux] bump task SHAs

---

doozer/doozerlib/cli/images_konflux.py
pyartcd/pyartcd/pipelines/ocp4_konflux.py

Instead of crashing the pipeline on rebase failures, exclude those images from the build step.
Prepare ocp4-konflux to accept an image build strategy similar to what we have in ocp4, where can build all images, a pinned subset, or exclude only specific images.
Do not spam us about rebase failures (would happen too often at the moment)

Introduce build plan for konflux builds

---

artcommon/artcommonlib/konflux/konflux_db.py
artcommon/tests/test_konflux_db.py

In `konflux_db.search_builds_by_fields()` we currently use LIKE to perform simple pattern matching using wildcard characters. This is limited to  basic wildcard patterns (`%` to match zero or more characters, `_` to match exactly one character).
Replace `LIKE` with `REGEXP_CONTAINS` to allow more complex regular expression matching. Supported Features are:
- Anchors (^ for the beginning of a string, $ for the end).
- Character classes (e.g., [abc], [a-z]).
- Quantifiers (e.g., *, +, ?, {n,m}).
- Alternation (| for "or" conditions).

Introduce regex matching in konflux_db.search_builds_by_fields()

---

doozer/doozerlib/constants.py

Update URLs to new konflux cluster
Follows https://github.com/openshift-eng/aos-cd-jobs/pull/4299

ART-11441: [konflux] Update URLs to point to new cluster

---

pyartcd/pyartcd/pipelines/prepare_release.py

The returned object of `AsyncErrataAPI.create_batch` is flattened since https://github.com/openshift-eng/art-tools/pull/1139. Getting the "data" field is no longer needed.

Fix batch creation

---

pyartcd/pyartcd/pipelines/ocp4_scan_konflux.py

Since we are good to build aarch64 regularly now as well.
Other arches have to wait until konflux setups up the VM

[konflux] Build aarch64 regularly as well

---

doozer/doozerlib/cli/scan_sources_konflux.py
doozer/doozerlib/util.py
doozer/requirements.txt

Test build: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4-scan-konflux/65/console
To test this change, a test job has been pointed at `test` assembly and a custom art-tools, where all other checks (upstream changes, config changes, etc.) have been commented out

ART-11062 ocp4-scan-konflux: check builder changes

---

doozer/doozerlib/backend/konflux_image_builder.py

Now that we have our own cluster, we can reduce the number of retires to 3, as it was originally set. If builds fail here, its most likely a legit issue which warrants further investigation and not a flake, so no need for additional retires

[konflux] set build retires to 3

---

doozer/doozerlib/backend/konflux_image_builder.py

Follows https://github.com/openshift-eng/art-tools/pull/1166
Includes Sid's suggestion: https://github.com/openshift-eng/art-tools/pull/1166#discussion_r1866412110

[konflux] Fail when SBOMs can't be accessed (update)

---

doozer/doozerlib/cli/images_health.py

rh-pre-commit.version: 2.3.2
rh-pre-commit.check-secrets: ENABLED

ART-11446: images-health should report failures only when fail count > 1

---

doozer/doozerlib/backend/konflux_client.py

microshift-bootc times out after the default '2h' for the apply-tags task. So increasing to '4h'

[konflux] update apply-tags timeout

---

pyartcd/pyartcd/pipelines/update_golang.py

- add `tag_builds` flag to UpdateGolangPipeline, if its set then tag golang builds into override tag
- in wait-repo add `--request` parameter, it will request gen-repo if needed
- refactor update golang streams pr to support major version bump(update group.yml and previous golang version)
- update to create pr for only one release

[ART-11187] add tag-builds parameter and support update go major version

---

doozer/doozerlib/cli/scan_sources_konflux.py

scan-sources for Konflux is already not scanning for changes in images that are not enabled in the `konflux` config stanza.
Nonetheless, if a parent image of a disabled one is changing, doozer propagates the child into the report and marks it for rebuild.
To prevent this, perform an extra filtering right before generating the output report, which serves as input to the ocp4-scan-konflux pipeline and to ocp4-konflux.

Exclude images not enabled in Konflux from the scan report

---

pyartcd/pyartcd/pipelines/update_golang.py

GO_PREVIOUS will be removed so only have latest

allow go previous is none

---

doozer/doozerlib/backend/konflux_client.py
doozer/doozerlib/backend/konflux_image_builder.py

Ref [thread](https://redhat-internal.slack.com/archives/C06Q309QUDV/p1733250810691609) for details
ose-installer-artifacts require more storage, hence a new VM variant was created for ARM
Alongside https://github.com/openshift-eng/ocp-build-data/pull/5798

[konflux] support VM override

---

artcommon/artcommonlib/util.py
pyartcd/pyartcd/pipelines/build_microshift.py
pyartcd/pyartcd/pipelines/build_microshift_bootc.py
pyartcd/pyartcd/pipelines/gen_assembly.py
pyartcd/pyartcd/pipelines/prepare_release.py
pyartcd/pyartcd/pipelines/review_cvp.py
pyartcd/pyartcd/pipelines/update_golang.py

Add yaml_handler function to artcommon lib to set yaml config and load by others to reduce duplication
also set indent config for yaml, this will change list item
```
arches:
- x86_64
- ppc64le
- s390x
- aarch64
```
to
```
arches:
- x86_64
- ppc64le
- s390x
- aarch64
```
for better reading

move yaml lib into artcommon lib

---

doozer/doozerlib/backend/konflux_client.py

Reverts openshift-eng/art-tools#1177
Apply tags should only take a couple of minutes. Something else might be going on, so additional investigation might be required.

Revert "[konflux] update apply-tags timeout"

---

doozer/doozerlib/backend/konflux_image_builder.py
doozer/requirements.txt

We rely on "syft:metadata:sourceRpm" which is generated by syft, the cli tool konflux uses to generate sbom. 
It is not the official identifier in the sbom spec, it can go away if another tool is used. 
Instead rely on purl which is the identifier in the sbom spec 
https://cyclonedx.org/docs/1.6/json/#components_items_purl
Use https://github.com/package-url/packageurl-python to parse purl
Note: https://cyclonedx-python-library.readthedocs.io/en/latest/schema-support.html is a nice lib to 
work with the whole sbom, but lacks support for some schema keys in the latest version which konflux uses.
Test
```
$ python3 -m asyncio
>>> from doozerlib.backend.konflux_image_builder import KonfluxImageBuilder
>>> pullspec = "quay.io/openshift-release-dev/ocp-v4.0-art-dev:microshift-bootc-v4.18.0-20241 …
```

Get source rpm from purl

---

doozer/doozerlib/backend/konflux_client.py
doozer/doozerlib/backend/konflux_image_build_pipelinerun.yaml

Enterprise Contract (EC) requires us to build source image always. This value was set in the yaml file, but the default value there is `false`. Setting that value in code as per current pattern.

[konflux] set build source image as true

---

doozer/doozerlib/backend/konflux_image_builder.py

cosign doesn't seem to be correctly pulling the auth for the art-images registry. But it does support params to allow passing in values directly, which seems to fix the issue.
Tested, [works](https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4-konflux/489/console)

[konflux] pass registry username-password for cosign

---

art-cluster/pipelines/data/project/art-cd/image/Containerfile.base
doozer/doozerlib/coverity.py
ocp-build-data-validator/Dockerfile
ocp-build-data-validator/deploy/Dockerfile.base

2015 cert is deprecated on https://certs.corp.redhat.com/certs/

deprecate 2015 IT cert

---

doozer/doozerlib/constants.py

Now that we are on the new cluster, lets increase the build queue size to `25` per OCP version

[konflux] increase build queue size

---

doozer/doozerlib/backend/konflux_image_builder.py

purl error
```
ERROR Failed writing record to the konflux DB: Invalid purl 'pkg:github/docker:/#morphy/revive-action:v2' cannot contain a "user:pass@host:port" URL Authority component: ''.
```
Skip SBOM components with invalid purl

[konflux] skip SBOM components with incorrect purl

---

doozer/doozerlib/cli/scan_sources_konflux.py

It happened (due to manual build actions mostly) to have multiple builds from the same upstream commit. In this case, scan-sources for konflux compares the NVRs and finds them different (rebase times differ), so concluded that the image needed to be rebuilt. 
To avoid that, compare the commitish of the latest retrieved build with the most recent upstream commit hash. If they match, no need to rebuild even if NVRs differ. Otherwise, scan-sources can conclude that an upstream commit has been reverted, so we need a more recent build from the HEAD commit.

Improve scan-sources-konflux

---

doozer/doozerlib/backend/konflux_client.py
doozer/doozerlib/backend/konflux_image_builder.py
doozer/doozerlib/cli/images_konflux.py
doozer/doozerlib/constants.py
pyartcd/pyartcd/pipelines/ocp4_konflux.py

Since we are now dynamically pulling the PipelineRun template from https://github.com/openshift-priv/art-konflux-template/blob/main/.tekton/art-konflux-template-push.yaml, in case if there is an issue with one of the newer task builds, having this option will allow us to use a temporary roll back if necessary, instead of merging a revert PR, thereby offering us more flexibility.
Alongside https://github.com/openshift-eng/aos-cd-jobs/pull/4313

[konflux] allow field to override konflux template url

---

doozer/doozerlib/cli/scan_sources_konflux.py

BigQuery also stored Brew build records. This was confusing ocp4-scan-konflux that kept on finding multiple builds from the same upstream commit of a given component. Setting engine=Konflux in the search base params will fix that. We'll then need to override this param when scanning RPM builds, that are only built by Brew
Test build: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4-scan-konflux/164/console

ocp4-scan-konflux: only look at Konflux builds by default

---

art-cluster/pipelines/data/project/art-cd/image/Containerfile.base

fixes this
```
2024-12-16 15:03:20,231 koji         ERROR (gssapi auth failed: requests.exceptions.SSLError: HTTPSConnectionPool(host='brewhub.engineering.redhat.com', port=443): Max retries exceeded with url: /brewhub/ssllogin (Caused by SSLError(SSLCertVerificationError(5, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)'))))
```

art-cd: use current IT root CA

---

doozer/tests/cli/test_gen_payload.py

No actual HTTP requests to GitHub should be made by unit test. `what_is_in_master` function should be mocked.

doozer: Don't send HTTP requests in unit test

---

pyartcd/pyartcd/pipelines/promote.py

Noticed that rhcos_sync jobs were [failing](https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Frhcos_sync/115/parameters/) because we were passing the entire pull spec as param.

trigger rhcos_sync with shortname

---

pyartcd/pyartcd/pipelines/quay_doomsday_backup.py
pyartcd/pyartcd/slack.py

Make `quay-doomsday-backup` asynchronous
- For running AWS and mirror commands, use `AsyncRetrying` from `tenacity` directly because `cmd_assert_async` does not contain retry logic and to avoid having to create a wrapper function around `cmd_assert_async` to use with `tenacity.retry` decorator
Sending results to Slack
- Create a new thread in a version specific release channel and send updates there
- After the sync of all arches either succeeds or fails, send final message to the thread and to the channel
- Modify `say()` and `say_in_thread()` from `pyartcd/slack.py` to include optional parameter -`broadcast` - to send thread replies to the channel as well
- Example of a successful run [here](https://redhat-internal.slack.com/archives/C05HB1F1THP/p1733224749354249)
- Example of a failed …

Make quay-doomsday-backup async and send its results to Slack

---

elliott/elliottlib/errata.py
elliott/tests/test_brew.py

`test_get_brew_build_failure` has a few issues that causes the execution takes too much time (> 30 seconds):
- `requests.get` is not property mocked, causing actual HTTP requests send to Errata.
- It retries 10 times on error. For each retry it waits for 3 seconds.
This PR fixes the issue and also updates `test_get_brew_build_success` and `test_get_brew_build_success_session` to follow the same pattern.

Elliott: Fix unit tests that take too much time

---

pyartcd/pyartcd/pipelines/rebuild_golang_rpms.py
pyartcd/requirements.txt
pyartcd/tests/pipelines/test_gen_assembly.py
pyartcd/tests/pipelines/test_promote.py
pyartcd/tests/test_rebuild_golang_rpms.py
pyartcd/tests/test_signatory.py

- Mute unit test warnings (mostly with better mock)
- Eliminate HTTP requests from unit tests (by mocking functions that makes HTTP requests) 
- Minor cleanups
See individual commits for details.

pyartcd unit test fixes and cleanups

---

ocp-build-data-validator/validator/json_schemas/image_content.requires.schema.json

Either `stream` or `member` field is required.

Fix schema for ci_build_root

---

doozer/doozerlib/cli/images_health.py

when there are more than one build

ART-11446: images-health should report only failures

---

doozer/doozerlib/backend/rebaser.py

Erroring out due to missing .oit folder
Tested, [works](https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4-konflux/1213/console)

[konflux] fix missing dir issue

---

doozer/doozerlib/cli/images_health.py

Currently, images-health is searching for builds within a 1-week window. This is not enough for images that do not get frequent rebuilds, such as [ose-machine-os-images](https://art-build-history-art-build-history.apps.artc2023.pc3z.p1.openshiftapps.com/search?name=ose-machine-os-images&outcome=both&group=openshift-4.15&assembly=stream&after=2024-12-06&engine=brew&art-job-url=). This is causing undesired pings like [this one](https://redhat-internal.slack.com/archives/CB95J6R4N/p1735863147706569)

images-health: look back to latest 30 days

---

doozer/doozerlib/backend/rebaser.py

Builds were erroring out due to yarn install timeouts. 
Rebased line example: https://github.com/openshift-priv/networking-console-plugin/blob/art-openshift-4.19-assembly-stream-dgk-networking-console-plugin/Dockerfile#L31

[konflux] increase yarn install timeout

---

pyartcd/pyartcd/pipelines/ocp4.py
pyartcd/pyartcd/pipelines/ocp4_konflux.py
pyartcd/pyartcd/runtime.py
pyartcd/tests/pipelines/test_ocp4.py

Test build: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/hack/job/dpaolell/job/ocp4-konflux/22/console

ocp4: clean up sources at the end of the artcd pipeline

---

artcommon/artcommonlib/konflux/konflux_db.py
artcommon/artcommonlib/runtime.py
artcommon/artcommonlib/util.py
artcommon/tests/test_konflux_db.py
doozer/doozerlib/backend/build_repo.py
doozer/doozerlib/backend/konflux_image_builder.py
doozer/doozerlib/backend/konflux_olm_bundler.py
doozer/doozerlib/backend/rebaser.py
doozer/doozerlib/cli/images_health.py
doozer/doozerlib/cli/images_konflux.py
doozer/doozerlib/cli/scan_sources_konflux.py
doozer/doozerlib/image.py
doozer/doozerlib/source_resolver.py
doozer/doozerlib/util.py
doozer/tests/backend/test_build_repo.py
doozer/tests/backend/test_konflux_olm_bundler.py
doozer/tests/cli/test_gen_payload.py

Test command:
```sh
doozer --assembly=test --group=openshift-4.18 --latest-parent-version beta:images:konflux:bundle --konflux-kubeconfig=/path/to/kubeconfig -
-konflux-namespace=ocp-art-tenant --image-repo=quay.io/openshift-release-dev/ocp-v4.0-art-dev-test ose-metallb-operator-container-v4.18.0-202410251504.p0.gc
5a3b07.assembly.test.el9
```
Test build: https://konflux.apps.kflux-ocp-p01.7ayg.p1.openshiftapps.com/application-pipeline/workspaces/ocp-art/applications/openshift-4-18/pipelineruns/ose-metallb-operator-bundle-container-s2724

Konflux: Add OLM bundle rebase/build support

---

doozer/doozerlib/cli/release_gen_assembly.py

When get rhcos arches, use group config arches instead of parameter arches for nightly.
https://redhat-internal.slack.com/archives/GDBRP5YJH/p1734708885038709?thread_ts=1734705090.164539&cid=GDBRP5YJH

ART-11093 use group arches to get rhcos list

---

doozer/doozerlib/backend/konflux_client.py
doozer/doozerlib/backend/konflux_image_builder.py
doozer/doozerlib/backend/konflux_olm_bundler.py
doozer/doozerlib/cli/images_konflux.py
doozer/doozerlib/constants.py
doozer/tests/backend/test_konflux_olm_bundler.py
pyartcd/pyartcd/constants.py
pyartcd/pyartcd/pipelines/ocp4_konflux.py

Per
https://konflux.pages.redhat.com/docs/users/getting-started/building-olm-products.html#_building_file_based_catalog_fbc_components,
we have to build OLM bundles using the single-arch pipelinerun template.
This PR contains multiple commits for fixing some minor issues with using different templates. See the commit message of each commit.

Konflux: Use single-arch pipelinerun template to build OLM bundles

---

doozer/doozerlib/assembly_inspector.py
doozer/doozerlib/build_status_detector.py
doozer/doozerlib/cli/olm_bundle.py
doozer/doozerlib/cli/release_gen_assembly.py
doozer/doozerlib/cli/release_gen_payload.py
doozer/doozerlib/cli/scan_sources.py
doozer/doozerlib/distgit.py
doozer/doozerlib/image.py
doozer/doozerlib/metadata.py
doozer/doozerlib/plashet.py
doozer/tests/test_metadata.py
doozer/tests/test_plashet.py
elliott/elliottlib/cli/find_builds_cli.py

`get_latest_build` will serve as a unique entry point to find builds in both Brew and Konflux, based on a new `build-system`  option that will be given to the runtime. Renaming `medatata.get_latest_build()` into `get_latest_brew_build()` will later let us define a `get_latest_konflux_build()` function and make `get_latest_build` a unique entrypoint for both, being controlled by the build-system option.
Test builds:
- [gen-assembly](https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fgen-assembly/356/console)
- [build-sync](https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fbuild-sync/13532/console)
- [ocp4](https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/jo …

Rename medatata.get_latest_build into get_latest_brew_build

---

doozer/doozerlib/cli/release_gen_payload.py

Due to the large number of images, any error in fetch in oc mirror
leads to a fail, which blocks us. So chunk these requests with appropriate
retry.

Chunk oc mirror commands

---

artcommon/artcommonlib/konflux/konflux_db.py
artcommon/tests/test_konflux_db.py
doozer/doozerlib/cli/scan_sources_konflux.py

- Move the datetime.replace(tzinfo=…) call from search_builds_by_fields to the scan_sources caller. This function is to force set the timezone for a given datetime object. If it is already timezone aware, it will override its timezone and cause an unexpected timezone change. We should only use it on timezone “naive” objects.
- Use datetime.astimezone() to convert all passed datetime objects into timezone aware objects. This makes sure all datetime calculations are timezone aware, and all datetime objects passed to BigQuery are also timezone aware.

KonfluxDB: Always use timezone aware datetime objects

---

pyartcd/pyartcd/pipelines/quay_doomsday_backup.py
pyartcd/pyartcd/slack.py

Nearly identical changes as in https://github.com/openshift-eng/art-tools/pull/1170 (which has been reverted).
The only difference is that now the code does not query all RH Slack channels to get the channel ID. It simply read the ID from the Slack API response.
- [Example](https://redhat-internal.slack.com/archives/C05HB1F1THP/p1737042238643629) of a message after a successful run
- [Example](https://redhat-internal.slack.com/archives/C05HB1F1THP/p1737042297567809) of a message after a failed run

[ART-11306] Make quay-doomsday-backup async and send its results to Slack

---

pyartcd/pyartcd/pipelines/build_microshift.py

This aligns with our promote job - don't raise validation error for bugs/advisory
for preGA assemblies. Instead report in slack and proceed.
Test run: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fbuild-microshift/1623/console

Don't raise microshift advisory validation error for preGA assembly

---

doozer/doozerlib/backend/build_repo.py
doozer/doozerlib/backend/konflux_client.py
doozer/doozerlib/cli/__main__.py
doozer/doozerlib/cli/fbc.py
doozer/doozerlib/opm.py
doozer/tests/cli/test_fbc.py
doozer/tests/test_opm.py

This command implements the procedule described in https://github.com/konflux-ci/olm-operator-konflux-sample/blob/main/docs/konflux-onboarding.md#create-the-fbc-in-the-git-repository to create an FBC repo from a given published index. Non-ART managed OLM packages will be filtered out.
Test command:
```
doozer --debug --group=openshift-4.17 beta:fbc:import --from-index=registry.redhat.io/redhat/redhat-operator-index:v4.17 ./fbc-4.17
```

[Konflux] Add fbc:import command to create FBC from published index

---

artcommon/artcommonlib/konflux/konflux_db.py
artcommon/tests/test_konflux_db.py
doozer/doozerlib/cli/cli_opts.py
doozer/doozerlib/cli/scan_sources_konflux.py
doozer/doozerlib/metadata.py
pyartcd/pyartcd/pipelines/ocp4_scan_konflux.py

Follows:
- https://github.com/openshift-eng/art-tools/pull/1266
- https://github.com/openshift-eng/art-tools/pull/1267
- https://github.com/openshift-eng/art-tools/pull/1268
Implement the new `metadata.get_latest_konflux_build()` function and start using it in scan-sources-konflux.
Requires doozer to be called with the `--build-system=konflux` option.
Test build: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4-scan-konflux/8122/console

Define metadata.get_latest_konflux_build()

---

doozer/doozerlib/backend/konflux_client.py
doozer/doozerlib/backend/konflux_image_builder.py
doozer/doozerlib/backend/rebaser.py

Support two new network modes `hermetic` and `internal-only`. The latter is set by using proxies to allow traffic only to RH internal network, while the former is configured by setting a value `hermetic` to `true` for Konflux PipelineRun

[konflux] network modes

---

doozer/doozerlib/backend/konflux_image_builder.py
doozer/doozerlib/backend/konflux_olm_bundler.py
doozer/doozerlib/cli/images_konflux.py
doozer/doozerlib/constants.py
doozer/tests/backend/test_konflux_olm_bundler.py
pyartcd/pyartcd/__main__.py
pyartcd/pyartcd/constants.py
pyartcd/pyartcd/jenkins.py
pyartcd/pyartcd/locks.py
pyartcd/pyartcd/pipelines/ocp4_konflux.py
pyartcd/pyartcd/pipelines/olm_bundle_konflux.py

1. Add new pyartcd job `olm_bundle_konflux` to build OLM bundles with Konflux.
2. Auto-trigger `olm_bundle_konflux` job from `ocp4_konflux` job.
3. Update Doozer to write record.log for information about the resulting operators and bundles.
4. Follow up https://github.com/openshift-eng/art-tools/pull/1277/: Use distgit key instead of Brew component name for NVR.
This PR requires https://github.com/openshift-eng/art-tools/pull/1281 for setting the correct pull secret on buildvm.
- Test olm_bundle_konflux build: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/securityRealm/commenceLogin?from=%2Fjob%2Fhack%2Fjob%2Fyuxzhu%2Fjob%2Faos-cd-builds%2Fjob%2Fbuild%25252Folm_bundle_konflux%2F11%2Fconsole
However, the part of triggering olm_bundle_konflux from ocp4_konflux can't …

[Konflux] Add olm_bundle_konflux job

---

doozer/doozerlib/backend/rebaser.py
doozer/doozerlib/distgit.py

Per [doc](https://docs.google.com/document/d/1Ajc6MSNJz20b34L7QNwoPcWKxId7Fy-eRt7oqyaJl8c/edit?tab=t.0#heading=h.4fbec24ysdh3)
Inserting ENV variables so that upstream can indentify if the build environment is brew/konflux and if the dependency manager that's available is cachito or cachi2

[konflux] ENV variables for cachito/cachi2 and network mode identifcation

---

pyartcd/pyartcd/pipelines/build_sync.py

For non-stream assemblies we were raising before updating title of the run.
example: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fbuild-sync/14035/
So fix that.

Update build-sync title before exiting

---

doozer/doozerlib/cli/scan_sources_konflux.py
pyartcd/pyartcd/pipelines/ocp4_scan_konflux.py

In the Konflux call, it was discussed that we build only x86, for now, for rapid development, until a single arch payload is generated.

[konflux] Build only for x86 for now

---

doozer/doozerlib/backend/konflux_olm_bundler.py
doozer/doozerlib/backend/rebaser.py
doozer/doozerlib/brew_info.py
doozer/doozerlib/cli/images_streams.py
doozer/doozerlib/cli/release_gen_assembly.py
doozer/doozerlib/cli/scan_sources_konflux.py
doozer/doozerlib/distgit.py
doozer/doozerlib/image.py
doozer/doozerlib/olm/bundle.py
doozer/doozerlib/util.py
doozer/tests/backend/test_konflux_olm_bundler.py
doozer/tests/test_distgit/test_resolve_image_from_upstream_parent.py

Currently, we run `oc image info` with --filter-by-os always on. This PR suggests making the `oc_image_info()` function generic, and create new specific functions to be used with the `--filter-by-os` and `--show-multiarch` options instead.

Make oc_image_info option generic

---

doozer/doozerlib/backend/rebaser.py

Successful run: https://konflux.apps.kflux-ocp-p01.7ayg.p1.openshiftapps.com/application-pipeline/workspaces/ocp-art/applications/openshift-4-19/pipelineruns/ocp-art-tmp-onboard-policy-stage-4-19-422dh/detail
Setting it to `None` had started failing recently.

[konflux] update label to Empty

---

doozer/doozerlib/cli/olm_bundle.py

To resolve ```2025-01-28 10:48:11,553 art_tools.doozerlib.cli.olm_bundle ERROR Failed writing record to the konflux DB: KonfluxBundleBuildRecord.__init__() got an unexpected keyword argument 'artifact_type'```

Olm bundle build db write fix

---

pyartcd/pyartcd/pipelines/build_rhcos.py

This reverts commit 45088161971df1aace0527b32b7d3a6bd0e2d74e.
As mentioned in [1] this can have a few side effects that I don't really think we want to deal with on a continuing basis. Let's just revert back to letting the x86_64 buils pass tests and upload to clouds first (i.e. error prone operations) first.
[1] https://github.com/openshift-eng/art-tools/pull/1164#issuecomment-2620026207

Revert "Start RHCOS arch jobs earlier"

---

pyartcd/pyartcd/pipelines/olm_bundle_konflux.py

related to the slack message on 4.18:
https://redhat-internal.slack.com/archives/C07BD2S0XRN/p1738121101574969

disabled konflux_olm_bundle failed message for realease channels

---

doozer/doozerlib/backend/rebaser.py

We store Konflux specific config data in a `konflux` stanza in the components yaml files. We generally check those fields one by one to override/apply specific behavior.
This can be improved by checking if a `konflux` stanza exists at rebase time, and if it does merging it with the main config, just like we do (or used to do) with `alternative_upstream`. This also lets us automatically override any config we want to replace for Konflux only. As an example, this PR along with https://github.com/openshift-eng/ocp-build-data/compare/openshift-4.19...locriandev:ocp-build-data:4.19-test-dtk  fixed DTK build failures in Konflux: https://konflux.apps.kflux-ocp-p01.7ayg.p1.openshiftapps.com/application-pipeline/workspaces/ocp-art/applications/openshift-4-19/pipelineruns/ose-4-19-driver-toolkit-j7q …

[konflux] Merge konflux config before rebase

---

doozer/doozerlib/cli/release_gen_payload.py

Currently `@retry` applies for the func which runs `oc adm release new` for all arches.
Instead wrap it on the command itself, so only the failed arch invocation is retried.

Retry failed arch only

---

pyartcd/pyartcd/pipelines/build_rhcos.py

Raise appropriately when api request fails
https://urllib3.readthedocs.io/en/stable/reference/urllib3.util.html#urllib3.util.Retry
Before:
```
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
After:
```
requests.exceptions.RetryError: HTTPSConnectionPool(host='jenkins-rhcos--prod-pipeline.apps.int.prod-stable-spoke1
-dc-iad2.itup.redhat.com', port=443): Max retries exceeded with url: /job/build/api/json?
tree=builds%5Bnumber,description,result,actions%5Bparameters%5Bname,value%5D%5D%5D (Caused by 
ResponseError('too many 403 error responses'))
```
https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Frhcos/12838/console

Raise for status build/rhcos

---

doozer/doozerlib/assembly_inspector.py
doozer/doozerlib/build_info.py
doozer/doozerlib/cli/inspect_stream.py
doozer/doozerlib/cli/release_gen_assembly.py
doozer/doozerlib/cli/release_gen_payload.py
doozer/doozerlib/cli/scan_sources.py
doozer/doozerlib/distgit.py
doozer/doozerlib/image.py
doozer/doozerlib/metadata.py
doozer/tests/cli/test_gen_payload.py
doozer/tests/cli/test_scan_sources.py
doozer/tests/test_assembly_inspector.py
doozer/tests/test_brew_inspector.py
doozer/tests/test_image.py
pyartcd/pyartcd/pipelines/build_sync.py

This PR aims at starting to sync out Konflux image builds, and to update the related imagestreams on the CI cluster. For this purpose, some brew-specific classes have been made flexible enough to handle Konflux build records as well. Specifically:
- `BuildImageInspector` has been renamed into `BuildRecordInspector`; this acts as an abstract superclass for `BrewBuildRecordInspector` and `KonfluxBuildRecordInspector`
- `ArchiveImageInspector` has been renamed into `ImageInspector`; again, this acts as an abstract superclass for `BrewImageInspector` and `KonfluxImageInspector`
The concrete implementations of `BuildRecordInspector` and `ImageInspector` have what it takes to gather the payload entries for both build systems.
The assembly checks [are being …

ART-11391 build-sync for konflux

---

doozer/doozerlib/rhcos.py

context: https://redhat-internal.slack.com/archives/CB95J6R4N/p1738691928076439
and https://github.com/openshift/os/pull/1737

Ignore invalid version-release rpms in rhcos

---

artcommon/artcommonlib/exectools.py

This will let us easily copy-paste commands around, as well as find occurrences of a certain command invocation in the logs.

exectools: print the command string instead of a list

---

pyartcd/pyartcd/jenkins.py
pyartcd/pyartcd/pipelines/build_sync.py
pyartcd/pyartcd/pipelines/ocp4.py
pyartcd/pyartcd/pipelines/ocp4_konflux.py
pyartcd/pyartcd/util.py
pyartcd/tests/pipelines/test_ocp4.py

Hooking up build-sync for Konflux runs to ocp4-konflux. Currently, this is being limited to 4.19 only; we can remove the [switch](https://github.com/openshift-eng/art-tools/compare/main...locriandev:trigger-build-sync-for-konflux?expand=1#diff-722ce25d123c3fd8f7c2ebbbd5ab0e9f310f3f4b82b1f4a37d568f6f8f17dd47R180) once we think we're ready to start syncing all version building for Konflux. 
Test run for [ocp4-konflux](https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4-konflux/4148/console) triggered [this build-sync](https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fbuild-sync/14516/)

ART-11391 Trigger build-sync after ocp4-konflux

---

artcommon/artcommonlib/bigquery.py
doozer/doozerlib/backend/rebaser.py
doozer/doozerlib/metadata.py
pyartcd/requirements.txt

- REMOTE_SOURCES needs to be injected as relative path instead of absolute
- REMOTE_SOURCES_DIR must be defined
- cachito.env must exist
Also:
- Changing to konflux.cachito.mode instead of proliferating booleans in metadata.
- Allowing GCP default application credentials to be used for bigquery access
- Adding missing requirements

Cachito emulation fixes

---

artcommon/artcommonlib/konflux/konflux_db.py
doozer/doozerlib/constants.py
pyartcd/pyartcd/pipelines/build_microshift_bootc.py

ref [thread](https://redhat-internal.slack.com/archives/GDBRP5YJH/p1739373251573739?thread_ts=1739372936.015079&cid=GDBRP5YJH)
Konflux needs images to be built to the default build repo in order for it to be released. But the microshift team has an additional requirement that it has to be synced to `quay.io/openshift-release-dev/ocp-v4.0-art-dev` as well

[konflux] build/sync microshift-bootc location

---

doozer/doozerlib/backend/konflux_client.py

To follow this change: https://github.com/openshift-priv/art-konflux-template/pull/46
We have the option to pass it as a param: https://github.com/konflux-ci/build-definitions/blob/main/task/buildah-remote-oci-ta/0.4/buildah-remote-oci-ta.yaml#L88

[konflux] explicitly pass cyclonedx

---

pyartcd/pyartcd/pipelines/build_microshift_bootc.py

To provide pull access to konflux build repo
Same logic as build sync: https://github.com/openshift-eng/art-tools/blob/29f04b71d7e8e1b5a2cbfd4901840de82917059e/doozer/doozerlib/cli/release_gen_payload.py#L883-L887

[konflux] fix bootc

---

doozer/doozerlib/backend/konflux_client.py

The default IBM VMs have only 2CPU, while the default for other arches are 4CPU. Ref [docs](https://konflux.pages.redhat.com/docs/users/getting-started/multi-platform-builds.html) 
Proposing to use linux-large variant by default, which has 4CPU, to see if it reduces build times and matches the builds of other arches.

[konflux] use bigger IBM VM flavors

---

doozer/doozerlib/cli/release_gen_payload.py

We had introduced a temporary permit for missing builds when syncing Konflux images. This was needed because not all components had available builds, as most of them had been garbage-collected and been failing to rebuild since then.
Now this should be fixed at least for 4.19, so re-introducing the constraint.

Fail build-sync for konflux in case of missing builds

---

doozer/doozerlib/cli/images_konflux.py
pyartcd/pyartcd/pipelines/olm_bundle_konflux.py

Current Konflux bundle build logic is using the
KonfluxDB.get_latest_build, which doesn't strictly follow how we find builds for assembly. Now after `metadata.get_latest_build` is implemented for Konflux, make a change to use that.
Also fixes finding latest bundles for an operator (implemented in _get_bundle_build_for).

Konflux: Use metadata.get_latest_build in bundle build

---

elliott/elliottlib/cli/find_builds_cli.py

Right now find-builds fails in dry-run mode because it tries to fetch cdn repos.
The cdn repos api endpoint fails if there are no docker images already attached 
for an advisory - which can be a common case when doing a dry-run.
So skip the api call.
Failed run: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fprepare-release/621/
Success run: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fprepare-release/622/console

Skip fetching cdn repos in dry-run mode

---

doozer/doozerlib/backend/konflux_client.py
doozer/doozerlib/backend/konflux_image_builder.py

PR https://github.com/openshift-eng/art-tools/pull/1292 breaks bundle build, because for bundle build` None` ImageMetadata is passed into KonfluxClient.start_pipeline_run_for_image_build.
Also there is a typo with parsing `network_mode` config option, which prevents hermetic build from being enabled.
This PR fixes both issues, and remove the reference of `ImageMetadata` from `KonfluxClient`, because it is designed not only for image build.

Fix bundle build error and hermetic build config

---

artcommon/artcommonlib/util.py
doozer/doozerlib/source_resolver.py
elliott/elliottlib/brew.py
pyartcd/pyartcd/pipelines/ocp4.py
pyartcd/pyartcd/pipelines/prepare_release.py

Similar to ocp4 job, adds `--data-path` and `--data-gitref` options to allow to override ocp-build-data fork and commit hash.
This also contains some other minor fixes/improvements.

prepare-release: Add options to use custom ocp-build-data

---

pyartcd/pyartcd/pipelines/prepare_release.py

fixes the bug of `None` being passed to doozer/elliott cmd invokes
seen in: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fprepare-release/641/console

Use correct params in cmd invoke

---

artcommon/artcommonlib/constants.py
artcommon/artcommonlib/konflux/konflux_build_record.py
artcommon/artcommonlib/konflux/konflux_db.py
doozer/doozerlib/backend/konflux_client.py
doozer/doozerlib/backend/konflux_image_builder.py
doozer/doozerlib/backend/konflux_olm_bundler.py

UI is broken and tekton results are too slow to be useful. Adding pod logs to Jenkins output and metrics that will help us find which tasks are failing during builds.

ART-12118: Add TaskRun outcome & timing to bigquery

---

elliott/elliottlib/cli/find_bugs_sweep_cli.py

filter out cve tracker bug from included bugs defined in `releases.yml`
executed the command from my local
```console
$ elliott --data-path https://github.com/openshift-eng/ocp-build-data.git --group openshift-4.18 --assembly 4.18.1 find-bugs:sweep --cve-only --report --output json
2025-02-24 19:28:06,221 artcommonlib INFO Konflux DB initialized
2025-02-24 19:28:06,221 artcommonlib INFO Cloning config data from https://github.com/openshift-eng/ocp-build-data.git
2025-02-24 19:28:06,226 art_tools.artcommonlib.exectools INFO $0: ['git', 'clone', '--no-single-branch', 'https://github.com/openshift-eng/ocp-build-data.git', '/var/folders/pk/ntb29tq142l2dm5899xcc4yh0000gn/T/elliott-k9813k8q.tmp/ocp-build-data'] - [cwd=None] [env={'GIT_SSH_COMMAND': 'ssh -oBatchMode=yes', 'GIT_TERMINAL_PROMPT': …
```

ART-12164 check cve tracker bug in included bug list

---

doozer/doozerlib/cli/release_gen_payload.py
pyartcd/pyartcd/pipelines/prepare_release.py

get version number out of an imagestream
makes only sense to merge after: https://github.com/openshift-eng/art-tools/pull/1301
Test prepare-release with these changes https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fprepare-release/618/console (dry-run!!!)

ART-9439 - modifications in prepare-release

---

doozer/doozerlib/backend/konflux_image_builder.py

SUPPORTED_ARCHES is defined here: https://github.com/openshift-eng/art-tools/blob/main/doozer/doozerlib/backend/konflux_client.py#L30, which seems to be the source of truth.

[konflux] remove unused code

---

doozer/doozerlib/backend/konflux_client.py

Konflux has max instances for each VM flavor defined [here](https://github.com/redhat-appstudio/infra-deployments/blob/main/components/multi-platform-controller/production-downstream/kflux-ocp-p01/host-config.yaml). For the ppc VM flavors, the max-instances are 30 each, for now. Since IBM has a resources limitation, we can't use just a single flavor, since during mass rebuilds, builds will be waiting for PPC ones to finish. So using a random function to unblock us for now, until we have a max-instance limit of 100

[konflux] random choice for ppc VM flavor

---

doozer/doozerlib/cli/rpms.py

Right now rpms in Konflux db have source_repo set to openshift-priv url.
It should instead use the public upstream url.
Also rely on object var which contains build commit instead of parsing specfile.
ref: https://github.com/openshift-eng/art-tools/blob/e7689d92bf2eea33c47f91aa8cf15e82a7ea3ae7/doozer/doozerlib/rpm_builder.py#L179-L180

Fix upstream url for rpms

---

artcommon/artcommonlib/konflux/konflux_db.py
artcommon/tests/test_konflux_db.py
doozer/doozerlib/cli/release_gen_payload.py

- teach `search_builds_by_fields()` how to do `WHERE name IN (value1, value2)
- by default, only search for builds in 'failure' or 'success' state

search_builds_by_fields(): match against multiple values

---

pyartcd/pyartcd/pipelines/build_sync.py

Currently all locks for build-sync reference `build-sync-konflux`. Fixing this for Brew builds

Fix lock name for Brew build-sync

---

doozer/doozerlib/cli/scan_sources_konflux.py
pyartcd/pyartcd/pipelines/ocp4_scan_konflux.py

Since PPC VMs on Konflux are not spawning correctly, disabling triggering builds temporarily until Konflux fixes are in. 
ref [thread](https://redhat-internal.slack.com/archives/C06Q309QUDV/p1740589236365859) for details

[konflux] disable ppc

---

doozer/doozerlib/cli/scan_sources_konflux.py
pyartcd/pyartcd/pipelines/ocp4_scan_konflux.py

Reverts openshift-eng/art-tools#1407

Revert "[konflux] disable ppc"

---

elliott/elliottlib/brew.py
elliott/elliottlib/cli/find_builds_cli.py

Because of the recent change of get_latest_build returning Model/MissingModel,
we want to check for bool(MissingModel)/False instead of None.

find-builds: Check for False instead of None

---

doozer/doozerlib/cli/release_gen_payload.py

Test is working: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fbuild-sync/15675
Honor the new konflux field defined in group config: https://github.com/openshift-eng/ocp-build-data/blob/openshift-4.19/group.yml#L39

konflux arches for konflux build-sync

---

doozer/doozerlib/backend/rebaser.py

`self._detect_package_managers(metadata, dest_dir)` is not smart enough to find the package managers if it does not exist in current directory.

[konflux] update cachito logic

---

artcommon/artcommonlib/metadata.py
elliott/elliottlib/brew.py
elliott/elliottlib/cli/find_builds_cli.py

- fix the issue that get_latest_build return empty model instead of the default value set in args
- for el_target should honor the config in component instead of the global config
- revert pr https://github.com/openshift-eng/art-tools/pull/1413 since it didn't fix the issue and raise error incorrectly when no build found we should silently exit

fix find builds issue

---

doozer/doozerlib/backend/konflux_client.py

For `prefetch-dependencies` the sbom type override param key is `sbom-type`. 
Ref: https://github.com/konflux-ci/build-definitions/blob/main/task/prefetch-dependencies/0.2/prefetch-dependencies.yaml#L48
Test build [succeeded](https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4-konflux/5667/console)

[konflux] update prefetch-dependencies sbom-type param

---

artcommon/artcommonlib/konflux/konflux_db.py
artcommon/artcommonlib/konflux/package_rpm_finder.py
doozer/doozerlib/build_info.py
doozer/doozerlib/cli/scan_sources_konflux.py

Test build: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4-scan-konflux/12812/console
scan-sources noticed a change in `libxml2` that's installed in `openshift-base-rhel9`, and marked that image for rebuild due to `PACKAGE_CHANGE`.
The workflow for finding outdated RPMs in a Konflux build is:
- fetch the `installed_packages` field from a Konflux build record in BigQuery; this is a list of Brew package builds, each one containing one or more RPMs
- for each installed package, call the `listBuildRPMs` Brew API to extract a list of RPMs
- compare each RPM with the most recent one in the enabled repos

[ART-11745] scan-sources scan for RPM changes

---

doozer/doozerlib/cli/images_health.py

Look at latest 90 days, as 30 could not be enough for slowly updating images and might result in unwanted pings.
Also, no need to filter builds in `PENDING` state as `search_builds_by_field()` is doing that in a smarter way:
```
if 'outcome' not in where:
base_clauses.append(Column('outcome', String).in_(['success', 'failure']))
```

images:health look back to latest 90 days

---

doozer/doozerlib/distgit.py

Locking osbs to `remote_sources_version: 1 `until a deprecation date is announced for cachito. Ideally it would land after 4.19 GA and we won't have to worry about it.
Docs: https://spaces.redhat.com/pages/viewpage.action?pageId=591269742

Set cachito as explicit default for osbs builds

---

doozer/doozerlib/backend/build_repo.py
doozer/doozerlib/backend/konflux_fbc.py
doozer/doozerlib/cli/__main__.py
doozer/doozerlib/cli/fbc.py
doozer/doozerlib/cli/images_konflux.py
doozer/doozerlib/constants.py
doozer/tests/backend/test_konflux_fbc.py

This verb is to rebase the art-fbc repo to include the bundles for the runtime assembly.
Test command:
```sh
doozer --group=openshift-4.18 --assembly=test --images=ose-metallb-operator --latest-parent-version beta:fbc:rebase --version=v4.18.0 --release=0.2 --message=test
```

Konflux: Add beta:fbc:rebase verb to rebase FBC

---

doozer/doozerlib/backend/konflux_client.py
doozer/doozerlib/backend/konflux_fbc.py
doozer/doozerlib/backend/konflux_olm_bundler.py
doozer/doozerlib/cli/__main__.py
doozer/doozerlib/cli/fbc.py
doozer/doozerlib/constants.py
doozer/tests/backend/test_konflux_fbc.py
doozer/tests/backend/test_konflux_olm_bundler.py

This verb is used to build File-based catalog (FBC) segments from the art-fbc repo. `beta:fbc:rebase` must be run before this command.
Requires https://github.com/openshift-eng/art-tools/pull/1364
Test command:
```sh
doozer --group=openshift-4.18 --assembly=stream --images=ose-metallb-operator --latest-parent-version beta:fbc:build --konflux-kubeconfig=/path/to/config-konflux-prod --konflux-namespace=ocp-art-tenant --skip-checks
```
Note: `--skip-test` is to instruct the Konflux pipeline to skip validations. Those validations are expected to fail if any of bundles, operators, or operands are not shipped live.
Test build on jenkins: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/hack/job/yuxzhu/job/aos-cd-builds/job/build%252Fbuild-fbc/15/console

Add beta:fbc:build verb to build FBC segments

---

artcommon/artcommonlib/konflux/konflux_db.py
doozer/doozerlib/backend/konflux_client.py
doozer/doozerlib/backend/konflux_image_builder.py
doozer/doozerlib/cli/images_konflux.py
elliott/elliottlib/cli/__main__.py
elliott/elliottlib/cli/find_konflux_builds_cli.py
elliott/elliottlib/cli/snapshot_cli.py
elliott/functional_tests/test_snapshot.py
elliott/tests/test_snapshot_cli.py

Needs https://github.com/openshift-eng/art-tools/pull/1408 
```
$ elliott -g openshift-4.18 snapshot new sriov-network-operator-v4.18.0-202502251712.p0.gf496851.assembly.stream.el9 
--konflux-kubeconfig=~/konflux.kubeconfig.priv
--apply
...
2025-02-25 20:55:53,511 art_tools.elliottlib.cli.release_snapshot_cli INFO Validating given NVRs...
2025-02-25 20:55:53,511 art_tools.elliottlib.cli.release_snapshot_cli INFO Fetching NVRs from DB...
2025-02-25 20:55:55,000 art_tools.artcommonlib.exectools INFO Executing:cmd_gather_async: oc image info -o json --registry-config=/tmp/_doozer_fwmb7qli --filter-by-os=amd64 quay.io/redhat-user-workloads/ocp-art-tenant/art-images:ose-sriov-network-rhel9-operator-v4.18.0-20250225.171216
2025-02-25 20:55:56,961 doozerlib.backend.konflux_client INFO Creating …
```

ART-12049 Elliott can create Konflux Snapshots

---

doozer/doozerlib/cli/scan_sources_konflux.py

**TO BE REVERTED!!!**
Temporarily disable konflux rebuilds on config changes. Some images are continuously being rebuilt, so something might be wrong with our metadata configuration check. Disabling it until we assess the problem

[temp][konflux] disable rebuilds on config changes

---

pyartcd/pyartcd/__main__.py
pyartcd/pyartcd/constants.py
pyartcd/pyartcd/pipelines/build_fbc.py

This job uses `doozer beta:fbc:rebase` and `doozer beta:fbc:build` to build file-based catalog (FBC) segments for OLM operators.
Requires: https://github.com/openshift-eng/art-tools/pull/1364 and https://github.com/openshift-eng/art-tools/pull/1403
Test pipeline run: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/hack/job/yuxzhu/job/aos-cd-builds/job/build%252Fbuild-fbc/15/console

pyartcd: Add build-fbc job to rebase and build FBC

---

pyartcd/pyartcd/__main__.py
pyartcd/pyartcd/pipelines/fbc_import_from_index.py

This job uses `doozer beta:fbc:import` to import FBC objects from published operator index into art-fbc repo.
Requires https://github.com/openshift-eng/art-tools/pull/1391
Test job run: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/hack/job/yuxzhu/job/aos-cd-builds/job/build%252Ffbc-import-from-index/9/
For the result, look at "art-*" branches in https://github.com/openshift-priv/art-fbc

pyartcd: Add fbc-import-from-index job

---

doozer/doozerlib/backend/rebaser.py
doozer/doozerlib/cli/scan_sources_konflux.py
doozer/doozerlib/image.py

`scan-sources` and 'images:rebase` compute image config digest at different times; the latter happens after merging the `konflux` config stanza into the main config, and this alters the result. As a consequence, we were continuously finding reasons to rebuild images because the digest computed by scan-sources did not match what we had pushed upstream. 
Moving the config merge inside the function that computes the digest will ensure consistent results across pipelines.
Test build: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4-scan-konflux/12930/console

Fix scan-sources config changes check

---

pyartcd/pyartcd/jenkins.py

Sometimes fetching build/builds would timeout since default is 10 seconds,
increase it to 60 seconds. 
Run: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/maintenance/job/maintenance%252Fcleanup-locks/34863/parameters/

Increase jenkins client timeout

---

doozer/doozerlib/backend/rebaser.py

We had stopped adding `-container` to image names recently, but while searching through the brew database, we need to search with that suffix.
Fixes error
```
doozerlib.cli.images_konflux ERROR Failed to rebase cluster-nfd-operator: No brew package is defined for cluster-nfd-operator
```
https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4-konflux/5900/console

[konflux] add -container while searching for brew builds

---

doozer/doozerlib/backend/konflux_fbc.py
doozer/doozerlib/opm.py
doozer/tests/test_opm.py

Follow up https://github.com/openshift-eng/art-tools/pull/1437,
`opm alpha render-template` also needs registry credentials.
Tested with https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/hack/job/yuxzhu/job/aos-cd-builds/job/build%252Ffbc-import-from-index/18/

Doozer: Additional auth fix for FBC import

---

artcommon/artcommonlib/util.py
artcommon/tests/test_cachito.py
doozer/doozerlib/backend/konflux_client.py
doozer/doozerlib/backend/konflux_image_builder.py
doozer/doozerlib/backend/rebaser.py
doozer/tests/backend/test_konflux_cachi2.py

pre-fetch is the first step towards hermetic builds. The pre-fetch dependencies konflux task uses cachi2 to get the required packages and make it available to the hermetic build. Right now, we can enable pre-fetch without enabling hermetic to make sure that all images work with cachi2. If not, we need to work with upstream image owners to make changes to their repos.
image config `konflux.cachi2.enabled` > group config `konflux.cachi2.enabled` > cachito enabled/disabled
Ticket: https://issues.redhat.com/browse/ART-11902

[ART-11902] konflux prefetch support

---

artcommon/artcommonlib/konflux/package_rpm_finder.py
doozer/doozerlib/assembly_inspector.py
doozer/doozerlib/build_info.py
doozer/doozerlib/cli/release_gen_payload.py
doozer/doozerlib/cli/scan_sources_konflux.py
doozer/tests/cli/test_gen_payload.py
doozer/tests/test_assembly_inspector.py

Re-enabling these checks in Konflux gen-payload:
- detect_non_latest_rpms
- detect_inconsistent_images
- detect_installed_rpms_issues
Test build: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fbuild-sync/16020

[konflux] build-sync: re-enable a few assembly issues checks

---

elliott/elliottlib/cli/snapshot_cli.py
elliott/functional_tests/test_snapshot.py
elliott/tests/test_snapshot_cli.py

Get NVRs from a Konflux snapshot and validate them in the DB.
This will enable to inspect a Snapshot at various points in our release pipeline
`elliott -g openshift-4.18 snapshot get ose-4-18-202503121723`

elliott snapshot get

---

doozer/doozerlib/backend/rebaser.py
doozer/tests/backend/test_rebaser.py

follows https://github.com/openshift-eng/art-tools/pull/1452
since `metadata.config.final_stage_user` is defined without the `USER` perfix

[konflux] Fix final stage user bug

---

artcommon/artcommonlib/konflux/konflux_db.py

Do not unecessarily warn about unfound builds

Do not warn about unfound builds

---

pyartcd/pyartcd/pipelines/ocp4_konflux.py

Test build: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fbuild-sync/16409/
Updated multi is:
```
$ oc -n ocp-multi get is 4.19-konflux-art-latest-multi
NAME                            IMAGE REPOSITORY                                                    TAGS                                       UPDATED
4.19-konflux-art-latest-multi   registry.ci.openshift.org/ocp-multi/4.19-konflux-art-latest-multi   4.19.0-0.nightly-multi-2025-03-27-090653   2 hours ago
```

[konflux] sync multiarch payloads

---

doozer/doozerlib/backend/build_repo.py
doozer/doozerlib/backend/rebaser.py

`hypershift` image has a .gitignore file that needs to be present after rebase, in konflux. Usually its removed before rebase to make sure that files/folders that doozer generates are not excluded by git.

[konflux] use force for git add

---

doozer/doozerlib/backend/rebaser.py

go versions defined like https://github.com/openshift/prometheus-alertmanager/blob/release-4.18/go.mod#L3 is breaking konflux prefetch task. i.e. the go version has to be defined as `1.22.0` instead of `1.22`.
Since there are 20+ images with this issue, for more than one OCP version, updating our automation to fix it.
Successfully rebased file: https://github.com/openshift-priv/image-customization-controller/blob/art-openshift-4.18-assembly-stream-dgk-ose-image-customization-controller/go.mod#L3
Successful prefetch: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4-konflux/6683/

[konflux] append .0 for go version

---

doozer/doozerlib/backend/rebaser.py

Rolls back https://github.com/openshift-eng/art-tools/pull/1480 and its follow up PR

[konflux] rollback gomod patch

---

doozer/doozerlib/cli/fbc.py
doozer/doozerlib/constants.py

Due to a limitation in Konflux, FBC artifacts must be pushed to a public quay repo (instead of the private art-images repo). Making this change shouldn't cause any security concerns since FBC only includes metadata.

build-fbc: Push to a dedicated quay repo

---

artcommon/artcommonlib/exectools.py
artcommon/artcommonlib/lock.py
doozer/doozerlib/backend/konflux_client.py
doozer/doozerlib/backend/konflux_image_builder.py
elliott/elliottlib/cli/pin_builds_cli.py
elliott/tests/test_pin_builds_cli.py

Summary
- Pin rhcos at the right level
- flake8 fixes (7.2.0)
```
uv run -m flake8
./artcommon/artcommonlib/exectools.py:168:5: F824 `global cmd_counter_lock` is unused: name is never assigned in scope
./artcommon/artcommonlib/lock.py:23:5: F824 `global _NAMED_SEMAPHORES` is unused: name is never assigned in scope
./doozer/doozerlib/backend/konflux_client.py:563:13: F824 `nonlocal overall_timeout_timedelta` is unused: name is never assigned in scope
./doozer/doozerlib/backend/konflux_client.py:749:13: F824 `nonlocal overall_timeout_timedelta` is unused: name is never assigned in scope
./doozer/doozerlib/backend/konflux_image_builder.py:558:25: F824 `nonlocal containers_info` is unused: name is never assigned in scope
```

Pin rhcos at the right level

---

doozer/doozerlib/backend/konflux_client.py
doozer/tests/backend/test_konflux_client.py

URL has changed from 
```
https://konflux.apps.kflux-ocp-p01.7ayg.p1.openshiftapps.com/application-pipeline/workspaces/ocp-art/applications/openshift-4-19/pipelineruns/ose-4-19-ose-ovn-kubernetes-6wv6l
```
to 
```
https://konflux-ui.apps.kflux-ocp-p01.7ayg.p1.openshiftapps.com/ns/ocp-art-tenant/applications/openshift-4-19/pipelineruns/ose-4-19-ose-ovn-kubernetes-6wv6l
```

[konflux] update UI url generation

---

pyartcd/pyartcd/pipelines/quay_doomsday_backup.py

We are producing only x86_64 for both 4.12 and 4.13. 
Fixes errors like [this](https://redhat-internal.slack.com/archives/C03JYDGPX8F/p1743723045279199?thread_ts=1743723039.998309&cid=C03JYDGPX8F)

Sync only x86_64 for 4.12 and 4.13

---

pyartcd/pyartcd/pipelines/build_sync.py
pyartcd/pyartcd/util.py

Only build Konflux enabled arches. Test build: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fbuild-sync-konflux/12/console

[konflux] build-sync: look at konflux arches in group config

---

doozer/doozerlib/backend/konflux_client.py

We need to remove the SAST tasks from `obj["spec"]["pipelineSpec"]["tasks"]` instead of `obj["spec"]["params"]`

[konflux] fix sast bug

---

art-cluster/pipelines/data/project/art-cd/image/Containerfile.base

`check-payload` newly requires `go >= 1.23.0` which causes our art-cd builds to fail (such as [this](https://console-openshift-console.apps.artc2023.pc3z.p1.openshiftapps.com/k8s/ns/art-cd/builds/art-cd-update-802))
~~Manually install go 1.23.0 because this version of go is not yet available for ubi9. We can go back to installing it with `dnf` once it's available~~
Use the CI golang 1.23 builder image instead of ubi9 to get golang 1.23

Manually install golang 1.23.0

---

doozer/doozerlib/backend/konflux_fbc.py

name: Use `<distgit_key>-fbc` instead of the bundle name.
image_pullspec: Reference by sha256 digest
image_tag: Use tag instead of sha256 digest (following up https://github.com/openshift/art-tools/issues/1434)

Konflux: Change how FBC build record is stored

---

pyartcd/pyartcd/pipelines/quay_doomsday_backup.py

This PR brings back Slack reporting logic of the `quay-doomsday-backup` pipeline which was removed in https://github.com/openshift-eng/art-tools/pull/1516.
To achieve this without major changes, this PR makes the functions async again and nearly identical to how they were before https://github.com/openshift-eng/art-tools/pull/1516. The only difference are [these lines](https://github.com/adobes1/art-tools/blob/73f047be1dafca95d1a61e552cce45c3f3f6f279/pyartcd/pyartcd/pipelines/quay_doomsday_backup.py#L93-L96) which run the synchronization process for each arch in sequence - this is done to hopefully fix Quay returning 502 when calling `oc adm release mirror ...` ([example](https://console-openshift-console.apps.artc2023.pc3z.p1.openshiftapps.com/k8s/ns/art-cd/tekton.dev~v1~PipelineRun/dooms …

Bring back Slack reporting to quay-doomsday-backup

---

doozer/doozerlib/backend/konflux_fbc.py

Add `com.redhat.art.nvr` label to FBC artifacts. This label will be used by the shipment pipeline to determine the NVR of the FBC artifacts.

[Konflux] Add NVR label to FBC artifacts

---

doozer/doozerlib/backend/rebaser.py

Follows https://github.com/openshift-eng/art-tools/pull/1523
We only need to add the `.0` suffix if the go version is >= 1.22

[konflux] go version patch only for 1.22+

---

pyartcd/pyartcd/pipelines/quay_doomsday_backup.py

Previously, the workspace dir would be cleaned only if the sync of the specific arch to s3 succeeded.
Move the cleanup into finally block to always clean it.

Always clean the doomsday pipeline workspace no matter the result

---

artcommon/artcommonlib/model.py

To let us slice ListModel objects, as in `sublist = list_model_obj[:N]`

Enable ListModel slicing

---

pyartcd/pyartcd/pipelines/ocp4.py

When we specify the build plan `all` the pipeline should not error out with `No images to build according to current build plan`, like its happening here: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4/17237/
Seems to have triggered correctly: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4/17259/console

ocp4 build all fix

---

doozer/doozerlib/backend/konflux_fbc.py
doozer/tests/backend/test_konflux_fbc.py

Currently EC policies verify if all related images in the FBC artifacts have valid pullspecs. However, at the time when ART builds an FBC artifacts, the operator is not yet released. Therefore EC compliants the pullspecs can't be pulled.
This PR will create an ImageDigestMirrorSet file for EC to pull from our art-images build registry instead and eventually make EC happy. See https://konflux.pages.redhat.com/docs/users/patterns/maintaining-references-before-release.html for references.

[Konflux] Create ImageDigestMirrorSet for FBC EC verification

---

doozer/doozerlib/backend/konflux_client.py

Follow up to https://github.com/openshift-eng/art-tools/pull/1547
https://issues.redhat.com/browse/KONFLUX-7956 has been setup i.e. which means that we need to use the per component SA, which is updated as part of the PR

konflux SA override update

---

doozer/doozerlib/cli/release_gen_payload.py

Quay throws occasionally more 502s than current retry can handle

Bump retries for multi payload creation

---

doozer/doozerlib/cli/scan_sources_konflux.py
doozer/doozerlib/metadata.py

We have two network modes that we care about, `hermetic` and `open`. Rebuild if the value changes in the config
Test build succeeded: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4-scan-konflux/17557/console

scan sources rebuild if hermetic

---

doozer/doozerlib/cli/scan_sources_konflux.py

Currently breaking scan-sources:
```
ChildProcessError: Process ['cosign', 'download', 'attestation', 'quay.io/redhat-user-workloads/ocp-art-tenant/art-images@sha256:39599c3f255239e2e8f072af35f041511a75abf80149b2a0bef6a5715fbf62b4', '--registry-username', ****, '--registry-password', ****] exited with code 1.
```

Disable scan_network_mode_changes()

---

artcommon/artcommonlib/assembly.py
artcommon/artcommonlib/konflux/konflux_build_record.py
artcommon/artcommonlib/konflux/konflux_db.py
artcommon/artcommonlib/konflux/package_rpm_finder.py
artcommon/artcommonlib/metadata.py
artcommon/tests/test_konflux_db.py
doozer/doozerlib/brew.py
doozer/doozerlib/cli/release_gen_payload.py
doozer/doozerlib/metadata.py
doozer/doozerlib/runtime.py
doozer/doozerlib/util.py
doozer/requirements.txt
doozer/tests/cli/test_gen_payload.py
doozer/tests/cli/test_rpms_build.py
doozer/tests/test_osbs2.py
doozer/tests/test_rpmcfg.py

Test build: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/hack/job/dpaolell/job/build-sync-konflux/7/console
Create imagestreams:
- `4.18-konflux-art-assembly-4.18.100`
- `4.18-konflux-art-assembly-4.18.100-multi`
- `4.18-konflux-art-assembly-4.18.100-s390x`
- `4.18-konflux-art-assembly-4.18.100-ppc64le`
- `4.18-konflux-art-assembly-4.18.100-arm64`

[konflux] gen-payload for named assemblies

---

elliott/elliottlib/cli/find_builds_cli.py
elliott/tests/test_find_builds_cli.py

Test:
```yaml
releases:
4.18.100:
assembly:
basis:
reference_releases:
aarch64: 4.18.0-0.konflux-nightly-arm64-2025-04-24-065555
x86_64: 4.18.0-0.konflux-nightly-2025-04-24-065624
time: 2025-04-24 05:59:34+00:00
...
```
Works with pinned builds as well
```
elliott --group openshift-4.18 --assembly 4.18.100 --build-system konflux --data-path .
./ocp-build-data find-builds -k image --non-payload
2025-05-06 16:29:44,008 artcommonlib INFO Konflux DB initialized 
2025-05-06 16:29:44,087 art_tools.artcommonlib.exectools INFO $0: ['git', '-C', '/home/sid/Projects/art/ocp-build-data', 'remote', 'get-url', 'origin'] - [cwd=None]: Executing:cmd_gather: git -C /home/sid/Projects/art/ocp-build-data remote get-url origin
2025-05-06 16:29:44,093 art_tools.artcommonlib.exectools INFO $1: ['git', '-C', …
```

Enable find-builds for konflux

---

doozer/doozerlib/backend/rebaser.py
doozer/doozerlib/constants.py
doozer/tests/backend/test_rebaser.py

Keep temporary files under `/tmp/art` and clean up at the end

OCPBUGS-55823: clean up temporary files

---

artcommon/artcommonlib/gitdata.py
elliott/elliottlib/cli/shipment_cli.py
elliott/elliottlib/runtime.py

This is to have default RP's set per application in shipment-data repo
Test:
https://gitlab.cee.redhat.com/hybrid-platforms/art/ocp-shipment-data/-/merge_requests/20
```
$ elliott -g openshift-4.18 --assembly 4.18.3 --shipment-path https://gitlab.cee.red
hat.com/sidsharm/ocp-shipment-data@add_config shipment init --advisory-key image
...
shipment:
metadata:
product: ocp
application: openshift-4-18
group: openshift-4.18
assembly: 4.18.3
fbc: false
environments:
stage:
releasePlan: ocp-art-advisory-stage-4-18
prod:
releasePlan: ocp-art-advisory-prod-4-18
snapshot:
name: test-snapshot
spec:
nvrs: []
...
```

Enable defaults for shipment config init

---

elliott/elliottlib/cli/find_bugs_sweep_cli.py
elliott/tests/test_find_bugs_sweep_cli.py

This is in preparation for returning structured json output in the find-bugs:sweep command,
which will be used in the prepare-release-konflux pipeline to prepare shipment.
Removing bugzilla in sweep will remove complexity and branching when dumping output.
Bugzilla is deprecated inside RedHat for filing normal bugs, and is only used for cve bugs only.
So it should be safe to remove from find-bugs:sweep

Deprecate bugzilla in bug sweep

---

artcommon/artcommonlib/util.py
doozer/doozerlib/backend/konflux_image_builder.py
doozer/doozerlib/cli/scan_sources_konflux.py

Looks like there is a 1-3 second delay from when the PLR completes and the attestation is created.
`@retry(reraise=True, wait=wait_fixed(10), stop=stop_after_attempt(3))` can retry it after 10 seconds, but the subcommand needs to raise an exception first

[konflux] slsa attestation raise exception

---

artcommon/requirements.txt

`future` is getting installed somewhere else, but artcommonlib needs it and this is breaking art-build-history that only install artcommon requirements

Add future to artcommon requirements

---

doozer/doozerlib/backend/konflux_image_builder.py

[libreswan-5.2-1.el9fdp](https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=3562713) is being stored in the database as `libreswan-5.2-1.el9fd` in the database (https://art-build-history-art-build-history.apps.artc2023.pc3z.p1.openshiftapps.com/build?nvr=ose-ovn-kubernetes-v4.20.0-202505090050.p2.g4789689.assembly.stream.el9&outcome=success). i.e. the `p` at the end of the NVR is missing.
Seems like its cause of the `rstrip` method
```
> print("libreswan-5.2-1.el9fdp.src.rpm".rstrip(".src.rpm"))
libreswan-5.2-1.el9fd
```

use split instead of strip

---

elliott/elliottlib/cli/attach_cve_flaws_cli.py
elliott/elliottlib/cli/create_cli.py
elliott/elliottlib/cli/shipment_cli.py
elliott/elliottlib/runtime.py
elliott/elliottlib/util.py
elliott/tests/test_create_cli.py
elliott/tests/test_runtime.py

For https://github.com/openshift-eng/ocp-build-data/pull/6706
In this PR:
- Store the template thats common to all OCP versions in openshift-eng/ocp-build-data#main
- The config can be overridden in the group level, if necessary
- As a first step, use the updated template. Follow up features include (updating the description to include the advisory id, adding the SHAs for the release digest)

ART-12761: docs workflow update

---

artcommon/artcommonlib/rhcos.py

Add support for layered rhcos image,
the brew build name follow the format rhcos-$arch-$ocp_major.$ocp_minor.$rhel_major.$rhel_minor.$timestamp-0
test with https://errata.devel.redhat.com/advisory/144055#c443

ART-12702 support new rhcos build name

---

artcommon/artcommonlib/constants.py
doozer/doozerlib/cli/release_gen_payload.py
doozer/doozerlib/constants.py
pyartcd/pyartcd/pipelines/build_sync.py
pyartcd/pyartcd/pipelines/ocp4.py

For 4.20, sync konflux builds to the default image stream `4.20-art-latest`

Sync konflux builds to default imagestream for 4.20

---

elliott/elliottlib/shipment_model.py
ocp-build-data-validator/validator/json_schemas/shipment.schema.json

https://issues.redhat.com/browse/RELEASE-1535 requires live_id field to be set in releaseNotes

ART-12592 Set live_id in shipment release notes

---

doozer/doozerlib/cli/images.py
pyartcd/pyartcd/pipelines/ocp4.py

`ocp4` should not crash on rebase failures; it should rather exclude the failed images from the build plan and continue.
Test build: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4/18167/console

Fix ocp4 on rebase errors

---

doozer/doozerlib/backend/konflux_client.py
doozer/doozerlib/backend/konflux_image_builder.py

https://github.com/openshift-eng/art-tools/pull/1527/ introduced a new parameter `metadata` to
`KonfluxClient.start_pipeline_run_for_image_build`, which breaks Konflux bundle and FBC build. This PR fixes the issue by replacing that parameter with an optional parameter.

[Konflux] Fix Konflux bundle and FBC build

---

elliott/elliottlib/cli/konflux_release_cli.py
elliott/tests/test_konflux_release_cli.py

Unless the application name is not present in labels, the Release won't show up in the Konflux UI: https://konflux-ui.apps.kflux-ocp-p01.7ayg.p1.openshiftapps.com/ns/ocp-art-tenant/applications/openshift-4-19/releases

Application label in Release

---

elliott/elliottlib/cli/find_bugs_sweep_cli.py
elliott/elliottlib/cli/verify_attached_bugs_cli.py
elliott/tests/test_verify_attached_bugs_cli.py

Fixes the following error:
```
Error validating attached bugs: categorize_bugs_by_type() missing 3 required positional arguments: 'noop', 'major_version', and 'minor_version'
2025-05-15 15:01:04,888 pyartcd      WARNING Error verifying attached bugs: Process ['elliott', '--assembly=4.17.30', '--group=openshift-4.17', 'verify-attached-bugs', '--verify-flaws'] exited with code 1.
2025-05-15 15:01:04,888 pyartcd      ERROR Process ['elliott', '--assembly=4.17.30', '--group=openshift-4.17', 'verify-attached-bugs', '--verify-flaws'] exited with code 1.
File "/mnt/jenkins-workspace/_builds_build_promote-assembly_2@2/art-tools/pyartcd/pyartcd/pipelines/promote.py", line 342, in run
justification = self._reraise_if_not_permitted(err, "ATTACHED_BUGS", permits) …
```

added missing arguments for categorize_bugs_by_type

---

elliott/elliottlib/bzutil.py

This PR makes it possible to override pscomponent with `art:pscomponent:` label for new stype CVE trackers.

Elliott: Respect `art:pscomponent:` label for new style trackers

---

elliott/elliottlib/cli/find_builds_cli.py
elliott/elliottlib/errata_async.py

Test
```
$ elliott -g openshift-4.17 find-builds --attach 149789 --kind image --build rhcos-aarch
64-417.94.202505140130-0 --build ose-route-controller-manager-container-v4.17.0-202505140543.p0.g02bbf80.assembly.stream.el9
No new builds found for attaching to advisory
```

ART-12941 Correctly fetch attached builds and filter

---

pyartcd/pyartcd/pipelines/build_microshift.py

The release specific boilerplates were removed for versions 4.16 and down. This was causing an error in the microshift build pipeline. 
```
ERROR: failed shell command: artcd -v --working-dir=./artcd_worki...-g openshift-4.15 --assembly 4.15.51
with rc=1 and output:
[...see full archive #5...]
~~~~~~~^^^^^^^^^^^^^^^^
File "/mnt/jenkins-workspace/_builds_build_build-microshift_2@2/art-venv/lib64/python3.11/site-packages/ruamel/yaml/comments.py", line 853, in __getitem__
return ordereddict.__getitem__(self, key)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'boilerplates'
Finished: FAILURE
```
I worked around this by leveraging some of the elliottlib code to load the default boilerplate from main but I think this could probably use a larger refactor at some point. This could be shared code …

Fix build microshift

---

elliott/elliottlib/shipment_model.py
elliott/tests/test_konflux_release_cli.py
ocp-build-data-validator/validator/json_schemas/shipment.schema.json

Issues should not be set to `issues: {}` if the field is not populated from the shipment config. It should be omitted instead.
Ref thread: https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1747402808869269?thread_ts=1747343024.598559&cid=C04PZ7H0VA8
The mandatory fields are defined here: https://github.com/konflux-ci/release-service-catalog/blob/development/schema/dataKeys.json#L673, everything else should be omitted, if they don't have a value.

shipment pipeline update

---

doozer/doozerlib/backend/konflux_client.py
doozer/doozerlib/backend/konflux_olm_bundler.py
doozer/tests/backend/test_konflux_olm_bundler.py

After the recent bump of Tekton templates for bundle build (https://github.com/openshift-priv/art-konflux-template/pull/95), we got an build error due to the existance of container.yaml. e.g.
https://konflux-ui.apps.kflux-ocp-p01.7ayg.p1.openshiftapps.com/ns/ocp-art-tenant/applications/openshift-4-18/pipelineruns/openshift-4-18-openshift-kubernetes-nmstate-operator-bundl68fzn.
This file is only used in Brew/OSBS build. Removing it will resolve the build error. 
Another error is similar to
https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1747396281747099.
Applying artifact_type="operatorbundle" will solve the issue.
Test build: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Folm_bundle_konflux/1953/

Konflux: Fix bundle build again

---

doozer/doozerlib/build_info.py

We overrode enabled repos for DTK in 4.19/4.20, but scan-sources is not looking at the Konflux specific config

[konflux] scan-sources: look at konflux enabled repos if defined

---

doozer/doozerlib/build_info.py
doozer/doozerlib/cli/scan_sources_konflux.py

Follows https://github.com/openshift-eng/art-tools/pull/1626 with a more robust approach

[konflux] scan-sources: merge Konflux config if present before scan

---

doozer/doozerlib/backend/konflux_client.py
doozer/doozerlib/backend/konflux_image_builder.py

Migrate sbom type from `cyclonedx` to `spdx` since Konflux has updated their default to the latter.

ART-12117: migrate sbom type from cyclonedx to spdx

---

doozer/doozerlib/backend/konflux_olm_bundler.py
doozer/tests/backend/test_konflux_olm_bundler.py

https://github.com/openshift-eng/art-tools/pull/1596 missed `operator_nvr` field in `events.bundles` table, which breaks recent FBC builds.

Bring back -container suffix in bundle build records

---

doozer/doozerlib/backend/konflux_olm_bundler.py

https://github.com/openshift-eng/art-tools/pull/1625 introduced an issue that the build repo urls are https urls instead of ssh, which broke bundle rebase.

[Konflux] Fix rebase error in bundle build

---

doozer/doozerlib/cli/scan_fips.py

`doozer images:scan-fips` is failing for openshift-4.12 and openshift-4.13 because the tags it retrieves from `erratatool.yml` are incorrectly formatted:
```
koji.GenericError: No such tagInfo: 'rhaos-{MAJOR}.{MINOR}-rhel-8-candidate'
```
This is because `erratatool.yml` in these two versions now contains advisory boilerplate - this contains `{PATCH}` variable which is not defined anywhere in `group.yml` and so `runtime.gitdata.load_data()` fails to replace any vars.

Fix brew tag retrieval in doozer images:scan-fips

---

doozer/doozerlib/cli/release_gen_assembly.py

- `print(yaml.dump)` erroneously prints the return value of `dump`, which broke artcd at the time it loads back the report
- `yaml.width = 4096` prevents Ruamel YAML from splitting simple `key: value` entries on multiple lines, if the string is long

gen-assembly: fix yaml dump

---

artcommon/artcommonlib/konflux/konflux_build_record.py
artcommon/artcommonlib/konflux/konflux_db.py
artcommon/tests/test_konflux_db.py

Querying is (silently) broken right now, because a new field was added in DB table, but not in code.
```
TypeError: KonfluxBuildRecord.__init__() got an unexpected keyword argument 'hermetic'
```

Add hermetic field in DB record

---

doozer/doozerlib/cli/release_gen_assembly.py
pyartcd/pyartcd/pipelines/gen_assembly.py

For 4.20 for example, we are syncing konflux builds to formerly brew imagestreams. So we need to look at the usual nightly URLs instead.
Follows: https://github.com/openshift-eng/art-tools/pull/1609

imagestream override konflux

---

artcommon/artcommonlib/assembly.py
artcommon/tests/test_assembly.py
doozer/tests/backend/test_rebaser.py
elliott/elliottlib/cli/find_builds_cli.py
elliott/elliottlib/errata_async.py
elliott/elliottlib/shipment_model.py
ocp-build-data-validator/validator/json_schemas/assembly_basis.schema.json
ocp-build-data-validator/validator/json_schemas/assembly_group_config.schema.json
pyartcd/config.example.toml
pyartcd/pyartcd/__main__.py
pyartcd/pyartcd/git.py
pyartcd/pyartcd/pipelines/prepare_release_konflux.py
pyartcd/requirements.txt
pyartcd/tests/pipelines/test_prepare_release_konflux.py

Links
- Job run: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/hack/job/sidsharm-aos-cd-jobs/job/build%252Fprepare-release-konflux/48/console
- Test assembly config: https://github.com/thegreyd/ocp-build-data/blob/418_shipment_Test/releases.yml
- Created MR: https://gitlab.cee.redhat.com/sidsharm/ocp-shipment-data/-/merge_requests/6
TODOs:
- Any project with visibility=public in gitlab should be cloneable
- Created and using a new access token for hybrid-platforms/art/ocp-shipment-data
- Credentials stored in bitwarden
- shipment is a single object with "url", "advisories" and "env" keys. a shipment MR can have multiple advisories defined, which have kind and live_id keys.
- for an existing open shipment MR - pipeline can work on it idempotently - making sure all …

ART-12697 Add prepare-release-konflux pipeline

---

artcommon/artcommonlib/assembly.py
doozer/doozerlib/cli/release_gen_payload.py

- `assembly.basis.time` is now a string, and needs to be converted back into a `datetime` object
- for 4.20 we're syncing out Konflux builds to standard nightlies, so we need to remove the `-konflux` suffix in the pullspec

Adjust build-sync for Konflux

---

pyartcd/pyartcd/pipelines/ocp4.py
pyartcd/pyartcd/pipelines/ocp4_scan.py
pyartcd/pyartcd/util.py
pyartcd/tests/pipelines/test_ocp4.py

Right now, the incorrect rhcos job gets triggered for 4.19. instead of hardcoding values, check group config.
https://redhat-internal.slack.com/archives/GDBRP5YJH/p1748616572132659
Test: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4/18876/console
```
2025-05-30 18:35:46,239 pyartcd      INFO Layered RHCOS  enabled for 4.19
2025-05-30 18:35:46,239 pyartcd      INFO Would have triggered job: rhcos for 4.19, job_name=build-node-image
```

Check group config for determining rhcos job name

---

pyartcd/pyartcd/jenkins.py
pyartcd/pyartcd/pipelines/ocp4.py
pyartcd/pyartcd/pipelines/ocp4_konflux.py

After moving plashets building to their own job, we can trigger repo updates from both OSBS and Konflux builds. With this PR we shall trigger plashets from `ocp4-konflux` pipelines for those versions that we're syncing out to the regular imagestreams (currently, only 4.20). This will allow a smoother migration towards Konflux without having to worry about over building plashets.
Ref. [ART-13009](https://issues.redhat.com/browse/ART-13009)
Needs https://github.com/openshift-eng/aos-cd-jobs/pull/4408

ART-13009 Avoid duplicating plashet builds

---

ocp-build-data-validator/tests/test_releases.py
ocp-build-data-validator/validator/__main__.py
ocp-build-data-validator/validator/releases.py

Add check to ocp-build-data-validator to ensure that the `upgrades` field in `releases.yml` does not contain references to itself.
If there's self-referential entry, displays the following error:
```
validator.exceptions.ValidationFailed: releases.yml validation failed
Returned error: The following releases contain references to themselves in their respective 'upgrades': 4.18.14, 4.18.13, rc.1, ec.1
```

ART-13075: Add check for self-referential upgrades

---

doozer/doozerlib/cli/get_nightlies.py

get nightly used to assume entry in pullspec with empty commitid is rhcos
but layered rhcos in 4.20 has commitid, change the method the check rhel-coreos in name

fix rhcos check in get nightly

---

pyartcd/pyartcd/pipelines/build_plashets.py

To make sure that they are integers. Since self.version is a string
```
> "1" == 1
False
```
Till now the code had been short circuiting and the rhcos job had been triggering in layered rhcos mode, which is undesired.

fix rhcos version data type

---

elliott/tests/test_find_builds_cli.py
elliott/tests/test_konflux_release_cli.py
elliott/tests/test_snapshot_cli.py

Replace AsyncMock with MagicMock for the verify_connection method in tests to simplify the mocking behavior. Adjust related test cases to ensure compatibility with the new mocking approach.
Related to https://github.com/openshift-eng/art-tools/pull/1680

Refactor tests to use MagicMock instead of AsyncMock for verify_connection

---

artcommon/artcommonlib/rhcos.py
doozer/doozerlib/cli/inspect_stream.py
doozer/doozerlib/rhcos.py

Fix for the error when `AssemblyInspector.get_rhcos_build()` is invoked for named assemblies. This error can be seen at several places:
- build-sync / doozer release:gen-payload: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fbuild-sync/20529
- `doozer --assembly=4.19.0 --data-path=https://github.com/thegreyd/ocp-build-data --group=openshift-4.19@add_4_19_0 inspect:stream INCONSISTENT_RHCOS_RPMS`
```
2025-06-12 12:57:26,800 art_tools.doozerlib.rhcos INFO Send request to https://releases-rhcos--prod-pipeline.apps.int.prod-stable-spoke1-dc-iad2.itup.redhat.com/storage/prod/streams/rhel-9.6/builds/None/x86_64/commitmeta.json
...
urllib.error.HTTPError: HTTP Error 403: Forbidden
```
Test:
```
$ doozer --assembly=4.19.0 …
```

Init build_id in RhcosBuildInspector

---

elliott/elliottlib/bzutil.py

Example: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fbuild-microshift/2306/console

Do not dump html as part of jira search fails

---

install.sh
pyartcd/requirements.txt

pyartcd requires awscli to sync packages to mirror.
This will make it not depend on the global installation on buildvm.

Add awscli to pyartcd requirements

---

doozer/doozerlib/backend/konflux_olm_bundler.py
doozer/tests/backend/test_konflux_olm_bundler.py

Labels like `distribution-scope` and `url` are required by Conforma (Enterprise Policy).

[Konflux] Add required labels for OLM bundles

---

doozer/doozerlib/backend/konflux_fbc.py
doozer/tests/backend/test_konflux_fbc.py

Conforma (EC) requires the OLM bundle image itself to be included in `images-mirror-set.yaml`. This PR will make EC happy.
Tested with https://github.com/openshift-priv/art-fbc/commit/650489b69fec62dbd3676b9732dd21093cb89e46

[Konflux] Fix images-mirror-set to include the bundle itself

---

pyartcd/pyartcd/pipelines/ocp4_konflux.py

[Test build](https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4-konflux/11866/console) wiped out the failure counters from Redis.

Reset rebase fail counters when rebase succeeds

---

doozer/doozerlib/backend/konflux_client.py
elliott/elliottlib/cli/konflux_release_cli.py
elliott/elliottlib/cli/konflux_release_watch_cli.py
elliott/elliottlib/cli/snapshot_cli.py
elliott/tests/test_konflux_release_cli.py

This will let `elliott release watch <release_name> --dump` watch the release as it progresses, and dump out the object in yaml at the end. This info is needed for post-processing in shipment-ci pipelines
Test
```
$ elliott release watch ash-test-4-18-stage-release-5fjk9 --dump
2025-06-18 12:34:08,738 artcommonlib INFO Konflux DB initialized 
2025-06-18 13:06:25,472 doozerlib.backend.konflux_client INFO Found release at https://konflux-ui.apps.kflux-ocp-p01.7ayg.p1.openshiftapps.com/ns/ocp-art-tenant/applications/openshift-4-18/releases/ash-test-4-18-stage-release-5fjk9
2025-06-18 12:34:08,984 doozerlib.backend.konflux_client INFO Release ash-test-4-18-stage-release-5fjk9 [status=True][reason=Succeeded]
2025-06-18 12:34:08,985 art_tools.elliottlib.cli.konflux_release_watch_cli INFO …
```

Enable --dump in watch release cli

---

doozer/doozerlib/backend/konflux_fbc.py
doozer/doozerlib/image.py
doozer/tests/backend/test_konflux_fbc.py

When building FBC, we need to convert image repo names of OLM bundles to delivery repo names, so that Conforma can validate those bundles in FBC even before they are shipped to the delivery repo. However, we found the name of the internal build repo doesn't always match the delivery repo. Therefore, explicitly specifying delivery repo names for OLM bundles in ocp-build-data image config is the only way to go. Fortunately, those delivery repo names can be dumped from Pyxis.
This PR make Doozer use the bundle_delivery_repo_name field in ocp-build-data image config.

[Konflux] Use bundle delivery repo specified in ocp-build-data

---

doozer/doozerlib/image.py
doozer/doozerlib/lockfile.py
doozer/tests/test_lockfile.py

Adds validation to ensure enabled_repos is defined and not empty before attempting lockfile generation. Checks happen in both is_lockfile_generation_enabled() and generate_lockfile() to catch issues early and provide clear feedback.
[Test job](https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4-konflux/11964/console)

Add defensive checks for lockfile generation preconditions

---

doozer/doozerlib/lockfile.py
doozer/tests/test_lockfile.py

So basically when we find the digest file upstream and it matches, we'd skip generating the lockfile but then not download the files locally. This meant the next time
the pipeline ran, the files would be missing upstream and we would generate the files again. This would end up in a pattern where we generate the files every second run.
The flow was:
1. Find matching digest upstream → skip generation
2. Don't write anything locally
3. Next pipeline run → files are gone upstream
4. Not needed run 🙃
Now when we find a matching digest upstream, we actually download both the digest and lockfile to make sure they're availible for the next run:
- Added `_get_lockfile_from_target_branch()` to grab the lockfile from upstream
- Added `_get_target_branch()` helper since we were duplicating that logic …

Fix lockfile pipeline continuity by downloading upstream files when digest matches

---

doozer/doozerlib/backend/build_repo.py
doozer/doozerlib/backend/rebaser.py
doozer/doozerlib/lockfile.py

Implements comprehensive OpenTelemetry span instrumentation across the entire KonfluxRebaser workflow to enable effective debugging of async rebase operations. Replaces low-level command-only traces with semantic business operation spans that provide meaningful context and hierarchical organization.
**Before:** Limited debugging effectiveness due to only low-level command execution spans (`cmd_assert_async`, `cmd_gather_async`) repeated 341 times with flat span structure, no business operation grouping, and critical context information truncated in UI, making it impossible to correlate failures to specific workflow phases.
**After:** Comprehensive debugging visibility with clear high-level workflow phases, hierarchical span organization reflecting actual async operation dependencies, …

feat(telemetry): add comprehensive OpenTelemetry spans for async rebase operations

---

elliott/elliottlib/shipment_model.py
ocp-build-data-validator/validator/json_schemas/shipment.schema.json

This is so we can use custom art-tools commit in shipment schema
see: https://gitlab.cee.redhat.com/hybrid-platforms/art/shipment-ci/-/merge_requests/20

Support tools in shipment schema

---

pyartcd/tests/pipelines/test_prepare_release.py

Follow up to https://github.com/openshift-eng/art-tools/pull/1719
Add some basic unit tests for update_build_data method, so when we make changes,
we get immediate feedback if we break anything.
The next step is to remove the direct invocations to git commands and yaml dump from the method, and instead use `GitRepository` class which encapsulates these operations and mock/patch them instead. This is already done in the newly written `PrepareReleaseKonfluxPipeline`.
Assisted by Cursor

Add tests for update_build_data in PrepareReleasePipeline

---

elliott/elliottlib/cli/konflux_release_cli.py
elliott/elliottlib/cli/snapshot_cli.py
elliott/elliottlib/shipment_utils.py
elliott/tests/test_shipment_utils.py
pyartcd/pyartcd/pipelines/prepare_release_konflux.py

These fixes are needed in prepare-release-konflux, if build finding does not return anything or is skipped.
Seen at https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fprepare-release-konflux/41/console
Test run: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fprepare-release-konflux/44/console

Skip snapshot if builds are not found

---

elliott/elliottlib/cli/common.py
elliott/elliottlib/cli/konflux_release_cli.py
elliott/elliottlib/cli/konflux_release_watch_cli.py
elliott/elliottlib/cli/shipment_cli.py
elliott/elliottlib/cli/snapshot_cli.py
elliott/elliottlib/runtime.py
elliott/tests/test_konflux_release_cli.py

Fix error seen at https://gitlab.cee.redhat.com/hybrid-platforms/art/ocp-shipment-data/-/jobs/36829895 
Also provide an option for elliott to disable-gssapi login, needed for commands that run outside of buildvm, and do not need keytab to auth to brew (shipment repo)
Test: https://gitlab.cee.redhat.com/hybrid-platforms/art/ocp-shipment-data/-/jobs/36833578

Konflux commands should default to build-system konflux

---

elliott/elliottlib/cli/attach_cve_flaws_cli.py
pyartcd/pyartcd/pipelines/prepare_release_konflux.py
pyartcd/tests/pipelines/test_prepare_release_konflux.py

Integrate `elliott attach-cve-flaws` into Konflux prepare-release pipeline.
Test build: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fprepare-release-konflux/67/console
Created shipment MR: https://gitlab.cee.redhat.com/hybrid-platforms/art/ocp-shipment-data/-/merge_requests/41
Ref. [ART-13329](https://issues.redhat.com/browse/ART-13329)

ART-13329 Integrate attach-cve-flaws in prepare-release for Konflux

---

pyartcd/pyartcd/pipelines/build_microshift_bootc.py

Follow up to https://github.com/openshift-eng/art-tools/pull/1635 and https://github.com/openshift-eng/aos-cd-jobs/pull/4404/files
Fixes error seen at https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fbuild-microshift-bootc/113/console

Replace basic auth with registry config

---

elliott/elliottlib/cli/__main__.py
elliott/elliottlib/cli/verify_payload.py
elliott/elliottlib/util.py
pyartcd/pyartcd/pipelines/prepare_release.py

This pull request introduces a significant refactor and enhancement to the `elliott verify-payload` command. The changes focus on improving code maintainability, simplifying the user interface, and expanding functionality to support new workflows, particularly for Konflux assemblies.
- The core logic of the `verify-payload` command has been encapsulated in a new `VerifyPayloadPipeline` class.
- The `--advisory` CLI option has been **removed**.
- The command now automatically determines the relevant image advisory by inspecting the assembly definition (group/assembly config), eliminating the need for the user to specify it manually.
- This is related with the removal of the `prerelease` job (see https://github.com/openshift-eng/aos-cd-jobs/pull/4429); `verify-payload` is now only executed …

ART-13331 Implement verify-payload for Konflux shipments

---

pyartcd/pyartcd/pipelines/prepare_release_konflux.py

Test build: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fprepare-release-konflux/82/console
The build ran with a temporary commit that commented out pipeline steps that came before verify-payload, as `elliott shipment new` was failing. The commit has then been removed.

Integrate elliott verify-payload in prepare-release-konflux

---

artcommon/artcommonlib/konflux/konflux_build_record.py
doozer/doozerlib/backend/konflux_fbc.py
doozer/doozerlib/backend/konflux_olm_bundler.py
elliott/elliottlib/cli/snapshot_cli.py
pyartcd/pyartcd/pipelines/prepare_release_konflux.py

When component name parsing from url fails, fallback on fetching from staticmethods from Builder class.
This is a temporary hack to let the pipeline work with older builds and until we complete work for storing
and fetching component name from DB.
https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fprepare-release-konflux/88/console

Tweak component name parsing from url

---

artcommon/artcommonlib/util.py

We trigger pipelines in parallel and sometimes we fetch date to the exact second, in which case object creation fails.
Setting it to microsecond precision will not let that happen.
Example of collision occuring
- https://gitlab.cee.redhat.com/hybrid-platforms/art/ocp-shipment-data/-/jobs/37132356
- https://gitlab.cee.redhat.com/hybrid-platforms/art/ocp-shipment-data/-/jobs/37132357

Konflux object date to microsecond precision

---

doozer/doozerlib/cli/release_gen_assembly.py

Advisories are updated with what's defined in the previous group, for missing keys. For Konflux, this generates an invalid assembly when, for example, `ec.4` has:
```
group:
advisories:
image: -1
rpm: 149403
extras: -1
metadata: -1
prerelease: -1
microshift: 151969
```
as it currently does. As a consequence, `ec.5` will also have
```
group:
advisories:
rpm: 149403
microshift: 151969
image: -1
extras: -1
metadata: -1
```
and this will break prepare-release-konflux because
```
ValueError: Shipment config should not specify advisories that are already defined in assembly.group.advisories: {'extras', 'metadata', 'image'}
```

Konflux assemblies should not reference advisories handled by shipment

---

pyartcd/pyartcd/jira_client.py
pyartcd/pyartcd/pipelines/prepare_release.py
pyartcd/pyartcd/pipelines/prepare_release_konflux.py
pyartcd/tests/pipelines/test_prepare_release_konflux.py

Test build https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fprepare-release-konflux/101 run from a different branch where bundle builds were bypassed, as we currently have a rebase failure that would prevent the job from succeeding.
[ART-13418](https://issues.redhat.com/browse/ART-13418) was created as a clone of the new template ticket

ART-13350 prepare-release-konflux creates jira ticket

---

artcommon/artcommonlib/konflux/konflux_build_record.py
elliott/elliottlib/cli/snapshot_cli.py

https://issues.redhat.com/browse/ART-13270
Follow up to https://github.com/openshift-eng/art-tools/pull/1802 
Start using the new field when creating snapshot
Test:
Build with build_component field populated: https://art-build-history-art-build-history.apps.artc2023.pc3z.p1.openshiftapps.com/build?nvr=ose-aws-efs-csi-driver-operator-bundle-container-v4.17.0.202507161321.p2.gcc86210.assembly.stream.el9-1&outcome=success&type=bundle
```
elliott -g openshift-4.17 snapshot new ose-aws-efs-csi-driver-operator-bundle-container-v
4.17.0.202507161321.p2.gcc86210.assembly.stream.el9-1
...
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
name: ose-4-17-20250716152020649666-1
namespace: ocp-art-tenant
labels:
test.appstudio.openshift.io/type: override …
```

ART-13270 Use build_component field in snapshot creation

---

doozer/doozerlib/backend/konflux_fbc.py
doozer/tests/backend/test_konflux_fbc.py

Currently every FBC component lives in its own Konflux application due to Konflux's own limitation. This complicates konflux-release-data configuration and shipment pipeline implementation. Once multi-component FBC support is deployed, we can merge this PR to move to multi-component FBC.

Konflux: Use multiple components for FBC

---

doozer/doozerlib/backend/konflux_olm_bundler.py

Right now record.log stores bundle_nvr incorrectly. Fix that
Example: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Folm_bundle_konflux/3636/artifact/artcd_working/doozer_working/record.log/*view*/
bundle_nvr=ose-secrets-store-csi-driver-operator-bundle-v4.20.0.202507211028.p2.ga4fc5c3.assembly.stream.el9-1
nvr in db: https://art-build-history-art-build-history.apps.artc2023.pc3z.p1.openshiftapps.com/build?nvr=ose-secrets-store-csi-driver-operator-bundle-container-v4.20.0.202507211028.p2.ga4fc5c3.assembly.stream.el9-1

Fix bundle nvr in record.log

---

artcommon/artcommonlib/gitdata.py
elliott/elliottlib/cli/find_builds_cli.py

See: https://redhat-internal.slack.com/archives/C03JYDGPX8F/p1751488032244189?thread_ts=1751482523.009209&cid=C03JYDGPX8F
We recently introduced PATCH as a new string variable in erratatool.yml advisory template strings.
This variable is not available as other's are in group.yml. So when we try to load erratatool.yml with 
group config vars (in `find-builds`), we fail to substitute ANY value in template because PATCH isn't provided.
One way could be to have a template value in group.yml `PATCH: PATCH` - this would make sure any placeholder, remains placeholder. But then we will not be able to replace PATCH subsequently using `.format`.
Another way would be to use a safe formatter, which inserts vars that are given and leaves the others as is. This way it can still be substituted later.

Use safe formatting when loading template

---

elliott/elliottlib/cli/konflux_release_cli.py
elliott/tests/test_konflux_release_cli.py

We only reserve live_id for prod release, therefore releaseNotes.live_id is only meant for prod
For stage release, we want konflux to automatically assign a live_id to the release
see: https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1753275935250019

[konflux-release] Only allow live_id for prod

---

doozer/tests/test_lockfile.py

Some functions are not correctly mocked, causing unneeded network traffic during tests.

Fix Doozer unit test mocks

---

doozer/doozerlib/backend/konflux_client.py

1. KonfluxClient.wait_for_pipelinerun may mistakenly cancel pipelinerun when running a computer that is not on UTC. The problem is `datetime.now` returns timezone-naive object but creation_time obtained from kube API is always on UTC, resulting in a timeout.
2. Some kube API calls are missing _request_timeout. See https://github.com/openshift-eng/art-tools/pull/1636.

[Konflux] Fix minor issues in KonfluxClient

---

doozer/doozerlib/image.py
doozer/tests/test_image.py
ocp-build-data-validator/tests/test_schema/test_image_schema.py
ocp-build-data-validator/validator/json_schemas/image_config.base.schema.json

Implement exclude_parents configuration option to control RPM collection behavior in fetch_rpms_from_build method. This enables lockfile generation to choose between differential updates and complete package inventories based on use case requirements.
**Before:** Method always calculates `diff_rpms = rpms - parent_rpms` and returns only RPMs unique to this image, with fallback to full set only on parent lookup failures. This causes issues where an image attempts to install packages that are already in the base image.
**After:** Method should provide both diff and full list behaviors based on use case requirements - some scenarios need only new RPMs (diff), while others need complete package inventories (union). Configuration-driven approach provides this flexibility and prevents base …

feat(rpm-lockfile): add configurable parent exclusion for lockfile RPM collection

---

doozer/doozerlib/cli/fbc.py
doozer/tests/cli/test_fbc.py
pyartcd/pyartcd/pipelines/build_fbc.py

Add `--reset-to-prod` option to reset FBC to prod index before build.

[Konflux] FBC: Reset to prod index before build

---

doozer/doozerlib/backend/konflux_fbc.py
doozer/tests/backend/test_konflux_fbc.py

FBC builds are pushed out to the public mono repo [art-fbc](https://quay.io/repository/redhat-user-workloads/ocp-art-tenant/art-fbc?tab=tags&tag=latest), in order for stakeholders to get the latest tag per operator per version, tag it like `ocp__4.20__operator-delivery-repo-name`
https://github.com/openshift-eng/ocp-build-data/blob/openshift-4.20/images/cluster-nfd-operator.yml#L21 - is an example delivery repo name in our config.

ART-13868: tag latest fbc builds with version

---

doozer/doozerlib/backend/rebaser.py
doozer/tests/backend/test_rebaser.py

Do not need to check for `self._runtime.group_config.konflux.cachi2.gomod_version_patch` since we need to add the .0 if its missing

apply .0 if go version >= 1.22

---

elliott/elliottlib/cli/konflux_release_cli.py
elliott/tests/test_konflux_release_cli.py

Right now, re-releases fail: https://gitlab.cee.redhat.com/hybrid-platforms/art/ocp-shipment-data/-/jobs/37856445

allow konflux re-release for non-prod

---

doozer/doozerlib/backend/konflux_client.py
doozer/doozerlib/backend/konflux_fbc.py
doozer/doozerlib/cli/fbc.py
doozer/doozerlib/runtime.py
doozer/requirements.txt
doozer/tests/backend/test_konflux_fbc.py
pyartcd/pyartcd/__main__.py
pyartcd/pyartcd/pipelines/build_merged_fbc.py

This command is to merge per-component FBC fragments into one single
stage index.
Example command:
```sh
doozer --group=openshift-4.18 --assembly=stream beta:fbc:merge --konflux-kubeconfig=/path/to/kubeconfig --target-index=quay.io/openshift-art/stage-fbc-fragments:ocp-4.18 quay.io/openshift-art/stage-fbc-fragments:ocp__4.18__helloworld-operator quay.io/openshift-art/stage-fbc-fragments:ocp__4.18__pf-status-relay-operator
```

[Konflux] Add doozer verb to build stage operator index

---

doozer/doozerlib/cli/release_gen_assembly.py
pyartcd/pyartcd/pipelines/gen_assembly.py

add elease_date and brew_event key in gen-assembly
test job: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/hack/job/ximhan/job/build%252Fgen-assembly/10/console
created pr: https://github.com/openshift-eng/ocp-build-data/pull/7200
```
group:
....
release_date: 2025-Oct-30
```

ART-3761 ADD release_date in gen-assembly

---

doozer/doozerlib/backend/konflux_fbc.py
doozer/doozerlib/cli/fbc.py
doozer/doozerlib/opm.py
doozer/tests/backend/test_konflux_fbc.py
doozer/tests/cli/test_fbc.py
doozer/tests/test_opm.py

No need to generate templates and render from templates. The migration can be done with the `opm render` command.
Test jobs:
1. 4.17: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Ffbc-import-from-index/17/console
2. 4.16: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Ffbc-import-from-index/18/console

[Konflux] Simplify fbc:import

---

elliott/elliottlib/cli/find_builds_cli.py
pyartcd/pyartcd/util.py

the json dump method chaned recently, update the parameter
the error looks like
`TypeError: _json_dump() takes 2 positional arguments but 3 were given`

Fix microshift pipeline

---

doozer/doozerlib/cli/scan_sources_konflux.py
pyartcd/pyartcd/pipelines/ocp4_scan_konflux.py

Currently, only ocp4-scan is looking at outdated/updated RHCOS content, and triggers rhcos builds or build-sync pipelines accordingly. We'll eventually need to migrate these operations to the Konflux-specific pipelines, if we ever want to get rid of the OSBS code. This PR takes the first step in that direction, by teaching Konflux scan-sources to look at RHCOS as well.
Test build: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4-scan-konflux/26019/console
Ref. [ART-13935](https://issues.redhat.com/browse/ART-13935)

ART-13935 scan-sources-konflux: also output RHCOS and RPMs changes

---

doozer/doozerlib/cli/__main__.py
doozer/doozerlib/cli/images.py
doozer/tests/cli/test_images.py

Sometimes, when we want to do a rebuild an image manually, we want to rebuild its ancestors as well, like in konflux. This new command will give us a list of all its ancestors so that we can pass in the comma separated values to the ocp4 job.
```
$ doozer -g openshift-4.20 images:show-ancestors --image-names ptp-operator-must-gather,ose-frr,openshift-enterprise-console
openshift-base-nodejs.rhel9,openshift-base-rhel9,openshift-enterprise-base-rhel9,openshift-enterprise-cli,ose-must-gather
```
Would also be useful for testing new konflux task bundle updates: https://art-docs.engineering.redhat.com/konflux/update-konflux-task-bundles/

doozer images:show-ancestors

---

doozer/doozerlib/cli/release_gen_assembly.py

https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fgen-assembly/679/
```
File "/mnt/jenkins-workspace/s-cd-builds_build_gen-assembly_2/art-tools/doozer/doozerlib/cli/release_gen_assembly.py", line 909, in _get_release_date
self.release_date = await get_assembly_release_date_async(self.release_name)
```
Build succeeded with fix: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fgen-assembly/680/

fix gen assembly

---

doozer/doozerlib/backend/konflux_fbc.py
doozer/doozerlib/util.py
doozer/tests/backend/test_konflux_fbc.py

OLM bundle entity type 'olm.csv.metadata' might not exist in 4.16 and prior. This PR changes the way how CSV metadata is loaded.
Also when Doozer bootstraps FBC repo for a new repo, a hardcoded default logo is used. This PR changes this by using the logo from the CSV file.
Test build: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fbuild-fbc/430/console

[Konflux] Fix FBC CSV metadata parsing and logo bootstrapping

---

doozer/doozerlib/backend/konflux_fbc.py
doozer/tests/backend/test_konflux_fbc.py

Re-generate catalog.Dockerfile during FBC rebase. This makes sure catalog.Dockerfile is updated after base image change.

[Konflux] fbc:rebase: Always re-generate catalog.Dockerfile

---

artcommon/artcommonlib/util.py
pyartcd/pyartcd/pipelines/build_microshift_bootc.py

store bootc image pullspec to a tag to prevent GC
https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fbuild-microshift-bootc/155/console
```
oc image mirror --keep-manifest-list quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:3ac1f3c1d317643dc565f47bc960646aa237aca5de10ef62ba4cce6591c6f9d0 quay.io/openshift-release-dev/ocp-v4.0-art-dev:sha256-3ac1f3c1d317643dc565f47bc960646aa237aca5de10ef62ba4cce6591c6f9d0
```

tag bootc pullspec to tag

---

artcommon/artcommonlib/exectools.py
elliott/elliottlib/cli/__main__.py
elliott/elliottlib/cli/conforma_cli.py

```
elliott -g openshift-4.18 verify-conforma cluster-nfd-operator-fbc-4.18.0-20250723040450 --env stage
2025-07-23 19:51:10,009 art_tools.elliottlib.cli.snapshot_cli INFO Validating given NVRs...
2025-07-23 19:51:10,009 art_tools.elliottlib.cli.snapshot_cli INFO Fetching NVRs from DB...
2025-07-23 19:51:11,547 art_tools.artcommonlib.exectools INFO Executing:cmd_gather_async: oc image info -o json --filter-by-os=amd64 quay.io/redhat-user-workloads/ocp-art-tenant/art-fbc@sha256:c4700172a4414ac1f073fd8d120b546f9c144ce726198b5d780c59cb51405dae
2025-07-23 19:51:14,319 doozerlib.backend.konflux_client WARNING [DRY RUN] Would have created appstudio.redhat.com/v1alpha1/Snapshot ocp-art-tenant/ose-4-18-20250723235113797360-1
2025-07-23 19:51:14,319 art_tools.elliottlib.cli.snapshot_cli INFO …
```

elliott verify-conforma

---

doozer/doozerlib/cli/scan_sources_konflux.py

ocp4 scan for konflux failed with clone distgit https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4-scan-konflux/27319/console

fix ocp4_scan_konflux remove clone distgit for konflux

---

pyartcd/pyartcd/pipelines/ocp4.py
pyartcd/pyartcd/pipelines/ocp4_konflux.py

`ocp4` and `ocp4-konflux` are erroneously tagging what RPSs are being built in the Jenkins build title. This comes from mistakingly checking for the RPM build strategy in the build plan initialization, without checking whether the building release belongs to the KONFLUX_IMAGESTREAM_OVERRIDE_VERSIONS constant.

Fix RPM part in ocp4{-konflux} title on Jenkins

---

doozer/doozerlib/cli/release_gen_payload.py

When pruning multi-arch nightlies, we look at existing tags to ensure at least 2 accepted nightlies remain. The `is_accepted` function crashes when processing istag that has `annotations: null`

Handle istag with null annotations when checking number of accepted multi nightlies

---

doozer/doozerlib/cli/release_gen_payload.py
doozer/tests/cli/test_gen_payload.py

When deciding whether to update release controller with new multi-arch nightly, we look at the name of the last tag/nightly in the ImageStream and extract its date from its name.
This can be problematic when the last tag is not a nightly tag (as seen in [this run of build-sync-konflux](https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fbuild-sync-konflux/6076/consoleFull)).
To prevent this, check first if the last tag really is a nightly

Skip non-nightly tags when searching for last nightly

---

pyartcd/pyartcd/oc.py
pyartcd/pyartcd/pipelines/build_microshift.py
pyartcd/pyartcd/pipelines/build_microshift_bootc.py
pyartcd/pyartcd/pipelines/build_sync.py
pyartcd/pyartcd/pipelines/ocp4.py
pyartcd/tests/pipelines/test_ocp4.py

The only usage I've found of `doozer images:streams mirror` is by the `ocp4` pipeline. Log into the QCI registry before mirroring images.

Let oc login into the QCI registry

---

pyartcd/pyartcd/pipelines/ocp4.py

This PR introduces a few fixes and improvements to the ocp4 pipeline:
1.  **More Accurate Jenkins Job Status:** The Jenkins job title and description have been improved to provide a clearer and more accurate status of the build process. Specifically:
*   The title now indicates whether all, some, or no RPMs/images are being built.
*   The description is updated to reflect the build plan for RPMs and images.
*   The message about creating an RPM compose is now only displayed when it's relevant.
2.  **Conditional Bug Sweep:** The bug sweep, which transitions bugs from `MODIFIED` to `ON_QA`, will now only run if there were actual RPMs or images built during the pipeline execution. This prevents unnecessary bug state changes when no artifacts are produced.
3.  **Build Plan Consistency:** When …

Fix ocp4 title and description; do not sweep unless needed

---

pyartcd/pyartcd/jenkins.py

To fix failures as seen in https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/maintenance/job/maintenance%252Fcleanup-locks/51114/console

Check if Jenkins build path is not empty

---

doozer/doozerlib/cli/release_gen_payload.py

Ref. [ART-13996](https://issues.redhat.com/browse/ART-13996)

ART-13996 Exclude mismatched siblings from payload update for pre-releases

---

pyartcd/pyartcd/pipelines/gen_assembly.py

Reverts openshift-eng/art-tools#1942
there are some issue that need Authentication credentials
{"detail":"Authentication credentials were not provided."}

Revert "also get inflight for konflux release"

---

artcommon/artcommonlib/util.py

Quay flakes causing not all images to be mirrored out. For example: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4-konflux/15963/console
```
images&akamai_signature=exp=1756250761~hmac=ac5d6977afc59d1803faabaa47dc227103c9d8d12f867dcec8bdef848d943fca": remote error: tls: internal error
```

art-images-share sync fix

---

doozer/doozerlib/assembly_inspector.py

This rpm is built in rhaos, but it is consumed in RHCOS RHEL layer.

Permit discrepancy for ose-aws-ecr-image-credential-provider

---

artcommon/artcommonlib/util.py
doozer/doozerlib/backend/konflux_image_builder.py
doozer/doozerlib/cli/scan_sources_konflux.py
doozer/tests/cli/test_scan_sources_konflux.py

The konflux build pipeline has a step called build source image. The source image is built and signed as part of that step, but last week there was build that was not signed due to transient error on the konflux's side, which caused us a significant delay to promote the payload.
To prevent that, check to see if the source image is signed or not. If its signed, mark the build as failed, to trigger a rerun.
Test build: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4-konflux/17240
Seeing
```
2025-09-19 16:49:56,691 art_tools.artcommonlib.exectools INFO Executing:cmd_gather_async: cosign download signature quay.io/redhat-user-workloads/ocp-art-tenant/art-images:sha256-c581e65aafeb86d8cd3d9fecd2858118a669c5e16ed723d52c13e09f01ba33ad.src@s …
```

fail build if source image signature is missing

---

doozer/doozerlib/backend/konflux_image_builder.py

Fix the mismatch between the build_priority value being used for builds and the one being stored in the DB.
Test build: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4-konflux/17242/

fix build priority bug

---

doozer/doozerlib/backend/konflux_image_builder.py
doozer/tests/backend/test_konflux_cachi2.py

Extended RPM prefetch functionality to conditionally disable GPG checking during prerelease phase by adding DNF repository configuration with gpgcheck=0 for all enabled repositories using proper repository IDs.
**Before:** Current RPM prefetch only includes basic structure `{"type": "rpm", "path": "."}` without any DNF repository configuration options, regardless of software lifecycle phase.
**After:** When building images during prerelease phase, RPM prefetch includes DNF repository configuration that disables GPG checking (`"gpgcheck": "0"`) for all repositories, following the Hermeto specification format with proper content set IDs.
- `doozer/doozerlib/backend/konflux_image_builder.py`: Enhanced _prefetch() method (lines 393-416) to detect prerelease phase and add DNF repository …

feat(konflux): add prerelease GPG check disable for RPM prefetch

---

elliott/elliottlib/cli/attach_cve_flaws_cli.py

similar to https://github.com/openshift-eng/art-tools/pull/1985
use SafeFormatter to let Elliott ignore those missing variables during variable substitution and not panic.

use safeformatter for docs replacement

---

elliott/elliottlib/cli/conforma_cli.py

wrapper function get_build_records_by_nvrs in elliott/elliottlib/cli/snapshot_cli.py does not accept a keyword parameter called strict.
This change fixes this issue:
The issue was seen as follows:
verify-conforma command called:
elliott -g openshift-4.16 --data-path=https://github.com/openshift-eng/ocp-build-data verify-conforma --pullspec [registry.ci.openshift.org/ocp/release:4.16.0-0.nightly-2025-10-07-073920](http://registry.ci.openshift.org/ocp/release:4.16.0-0.nightly-2025-10-07-073920) --konflux-kubeconfig /home/fedora/pullsandkube/artkubeconfig
Error in the trace:
2025-10-07 16:59:19,960 art_tools.elliottlib.cli.conforma_cli ERROR Failed to process batch 19: get_build_records_by_nvrs() **got an unexpected keyword argument 'strict'**
2025-10-07 16:59:19,960 …

remove parameter strict=True from the call to get_build_records_by_nvrs in  wrapper function in elliottlib
