elliott/elliottlib/cli/find_bugs_kernel_cli.py
elliott/elliottlib/cli/find_bugs_kernel_clones_cli.py
elliott/elliottlib/early_kernel.py
elliott/tests/test_early_kernel.py
elliott/tests/test_find_bugs_kernel_cli.py
elliott/tests/test_find_bugs_kernel_clones_cli.py

porting https://github.com/openshift-eng/elliott/pull/585 to art-tools

[ART-5863] update elliott to close trackers when OCP ships a kernel

---

doozer/doozerlib/image.py

Reverts openshift-eng/art-tools#19

Revert "mass-rebuilds: only for streams.<stream>.image attribute"

---

.devcontainer/Containerfile
.devcontainer/README.md
.devcontainer/brewkoji.conf
.devcontainer/doozer.settings.yaml
.devcontainer/elliott.settings.yaml
.devcontainer/krb5-redhat.conf

I use this for dev and test. I'll let others add the vscode enablement :)

add dev container files

---

elliott/elliottlib/cli/find_bugs_kernel_cli.py
elliott/tests/test_find_bugs_kernel_cli.py

So that QE and other people will know that kernel CVEs are cloned as non-CVE bugs on purpose.

Include a note for kernel[-rt] CVEs

---

doozer/doozerlib/cli/get_nightlies.py

This will help us debug the reasons between nightly set inconsistencies.

Log nightly differences with WARNING level

---

pyartcd/pyartcd/pipelines/promote.py

When promoting candidate assemblies:
- Don't move advisories to QE
- Don't error out if advisories are not on QE
In case of candidate assemblies advisories are being prepared every week and are usually missing cdn repos or have other things going on with them which can prevent them from being on QE.
These operations would still be performed for these set of advisories, when they are 
promoted as part of the GA standard assembly.
https://saml.buildvm.openshift.eng.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fpromote-assembly/843/parameters/

[promote] Move/verify advisories only for standard assemblies

---

pyartcd/pyartcd/jenkins.py
pyartcd/pyartcd/pipelines/cleanup_locks.py

Only log Jenkins build URL if it is valid

ART-7628 cleanup locks follow up

---

pyartcd/pyartcd/pipelines/build_sync.py

Related with https://github.com/openshift-eng/art-tools/pull/61

Use : separator for fail counters in Redis

---

elliott/elliottlib/cli/find_builds_cli.py

Fix for (got tweaked in https://github.com/openshift-eng/art-tools/pull/56)
```
File "/mnt/workspace/jenkins/working/_cd-builds_build_prepare-release/art-tools/elliott/elliottlib/cli/find_builds_cli.py", line 161, in find_builds_cli
unshipped_nvrps = _fetch_nvrps_by_nvr_or_id(builds, tag_pv_map, ignore_product_version=remove, brew_session=brew_session)
TypeError: _fetch_nvrps_by_nvr_or_id() missing 1 required positional argument: 'include_shipped'
```
https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fprepare-release/847/console

find-builds: Fix for include-shipped

---

.devcontainer/Containerfile
doozer/doozerlib/cli/config_plashet.py
doozer/doozerlib/metadata.py
doozer/doozerlib/runtime.py
elliott/elliottlib/cli/find_builds_cli.py
elliott/elliottlib/runtime.py

just some random things i saw and fixed while doing something unrelated.

minor tweaks

---

doozer/doozerlib/cli/config_tag_rpms.py
doozer/doozerlib/cli/images_health.py
doozer/doozerlib/distgit.py
doozer/doozerlib/image.py
doozer/doozerlib/rpm_builder.py

Seeking for lgtm, approve labels.
/cc @joepvd

ART-7806 check images health for stream assembly only

---

doozer/doozerlib/cli/__main__.py
doozer/doozerlib/state.py

Context: https://redhat-internal.slack.com/archives/GDBRP5YJH/p1695907446479599?thread_ts=1695829004.021079&cid=GDBRP5YJH

ART-7853 Optional images no longer apply

---

pyartcd/pyartcd/redis.py

Could potentially need this to store pending task IDs of SAST scans. Using Redis would be much easier to setup than a database.
Usecase:
SAST scans take a lot of time to finish. Hence after we kick them off we can store the value in Redis. In the beginning of each `scan-osh` job run, we can check to see if the pending tasks has finished. If it has we can take the next steps, which maybe sending out emails (this hasn't been finalized yet) 
_Requesting /lgtm and /approve_

Add support for Redis lists in pyartcd

---

doozer/doozerlib/cli/images_streams.py

Ref https://github.com/openshift-eng/doozer/pull/818
_Ready to merge. Requesting lgtm and approve_

 Use component name consistent for reconciliation

---

doozer/doozerlib/golang_builder_FIPS_wrapper.sh

Pass GO_COMPLIANCE_INFO=0 GO_COMPLIANCE_DEBUG=0 to the go invocation.
This is because go programs will sometimes invoke go programs. In one scenario, the parent go program was trying to parse the stderr of the child go invocation. Since the shim was outputting to stderr, this parsing failed.

Prevent recursive calls of go from generating shim stderr

---

doozer/doozerlib/source_modifications.py

fix modification scripts error

key source is not required

---

doozer/doozerlib/image.py

So that making a change to `scan_sources` or `content.source.ci_alignment` will not trigger a rebuild caused by config change.

Exclude certain keys from config digest calculation

---

doozer/doozerlib/image.py

Reverts openshift-eng/art-tools#95

Revert "Exclude certain keys from config digest calculation"

---

doozer/doozerlib/cli/images_streams.py

The purpose of upstream_image_mirror is to mirror upstream_image. The previous incarnation of this code would only do that if upstream_image_base was not set.
If upstream_image_base was set, it would incorrectly mirror the base image instead of the transformed result.
Changing this logic to ONLY mirror usptream_image.

Fix upstream_image_mirror

---

doozer/doozerlib/image.py

Reverts openshift-eng/art-tools#105

Revert "Revert "Exclude certain keys from config digest calculation""

---

pyartcd/pyartcd/pipelines/cleanup_locks.py

Needs https://github.com/openshift-eng/aos-cd-jobs/pull/4016 to work.
Won't break without it (title update is skipped in case env vars are missing)

Display removed locks in build title

---

doozer/doozerlib/cli/scan_sources.py

https://redhat-internal.slack.com/archives/GDBRP5YJH/p1698137843148919?thread_ts=1698133398.861759&cid=GDBRP5YJH

Do not crash if config_digest is not found, just skip the check

---

doozer/doozerlib/cli/scan_sources.py

Currently, we have a hard switch that only takes `openshift-enterprise-tests` into consideration for rebase into openshift-priv. Until now, rebase never happened: when there was a new commit in public upstream, mirroring into priv always happened before our scan, so Doozer never saw the need for a rebase.
In order to start seeing rebases happening, we could make the filter broader by accepting any component, but as soon as one single rebase happen the procedure would stop and continue with the scan. This way, we would start getting notifications about rebases, and react as needed.

Only rebase into -priv one (if any) random component for each ocp4-scan

---

elliott/elliottlib/cli/find_builds_cli.py
elliott/tests/test_find_builds_cli.py

It is helpful to know which advisories, the filtered builds are attached to
`./elliott -g openshift-4.14 --assembly rc.7 find-builds -k image --non-payload`

[find-builds] Log advisories that filtered builds are attached to

---

pyartcd/pyartcd/pipelines/build_microshift.py

So that we don't run these steps for ECs

[build-microshift] Skip advisory prep if there is no advisory

---

elliott/elliottlib/errata_async.py

Now we have multiple golang builders for an OCP version,
there can be 2 versions (go 1.19 and go 1.20) each for rhel8 and rhel9, 
so easily exceeding 3 and reaching 5.
This check doesn't make sense now.
Test
- Ran `elliott -g openshift-4.14 --assembly rc.7 attach-cve-flaws --into-default-advisories` with no errors

Do not error out on multiple golang builders

---

pyartcd/pyartcd/pipelines/promote.py
pyartcd/tests/pipelines/test_promote.py

Move liveID verification out of `invalid_errata_status` permit

Fix liveID verification

---

pyartcd/pyartcd/pipelines/promote.py

JIRA: [ART-7678](https://issues.redhat.com/browse/ART-7678)
related PRs: 
https://github.com/openshift-eng/aos-cd-jobs/pull/4041
https://github.com/openshift-eng/art-tools/pull/154

[ART-7678] stop building microshift 4.13

---

elliott/elliottlib/cli/find_bugs_sweep_cli.py
pyartcd/pyartcd/pipelines/check_bugs.py

related JIRA: [ART-7990](https://issues.redhat.com/browse/ART-7990)

ART-7990: Improve wording about blocker bug messages

---

elliott/elliottlib/cli/advisory_drop_cli.py
elliott/elliottlib/errata.py

Remove blocking advisory when drop advisory so it's child won't be blocked when push

ART-8187 check blocking advisory when drop advisory

---

pyartcd/pyartcd/jenkins.py

fix failed job https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Focp4_scan/565987/console

fix comment arg

---

elliott/elliottlib/constants.py

Used to create https://errata.devel.redhat.com/advisory/123948

[ART-8113] elliott: enable prerelease/advance/bootimage advisories

---

pyartcd/pyartcd/pipelines/brew_scan_osh.py

[scan-osh] Add version to job runs for easy identification

[scan-osh] Add version to title

---

doozer/doozerlib/cli/scan_osh.py

Better logging for easy debugging

[scan-osh] better logging

---

pyartcd/pyartcd/pipelines/brew_scan_osh.py

Create JIRA tickets when ART is building the images as well

[scan-osh] Run for all variants of job

---

doozer/doozerlib/cli/scan_osh.py

Fixes in this PR:
- Fix JIRA query
- Fix the way in which we read the config from image metadata

[scan-osh] Fix how the image config is read, fix status field

---

doozer/doozerlib/cli/scan_osh.py

The `nvr` being used was the NVR of the current build, instead of the first successful build.

[scan-osh] Fix nvr bug

---

doozer/doozerlib/cli/scan_osh.py

- Check image metadata earlier, so that scan can be skipped
- Handle case in which there is only one successful scan and everything before has failed

[scan-osh] Refactor code

---

doozer/doozerlib/cli/scan_osh.py

Non GA versions have target version set to .0, while the others with .z

[scan-osh] fix edge case for JIRA target version

---

doozer/doozerlib/cli/scan_osh.py

We can't raise tickets for NVRs that we are not building, for now

[scan-osh} skip NVRs that we are not building

---

doozer/doozerlib/cli/scan_osh.py

Use the correct build URL to find the scan defects

Use latest build URL

---

doozer/doozerlib/cli/scan_osh.py

Test ticket: https://issues.redhat.com/browse/ART-8306
- Update ticket description
- OCPBUGS pipeline only for stream builds

[scan-osh] ocpbugs pipeline only for stream, update ticket

---

doozer/doozerlib/cli/scan_osh.py

Changes in this PR related to OCPBUGS workflow:
- Run only for the scheduled variant of the job
- Check OSH only once per brew component. _(Sometimes more than one build of a component can be found after a run. So running just once, for the latest build NVR)_
_Ready to merge, requesting /lgtm and /approve_

[scan-osh] Update OCPBUGS workflow run

---

doozer/doozerlib/cli/scan_osh.py

Match https://github.com/openshift-eng/ocp-build-data/pull/3907

[scan-osh] match ocp-build-data config

---

doozer/doozerlib/cli/scan_osh.py

Sometimes components do not have successful scans, like this [one](https://cov01.lab.eng.brq2.redhat.com/osh/task/?search=openshift-enterprise-tests-container-v4.15.0). 
This ticket is the long term solution: https://issues.redhat.com/browse/OSH-376

[scan-osh] time out component, if can't find successful scan

---

elliott/elliottlib/bzutil.py
elliott/elliottlib/cli/__main__.py
elliott/elliottlib/cli/create_cli.py
elliott/elliottlib/cli/create_placeholder_cli.py
elliott/elliottlib/cli/create_textonly_cli.py
elliott/elliottlib/cli/repair_bugs_cli.py
elliott/elliottlib/cli/verify_attached_bugs_cli.py
elliott/functional_tests/test_verify_attached_bugs.py
elliott/tests/test_bzutil.py
elliott/tests/test_repair_bugs_cli.py
pyartcd/pyartcd/pipelines/advisory_drop.py

Reverts openshift-eng/art-tools#25

Revert "[ART-7056] deprecate placeholder bug"

---

doozer/doozerlib/cli/images_streams.py

for new created pr, update jira earlier before sleep

reconcile jira earlier for new pr

---

doozer/doozerlib/cli/images_streams.py
doozer/doozerlib/cli/scan_osh.py

https://issues.redhat.com/browse/ART-8413

ART-8413 Exact jira title search

---

doozer/doozerlib/cli/images_streams.py

Follow up to https://github.com/openshift-eng/art-tools/pull/217

ART-8413 Summary string should be in quotes

---

doozer/doozerlib/cli/scan_osh.py

- If the previous successful scan is a duplicate scan from the same NVR, skip that
- Update `SCAN_RESULTS_URL_TEMPLATE` url since we need the URL without the raw suffix to comment on the ticket.

[scan-osh] Skip if NVRs are same, minor fixes

---

doozer/doozerlib/cli/__main__.py

Add `--show-disabled` to include images that are disabled as well

images:print add --show-disabled flag

---

doozer/doozerlib/cli/__main__.py
doozer/doozerlib/cli/rpms.py
doozer/doozerlib/cli/scan_osh.py

Rolls back https://github.com/openshift-eng/art-tools/pull/229
Use `--load-disabled` base doozer param instead of separate `--show-disabled` or `--include-disabled` param

use --load-disabled 

---

pyartcd/pyartcd/jira.py
pyartcd/pyartcd/pipelines/operator_sdk_sync.py

replace the way using subtask index locates subtask to using keyword searching locate subtask
and auto complete  pushes release content to customer portal task by checking if the release pushed to fast channel

update operator-sdk job update subtask function

---

doozer/doozerlib/cli/images_streams.py

Skip over buildconfigs which are not currently present in config
```
$ KUBECONFIG=~/art-publish ./doozer -g openshift-4.16 images:streams start-builds --dry-run
...
Skipping outdated buildconfig: buildconfig.build.openshift.io/release-rhel-9-release-golang-1.19-openshift-4.16--art-builder
```

Skip outdated buildconfigs when triggering builds

---

doozer/doozerlib/cli/scan_osh.py

Fixes following https://github.com/openshift-eng/art-tools/pull/247
- Adding support for hotfix tags
- Logging previous ticket ID

[scan-osh] Sast update workflow

---

doozer/doozerlib/cli/scan_osh.py

Follows https://github.com/openshift-eng/art-tools/pull/247

[scan-osh] minor regex fix

---

doozer/doozerlib/cli/scan_osh.py

If its the first time we are raising a ticket for this component, then its only natural that there's not previous ticket for this.

[scan-osh] update log message

---

doozer/doozerlib/distgit.py

Let single images override canonical_builders_from_upstream.
/hold
as this needs https://github.com/openshift-eng/art-tools/pull/246 to merge first

ART-8483 canonical builders override

---

doozer/doozerlib/distgit.py
doozer/tests/test_distgit/test_image_distgit/test_image_distgit.py

With these changes, `alternative_upstream` should look like this:
```
alternative_upstream:
- when: el8
distgit:
branch: rhaos-{MAJOR}.{MINOR}-rhel-8
enabled_repos:
- rhel-8-baseos-rpms
- rhel-8-appstream-rpms
name: openshift/ose-cluster-autoscaler-rhel8
```

ART-8476 handle when clause

---

doozer/doozerlib/cli/config_plashet.py
elliott/elliottlib/errata.py

Follow up to https://github.com/openshift-eng/art-tools/pull/261

Get advisory builds with errata attributes

---

doozer/doozerlib/cli/images_streams.py

we have some pr against the upstream master branch, and when upstream branch cut the pr info may not be accurate, this pr add more specific release version in pr title and commit. Its also useful for search pr for a release

ART-8481: add release version in alignment pr

---

doozer/doozerlib/cli/rpms.py

Don't clone sources when printing rpm config

---

doozer/doozerlib/cli/images_streams.py

When running locally we want to lookup PRs opened by openshift-bot by default

[prs list] Look for PRs by openshift-bot by default

---

doozer/doozerlib/cli/scan_osh.py

There is a bug which is wiping descriptions in OCPBUGS on editing https://issues.redhat.com/browse/RH1-5087
which breaks our runs. Instead of erroring out early on individual tickets, wrap it and raise at end

Scan-osh: Don't error out early

---

doozer/doozerlib/cli/images_streams.py

use github query replace loop method to get alignment prs which will fix the github api rate limit issue
test: https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/hack/job/ximhan/job/build%252Fnag-upstream/7/artifact/shell.7/sh.7.doozer_--assembly_stream_--working-d...nshift-4.14_images_streams_prs_list/sh.7.combo.txt/*view*/

ART-8481: new alignment prs check method

---

doozer/doozerlib/cli/release_gen_assembly.py

To get around the issue of outdated payload tag in nightly imagestreams
`WARNING Ignoring payload tag cluster-config-api-rhel9 since payload_name=cluster-config-api is explicitly defined in image config`

gen-assembly: Ignore outdated payload tag

---

doozer/doozerlib/cli/scan_osh.py

Replicating https://github.com/openshift-eng/art-tools/pull/302

[scan-osh] Fix container bug

---

doozer/doozerlib/cli/scan_osh.py

Skip autoclosing RPM tickets for now

[scan-osh] Skip closing ticket for RPMs

---

doozer/doozerlib/cli/scan_osh.py

Requires further investigation

[scan-osh] disable autoclosing tickets for now

---

pyartcd/pyartcd/pipelines/promote.py

Skip `--verify-flaws` flag for elliott verify-attached-bugs for preview and prerelease

skip verify-flaws for preview and prerelease

---

art-cluster/pipelines/config/argocd/project/art-cd/common/image/base.yaml

[tekton] update git ref

---

art-cluster/pipelines/data/project/art-cd/image/Containerfile.base

Update repo path to match refactor

[tekton] update dockerfile path

---

doozer/doozerlib/cli/__main__.py

Test build
https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fsync-for-ci/224819/console

Fix reposync good now

---

Makefile

Needed after https://github.com/openshift-eng/art-tools/pull/325

Run flake8 and unit tests against validator as well

---

art-cluster/pipelines/config/argocd/project/art-cd/quay-doomsday-backup/base/event-listener.yaml
art-cluster/pipelines/config/argocd/project/art-cd/quay-doomsday-backup/base/route.yaml
art-cluster/pipelines/config/argocd/project/art-cd/quay-doomsday-backup/base/service.yaml
art-cluster/pipelines/config/argocd/project/art-cd/quay-doomsday-backup/base/trigger-binding.yaml
art-cluster/pipelines/config/argocd/project/art-cd/quay-doomsday-backup/base/trigger-template.yaml

Adding event listener and related resources to argocd.

[tekton] add quay backup event listener

---

pyartcd/pyartcd/pipelines/promote.py

`no_verify_blocking_bugs` for EC, RC and first GA

no_verify_blocking_bugs for EC, RC and first GA

---

art-cluster/pipelines/config/argocd/project/art-ci/ocp-build-data-validator/build-config.yaml
art-cluster/pipelines/config/argocd/project/art-ci/ocp-build-data-validator/cluster-role-binding.yaml
art-cluster/pipelines/config/argocd/project/art-ci/ocp-build-data-validator/event-listener.yaml
art-cluster/pipelines/config/argocd/project/art-ci/ocp-build-data-validator/image-stream.yaml
art-cluster/pipelines/config/argocd/project/art-ci/ocp-build-data-validator/pipeline.yaml
art-cluster/pipelines/config/argocd/project/art-ci/ocp-build-data-validator/route.yaml
art-cluster/pipelines/config/argocd/project/art-ci/ocp-build-data-validator/service.yaml
art-cluster/pipelines/config/argocd/project/art-ci/ocp-build-data-validator/task.yaml
art-cluster/pipelines/config/argocd/project/art-ci/ocp-build-data-validator/trigger-binding.yaml
art-cluster/pipelines/config/argocd/project/art-ci/ocp-build-data-validator/trigger-template.yaml
ocp-build-data-validator/Dockerfile
ocp-build-data-validator/entrypoint.sh

Migrates PRs:
- https://github.com/openshift-eng/ocp-build-data-validator/pull/129
- https://github.com/openshift-eng/art-config/pull/66

[ART-7423] Migrate ocp build data validator

---

doozer/doozerlib/cli/release_gen_assembly.py
pyartcd/pyartcd/pipelines/gen_assembly.py
pyartcd/tests/pipelines/test_gen_assembly.py

Prepare to accommodate advance operator release
Alongside https://github.com/openshift-eng/aos-cd-jobs/pull/4075

[ART-8764] Setup advance operator release

---

elliott/elliottlib/cli/create_cli.py

https://issues.redhat.com/browse/ART-8758

ART-8758 Leave advisory type comment if configured

---

pyartcd/pyartcd/pipelines/promote.py

Reverts openshift-eng/art-tools#332

Revert "[ART-8241] Backup promoted payloads to AWS"

---

elliott/elliottlib/cli/create_cli.py

Fix AttributeError in elliott

---

pyartcd/pyartcd/pipelines/promote.py
pyartcd/tests/pipelines/test_promote.py

Reverts https://github.com/openshift-eng/art-tools/pull/346
Fixes failing unit tests

Backup promoted payloads to AWS

---

pyartcd/pyartcd/pipelines/ocp4_scan.py

Follows https://github.com/openshift-eng/aos-cd-jobs/pull/4079

Allow ocp4-scan to ignore locks

---

pyartcd/pyartcd/constants.py
pyartcd/pyartcd/pipelines/build_microshift.py
pyartcd/pyartcd/pipelines/build_sync.py
pyartcd/pyartcd/pipelines/review_cvp.py

For `pyartcd:WARNING No assembly PRs were found with head=thegreyd:art8712` issue

Fix GhApi owner param

---

doozer/doozerlib/cli/images_streams.py

... because most of these are proposed changes, not just alignment with what ART already does.

[ART-8800] update alignment PR wording

---

elliott/elliottlib/cli/get_golang_report_cli.py
elliott/elliottlib/metadata.py

Follow up to https://github.com/openshift-eng/art-tools/pull/337
https://issues.redhat.com/browse/ART-8042
```
$ ./elliott --quiet go:report --ocp-versions 4.14,4.11,4.12,4.13,4.15,4.16 --ignore-rhel
4.14: [{'go_version': '1.20.12', 'building_image_count': 219, 'building_rpm_count': 2}, {'go_version': '1.19.13', 'building_image_count': 2}]
4.11: [{'go_version': '1.18.10', 'building_image_count': 194, 'building_rpm_count': 2}, {'go_version': '1.19.13', 'building_image_count': 3}]
4.12: [{'go_version': '1.19.13', 'building_image_count': 207, 'building_rpm_count': 2}]
4.13: [{'go_version': '1.19.13', 'building_image_count': 215, 'building_rpm_count': 2}]
4.15: [{'go_version': '1.20.12', 'building_image_count': 223, 'building_rpm_count': 2}, {'go_version': '1.19.13', 'building_image_count': …
```

ART-8042 Add rpm support in golang report

---

elliott/elliottlib/cli/find_bugs_golang_cli.py

Part of https://issues.redhat.com/browse/ART-8426 effort
follow up to https://github.com/openshift-eng/art-tools/pull/276
Also find the errata that shipped the builds that the fixes are in.

ART-8426 Find all golang trackers in ocpbugs and determine if they are fixed

---

doozer/doozerlib/cli/images_streams.py

reference [slack](https://redhat-internal.slack.com/archives/GDBRP5YJH/p1706886759407449?thread_ts=1706738151.149559&cid=GDBRP5YJH)
with go 1.21 showing up in `go.mod` with the `toolchain` directive, our primitive golang doesn't know how to rewrite it. use `sed` instead to make this less fragile (and rewrite `toolchain` too if seen).

doozer images:streams - fix golang version problem

---

doozer/doozerlib/cli/release_gen_payload.py
doozer/requirements.txt
doozer/tests/cli/test_gen_payload.py
pyartcd/pyartcd/oc.py
pyartcd/pyartcd/pipelines/build_rhcos.py
pyartcd/requirements.txt

New release broke import 
https://github.com/openshift/openshift-client-python/releases/tag/2.0.1

Fix imports and pin openshift-client lib

---

ocp-build-data-validator/validator/json_schemas/image_config.base.schema.json

To support https://github.com/openshift-eng/ocp-build-data/pull/4312

Allow name attribute in distgit

---

ocp-build-data-validator/validator/json_schemas/streams.schema.json
ocp-build-data-validator/validator/schema/streams_schema.py

To account for changes in https://github.com/openshift-eng/ocp-build-data/pull/4312

Fix validator

---

pyartcd/pyartcd/pipelines/promote.py

https://issues.redhat.com/browse/ART-8685

ART-8685 Make verify-attached-bugs non-gating for preGA assemblies

---

elliott/elliottlib/cli/verify_attached_bugs_cli.py

https://issues.redhat.com/browse/ART-8686
Test:
```
./elliott --group openshift-4.15 --assembly rc.6 verify-attached-bugs --skip-multiple-advisories-check --no-verify-blocking-bugs
...
Found the following problems, please investigate
Bug <https://issues.redhat.com/browse/OCPBUGS-20517|OCPBUGS-20517> is an invalid tracker bug. Please fix
Bug <https://issues.redhat.com/browse/OCPBUGS-18387|OCPBUGS-18387> has invalid status ASSIGNED
Bug <https://issues.redhat.com/browse/OCPBUGS-19106|OCPBUGS-19106> has invalid status POST
Bug <https://issues.redhat.com/browse/OCPBUGS-15811|OCPBUGS-15811> has invalid status Closed: Test Pending
Bug <https://issues.redhat.com/browse/OCPBUGS-28762|OCPBUGS-28762> has invalid status ASSIGNED
Bug <https://issues.redhat.com/browse/OCPBUGS-25312|OCPBUGS-25312> has …
```

ART-8686 Verify bug status by default for verify-attached-bugs

---

doozer/doozerlib/runtime.py

Reverts openshift-eng/art-tools#420

Revert "Enforce distgits cloning when canonical_builders is enabled"

---

doozer/doozerlib/runtime.py
elliott/elliottlib/cli/find_builds_cli.py
elliott/elliottlib/runtime.py

Follow up to https://github.com/openshift-eng/art-tools/pull/419

Honor canonical builder in elliott find-builds

---

art-cluster/pipelines/config/argocd/project/art-ci/ocp-build-data-validator/pipeline.yaml

the managed task name is "validator-task"

fix ref task name

---

doozer/doozerlib/distgit.py

Always inject metadata environment variables into Dockerfiles even when set_build_variables is set to false. This changes ensures that metadata config `envs` are written into Dockerfiles as well as some standard metadata: `__doozer_group`, `__doozer_key`, and `__doozer_version`.
Ultimately, this is to enable work for [ART-8910](https://issues.redhat.com//browse/ART-8910) which requires the ability to set environment variables without using `set_build_variables` .

[ART-8910] Always inject doozer metadata environment variables on rebase

---

doozer/doozerlib/runtime.py
elliott/elliottlib/cli/find_builds_cli.py
elliott/elliottlib/runtime.py

Reverts openshift-eng/art-tools#422
@locriandev elliott never clones distgit. Does canonical builder feature affect how elliott finds builds?

Revert "Honor canonical builder in elliott find-builds"

---

doozer/doozerlib/cli/release_gen_payload.py
doozer/tests/cli/test_gen_payload.py

As the first step for filtering out embargoed builds.

[ART-8970] Mirror all images to private quay

---

elliott/elliottlib/runtime.py

Follow up to https://github.com/openshift-eng/art-tools/pull/468

Do not double init logging - elliott

---

doozer/doozerlib/cli/images_health.py
pyartcd/pyartcd/constants.py
pyartcd/pyartcd/jenkins.py
pyartcd/pyartcd/pipelines/build_microshift.py
pyartcd/pyartcd/pipelines/build_sync.py
pyartcd/tests/test_jenkins.py

- Update buildvm URLs
- Fix is_build_running and is_api_reachable to correctly handle authentication by using jenkins_api.

Fix cleanup-locks

---

doozer/doozerlib/cli/__main__.py

test job https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fsync-for-ci/1099/console

fix reposync

---

doozer/doozerlib/cli/config_plashet.py

This new method should be much faster on new buildvm.

plashet: Use queryRPMSigs API to check if rpm signed

---

doozer/doozerlib/cli/__main__.py

no need createrepo_c https://manpages.debian.org/testing/dnf-plugins-core/dnf-reposync.8.en.html#download
no need --destdir https://manpages.debian.org/testing/dnf/dnf.8.en.html#downloaddir=_path_
test job https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fsync-for-ci/1120/console

Fix repodirs

---

doozer/doozerlib/cli/release_gen_payload.py
doozer/tests/cli/test_gen_payload.py

Follow up to https://github.com/openshift-eng/art-tools/pull/477

Include auth in all manifest tool push from-spec

---

pyartcd/pyartcd/pipelines/promote.py

`oc image extract` will exit with 0 even if no files are exacted.

promote: Fix oc-mirror extraction

---

pyartcd/pyartcd/pipelines/prepare_release.py

Enable autoescape for Jinja templates

Enable jinja autoescape

---

pyartcd/pyartcd/slack.py

Use channel ID from response
Using lgtm from https://github.com/openshift-eng/art-tools/pull/487

fix slack reactions bug

---

elliott/elliottlib/bzutil.py
elliott/elliottlib/cli/find_bugs_kernel_cli.py
elliott/elliottlib/cli/find_bugs_kernel_clones_cli.py
elliott/elliottlib/constants.py
elliott/tests/test_find_bugs_kernel_cli.py
elliott/tests/test_find_bugs_kernel_clones_cli.py

Ref https://issues.redhat.com/browse/ART-7053
Pulling the field ID using JIRA API since customfield IDs can change without notice

[ART-7053] Use JIRA field names

---

pyartcd/pyartcd/pipelines/scan_fips.py

[tekton-fips] slack client use content

---

art-cluster/pipelines/config/argocd/project/art-cd/fips-scanning/pipeline-task.yaml

Referencing https://github.com/openshift-eng/art-tools/blob/main/art-cluster/pipelines/config/argocd/project/art-ci/ocp-build-data-validator/task.yaml

[fips-tekton] Use internal route

---

doozer/doozerlib/cli/__main__.py

- Download repo metadata to metadata_dir
- Remove obsolete dnf config option `exactarch` (https://dnf.readthedocs.io/en/latest/release_notes.html#id109)
- Enable dry_run
- Cleanup the cmd in general
https://dnf-plugins-core.readthedocs.io/en/latest/reposync.html
https://dnf.readthedocs.io/en/latest/command_ref.html
Test: `doozer --assembly stream -g openshift-4.16 beta:reposync -o /tmp/repo_sync -c /tmp/cache/ --dry-run -n rhel-9-server-ironic-rpms`

Cleanup reposync command

---

doozer/doozerlib/cli/__main__.py

test job: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fsync-for-ci/4829/console

also sync noarch rpm

---

doozer/doozerlib/cli/images_streams.py
doozer/doozerlib/cli/scan_osh.py

ref https://issues.redhat.com/browse/ART-8482

[ART-8482] Add labels for better JIRA tracking

---

doozer/doozerlib/cli/release_gen_payload.py
doozer/tests/cli/test_gen_payload.py

ref. https://issues.redhat.com/browse/ART-8971

[ART-8971] Mirror non-embargoed images to public quay

---

doozer/doozerlib/cli/release_gen_payload.py
doozer/tests/cli/test_gen_payload.py

Reverts openshift-eng/art-tools#516
Breaks build-sync https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fbuild-sync/364/console

Revert "[ART-8971] Mirror non-embargoed images to public quay"

---

pyartcd/pyartcd/pipelines/prepare_release.py

To not have something like this https://github.com/openshift-eng/ocp-build-data/commit/a7991558e54a4dfe09b6d4c481d7a2f6523190aa
Tested with 
- https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fprepare-release/31/console
- https://github.com/openshift-eng/ocp-build-data/commit/bf146e9e7618a08119258c17104bb1ebd425574c

Prepare-release: Respect assembly key names

---

elliott/elliottlib/bzutil.py
elliott/tests/test_bzutil.py
elliott/tests/test_bzutil_jira.py
elliott/tests/test_find_bugs_blocker_cli.py
elliott/tests/test_find_bugs_qe_cli.py
elliott/tests/test_find_bugs_sweep_cli.py
elliott/tests/test_remove_bugs_cli.py
elliott/tests/test_repair_bugs_cli.py
elliott/tests/test_verify_attached_bugs_cli.py

use jira lib to get jira fileds with auth so it won't failed with rate limit issue
test run:https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Ftag-rpms/14303/console

get jira fields with auth

---

doozer/doozerlib/cli/images_streams.py

Right now this fails because we are trying to fetch image metas and populate them with latest builds,
and latest builds aren't available for 4.17
`doozer -g openshift-4.17 images:streams mirror --stream rhel-9-golang-1.22 --dry-run`
but if a stream is given via `--stream` then it should ignore image metas and continue with that.
Edit: also for `images:streams check-upstream`

[images:streams] Skip fetching image meta if stream is given

---

doozer/doozerlib/cli/scan_fips.py

skip fips check for RPMs

---

doozer/doozerlib/rpm_delivery.py

Follows https://github.com/openshift-eng/ocp-build-data/pull/4722

Remove ship-okay tag

---

doozer/doozerlib/rpm_delivery.py

Reverts openshift-eng/art-tools#566

Revert "Remove ship-okay tag"

---

doozer/doozerlib/cli/scan_fips.py

Since otherwise we are looking at only the images in non-root context

sudo podman to see root images

---

pyartcd/pyartcd/pipelines/update_golang.py

https://issues.redhat.com/browse/ART-9253
Test run
https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/hack/job/sidsharm-aos-cd-jobs/job/build%252Fgolang-builder/25/console

ART-9253 update-golang: Support rebase and build

---

doozer/doozerlib/brew.py
elliott/elliottlib/brew.py

Fix tested in combination with 
https://github.com/openshift-eng/art-tools/pull/574
and https://gist.github.com/thegreyd/311eabef91689d6abbcf7b1c7fe4bf2e

Workaround for RHELBLD-15024

---

doozer/doozerlib/cli/scan_fips.py

In the cluster, we are creating the pod as root user, so we don't have to do `sudo`. But on the local, we have to. Creating a new function so that we prepend `sudo` only when necessary.

[fips] Dont sudo in root

---

doozer/doozerlib/metadata.py

This will help knowing which commit the component is pinned to 
Very helpful when Ctrl+F in logs by commit id

Log about pinning to commit

---

doozer/doozerlib/cli/scan_osh.py

- Exclude `ci-openshift-*` builds
- Exclude components preset in the exclusion [list](https://github.com/openshift-eng/ocp-build-data/blob/7d2e11afe7ac2ed530958d2bf74c499e5a7f788b/group.yml#L556)

[sast] update pipeline

---

doozer/doozerlib/cli/scan_osh.py

Before we were checking only for OCPBUGS workflow. Lets check for triggering scans as well

[sast] do not run for disabled versions

---

pyartcd/pyartcd/pipelines/gen_assembly.py

Don't get_inflight fro pre ga release

get inflight only apply for standard release

---

doozer/doozerlib/olm/bundle.py
pyartcd/pyartcd/pipelines/operator_sdk_sync.py

test job https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Folm_bundle/360/console

Fix olm bundle and operator-sdk job

---

art-cluster/pipelines/config/argocd/project/art-cd/common/image/build_base.yaml
art-cluster/pipelines/config/argocd/project/art-cd/common/image/build_latest.yaml
art-cluster/pipelines/config/argocd/project/art-cd/common/image/image.yaml
art-cluster/pipelines/data/project/art-cd/image/Containerfile.base
art-cluster/pipelines/data/project/art-cd/image/Containerfile.latest

Create new `Containerfile.latest` image so that we can update art-tools quickly

[artcluster] update base containerfile, add latest

---

pyartcd/pyartcd/pipelines/scan_fips.py
pyartcd/pyartcd/slack.py

Upload to slack from variable contents

[fips] Upload error as file, in slack

---

pyartcd/pyartcd/pipelines/scan_fips.py

[fips] ping issues to art-release

---

pyartcd/pyartcd/pipelines/scan_fips.py

Add triage docs to slack message. https://art-docs.engineering.redhat.com/sop/triage-fips/

[fips] add triage docs

---

pyartcd/pyartcd/pipelines/prepare_release.py

Since this causes issues with IIB

Error out when verify attached operator fails

---

pyartcd/pyartcd/pipelines/scan_fips.py

Since we could lose track of the messages in art-release, adding art-attention message as a prevention

[fips] fix slack message, add art-attention

---

doozer/doozerlib/cli/olm_bundle.py

fix https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/scheduled-builds/job/early-operator-index/320/console

fix find build return value

---

doozer/doozerlib/cli/scan_osh.py

At Hardik Vyas's [request](https://issues.redhat.com/browse/ART-9587?focusedId=24752424&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-24752424)

[sast] use custom-ocp profile

---

elliott/elliottlib/cli/find_builds_cli.py
elliott/elliottlib/cli/remove_builds_cli.py

Test find-builds:
```
echo sriov-network-operator-metadata-container-v4.16.0.202404221110.p0.g3b79f5e.assembly.stream.el9-7 | 
./elliott --assembly ec.6 -g openshift-4.16 find-builds -k image
```
[ashwin] Test remove-builds:
```
cat builds.txt | ./elliott --assembly rc.1 -g openshift-4.16 remove-builds --use-default-advisory image
```

Support stdin in elliott find-builds and remove-builds

---

art-cluster/pipelines/config/argocd/project/art-cd/fips-scanning/pipeline-task.yaml

The venv was causing issues with brew SSL auth

[fips-cluster] pin pip packages to task

---

doozer/doozerlib/cli/images_streams.py

quay.io image pullspec was previous being treated as a brew image and mangled. Allow full pullspecs to be mirrored.

Add ability to mirror quay / other registry images

---

doozer/doozerlib/cli/images.py

Skip config check for better testing on local

[konflux] skip config check

---

doozer/doozerlib/cli/images.py
doozer/doozerlib/distgit.py
doozer/doozerlib/k_distgit.py

Looks like using
```
k_dgr = KonfluxImageDistGitRepo(image_meta, dry_run=dry_run)
```
did not work with rebase. Modified to
```
k_dgr = image_meta.k_distgit_repo()
```

[konflux] fix rebase

---

elliott/functional_tests/test_create.py
pyartcd/config.example.toml

too bad it can't be art-bot...

elliott: joep is advisory owner

---

doozer/doozerlib/cli/scan_fips.py

- Skipping base images from scanning
- Refactor code

[fips] refactor code

---

elliott/elliottlib/errata_async.py
pyartcd/pyartcd/pipelines/prepare_release.py

- Reuse existing batch ID if the batch alreay exists
- Add --skip-batch to optionally skip batch creation/association
- Make batch operation reentrant and async
- Move `set_advisory_dependencies` and batch operations to somewhere after ocp-build-data update.

prepare-release: Reuse existing batch ID

---

pyartcd/pyartcd/pipelines/promote.py

Thread [here](https://redhat-internal.slack.com/archives/CNHC2DK2M/p1718795968624169)

set --import-mode=PreserveOriginal for tagging

---

doozer/doozerlib/cli/images_streams.py

Turns out, ART should not be in the business of editing go.mod. It is
strictly fine if the toolset version in go.mod is lower than the go
version that builds the project. Bumping the version in go.mod has
numerous side effects that the current naive implementation is not
taking care of. More importantly, most upstream projects get rebase
errors when getting their upstream in the release branches when this got
edited in between.

ART-9844: Stop editing go.mod

---

doozer/doozerlib/cli/scan_osh.py

Updating on [request](https://issues.redhat.com/browse/OSH-439?focusedId=24995197&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-24995197)

[sast] refactor to use --config=auto

---

pyartcd/pyartcd/constants.py
pyartcd/pyartcd/pipelines/rebuild.py
pyartcd/pyartcd/plashets.py
pyartcd/tests/pipelines/test_rebuild.py

Reverts openshift-eng/art-tools#717

Revert "ART-9503 Handle multiple plashet host locations"

---

pyartcd/pyartcd/pipelines/tag_rpms.py

for untag event use alert message type and add art-attention tag

ART-9555 update alert message for untag event

---

pyartcd/pyartcd/constants.py
pyartcd/pyartcd/pipelines/rebuild.py
pyartcd/pyartcd/plashets.py
pyartcd/tests/pipelines/test_rebuild.py

Reverts openshift-eng/art-tools#720

Revert "Revert "ART-9503 Handle multiple plashet host locations""

---

elliott/elliottlib/cli/find_bugs_golang_cli.py

Fix for `elliott find-bugs:golang`
```
File "/home/sid/Projects/art/art-tools/elliott/elliottlib/cli/find_bugs_golang_cli.py", line 356, in run
for fixed_in_version in self.flaw_fixed_in(flaw_bug):
TypeError: 'NoneType' object is not iterable
```
Right now if fixed_in_version field is not found in flaw bug, we 
error out (like this one https://bugzilla.redhat.com/show_bug.cgi?id=2292787) . Ignore it.
Test: `./elliott -g openshift-4.15 find-bugs:golang --analyze`

Ignore cve if fixed_in_version not found

---

ocp-build-data-validator/validator/json_schemas/image_content.base.schema.json

Support dockerfile_fallback option

[validator] update schema for dockerfile_fallback

---

pyartcd/pyartcd/pipelines/update_golang.py

Example PR: https://github.com/openshift-eng/ocp-build-data/pull/5041
Test:
./artcd -v --config config.example.toml update-golang --ocp-version=4.16 --art-jira=[ART-9927](https://issues.redhat.com//browse/ART-9927) golang-1.21.11-1.module+el8.10.0+21986+2112108a --confirm

Update-golang can update streams.yml

---

doozer/doozerlib/cli/scan_sources.py

There is a bug in `_is_pub_ancestor_of_priv` which doesn't interpret the exit code of `git merge-base` command correctly.
https://git-scm.com/docs/git-merge-base says
> Check if the first <commit> is an ancestor of the second <commit>, and exit with status 0 if true, or with status 1 if not. Errors are signaled by a non-zero status that is not 1.

Fix _is_pub_ancestor_of_priv

---

pyartcd/pyartcd/pipelines/update_golang.py

Builders are used across ocp versions, so 4.16 uses 1.21 builder as it's primary, and 
4.17 uses it as it's secondary. So given an ocp version check neighbouring versions,
and update them if needed

Update streams.yml for other versions that might have builder

---

pyartcd/pyartcd/jenkins.py
pyartcd/pyartcd/pipelines/promote.py

https://issues.redhat.com/browse/ART-9182
Test run: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fpromote-assembly/205/console
Should go with https://github.com/openshift-eng/aos-cd-jobs/pull/4196

ART-9182 Trigger rhcos_sync for ECs and GA

---

elliott/elliottlib/brew.py
elliott/elliottlib/cli/__main__.py
elliott/elliottlib/cli/attach_cve_flaws_cli.py
elliott/elliottlib/cli/find_bugs_blocker_cli.py
elliott/elliottlib/cli/find_bugs_golang_cli.py
elliott/elliottlib/cli/find_bugs_kernel_cli.py
elliott/elliottlib/cli/find_bugs_kernel_clones_cli.py
elliott/elliottlib/cli/find_builds_cli.py
elliott/elliottlib/cli/find_unconsumed_rpms.py
elliott/elliottlib/cli/rhcos_cli.py
elliott/elliottlib/cli/tag_builds_cli.py
elliott/elliottlib/cli/verify_attached_bugs_cli.py
elliott/elliottlib/cli/verify_cvp_cli.py
elliott/elliottlib/metadata.py
elliott/tests/test_early_kernel.py
elliott/tests/test_metadata.py

Follow up to https://github.com/openshift-eng/art-tools/pull/725

Remove runtime.logger refs in elliott

---

doozer/doozerlib/image.py

Fix for ([job](https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4_scan/50704/consoleFull))
```
-   changed: true
name: ci-openshift-golang-builder-latest.rhel8
reason: 'Outdated RPM grep-0:3.1-6.el8.x86_64 installed in ci-openshift-golang-builder-latest-container-v4.16.0-202407172305.p0.g2ed769e.assembly.stream.el8
(x86_64) when grep-0:3.6-5.el9.x86_64 was available in repo rhel-9-baseos-rpms-x86_64; ...
```
when we have [exempted](https://github.com/openshift-eng/ocp-build-data/blob/2ed769e2c98ecc09412712238a0af817fdbe2f94/images/ci-openshift-golang-builder-latest.rhel8.yml#L57) all rpms in 4.16 branch for this image
When we implemented exempt_rpms pattern matching in https://github.com/openshift-eng/art-tools/pull/237
we missed a …

Exempt rpms properly

---

artcommon/artcommonlib/assembly.py
doozer/doozerlib/cli/config_tag_rpms.py
doozer/doozerlib/rpm_delivery.py
doozer/tests/cli/test_config_tag_rpms.py
doozer/tests/cli/test_gen_payload.py
doozer/tests/test_assembly_inspector.py

removed leftovers of: early-kernel-ship-ok tag

removed early-kernel-ship-ok tag

---

pyartcd/pyartcd/s3.py

Follows https://github.com/openshift-eng/art-tools/pull/793
The options has to precede `--`, check job [logs](https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fpromote-assembly/219/consoleFull)

fix promote cloudflare command

---

elliott/elliottlib/cli/create_cli.py
elliott/elliottlib/errata_async.py
pyartcd/pyartcd/pipelines/prepare_release.py

Reverts openshift-eng/art-tools#792

Revert "Don't set publish date if batch is provided"

---

doozer/doozerlib/cli/olm_bundle.py

When invoking the command "olm-bundle:rebase-and-build" to build one nvr 
I noticed that the runtime initialization was taking a really long time (>10 minutes). This 
was before it even got to the bundle building part. This is because we were cloning all 
image distgits during init regardless of which NVRs were passed for building. 
This behavior isn't correct and wastes a lot of time when running this command locally 
so fix that. In case nvrs are given, fetch image names from nvrs and then init runtime 
with only those images.

Fix olm bundle command init

---

doozer/doozerlib/cli/scan_fips.py

Allow the doozer command to be run on test builds

[fips-scan] allow test builds

---

art-cluster/pipelines/config/argocd/project/art-cd/fips-scanning/pipeline-task.yaml
art-cluster/pipelines/config/argocd/project/art-cd/fips-scanning/pipeline.yaml
doozer/doozerlib/cli/scan_fips.py

- set default value
- skip non images

Fix fips scan

---

doozer/doozerlib/cli/scan_fips.py

- add await to clean images
- update error message

[fips-scan] update error message

---

doozer/doozerlib/cli/scan_fips.py

[fips-scan] fix log error

---

pyartcd/pyartcd/pipelines/rebuild_golang_rpms.py

related: https://github.com/openshift-eng/aos-cd-jobs/pull/4215
Test run: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Frebuild-golang-rpms/33/console

rebuild-golang-rpms: Add support for force rebuilding rpms

---

pyartcd/pyartcd/pipelines/build_sync.py

ref [thread](https://redhat-internal.slack.com/archives/CB95J6R4N/p1723146489209519)

for nightlies, set --import-mode=PreserveOriginal

---

pyartcd/pyartcd/pipelines/build_sync.py

Possible follow-up to https://github.com/openshift-eng/art-tools/pull/827

Use PreserveOriginal when re-triggering latest nightly

---

doozer/doozerlib/cli/images_okd.py

Supports: https://github.com/openshift-eng/ocp-build-data/pull/5236 .

Allow OKD-only images and references to quay.io images

---

doozer/doozerlib/cli/scan_fips.py

Previously, when retrieving the latest builds in a version for FIPS scan, doozer retrieved latest build per component per tag. This PR introduces logic to retrieve only the latest build for each component across all tags.

[ART-10376] Fix latest builds retrieval in FIPS scan

---

pyartcd/pyartcd/oc.py

Test run: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fpromote-assembly/277/console

Retry oc commands to rule out flakes

---

doozer/doozerlib/cli/scan_fips.py

exclude openshift-kubernetes-nmstate-handler-rhel-8-container since its moved to rhel9

[fips-scan] exclude openshift-kubernetes-nmstate-handler-rhel-8-container

---

doozer/doozerlib/brew.py

Test run: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Ftag-rpms/63637/

Retry on gss API login failure

---

art-cluster/pipelines/data/project/art-cd/image/Containerfile.base

Install `tkn` client and add it to path.

[fips-scan] tkn for cronjob

---

doozer/doozerlib/distgit.py
doozer/doozerlib/source_resolver.py
doozer/tests/test_distgit/test_generic_distgit.py
doozer/tests/test_source_resolver.py

This function is to get the upstream source directory for a component.

[ART-10504] Add helper function SourceResolver.get_source_dir

---

doozer/doozerlib/cli/scan_fips.py

Need to run as `sudo` in local dev env

[fips-scan] run as sudo if dev env

---

art-cluster/pipelines/data/project/art-cd/image/Containerfile.base

Test build: https://console-openshift-console.apps.artc2023.pc3z.p1.openshiftapps.com/k8s/ns/art-cd/builds/art-cd-base-test-2

ART-10297 art-cd: bump Python to 3.11

---

elliott/elliottlib/errata.py

Add a retry to fix this kind of flakes: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fbuild-microshift/788/console

Add a retry to Elliott get brew build

---

elliott/elliottlib/cli/find_builds_cli.py

Test
```
./elliott --data-path ../../ocp-build-data --group=openshift-4.12 --assembly 4.12.64 find-builds --payload --kind rpm
...
2024-08-27 09:53:06,047 art_tools.elliottlib.cli.find_builds_cli INFO Found 6 builds
cri-o-1.25.5-26.rhaos4.12.git635413a.el8
kernel-rt-4.18.0-372.119.1.rt7.279.el8_6
openshift-4.12.0-202408131833.p0.g1eb8682.assembly.stream.el8
openshift-4.12.0-202408131833.p0.g1eb8682.assembly.stream.el9
python-jinja2-3.0.1-3.el9.1
python-werkzeug-2.0.3-6.el9
```

find-builds: Do not filter out shipped builds if pinned

---

pyartcd/pyartcd/pipelines/scheduled/schedule_ocp4_scan.py

Backlinks are important, let's keep them

Restore ocp4_scan backlinks

---

pyartcd/pyartcd/pipelines/scheduled/schedule_ocp4_scan.py

Test build: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/hack/job/dpaolell/job/ocp4_scan/17/console
Triggered 4.7 and 4.11 (hacked aos-cd-jobs), failed on Jenkins API (not related with this change).

Refactor scheduled ocp4-scan

---

doozer/doozerlib/cli/scan_sources.py
pyartcd/pyartcd/jenkins.py

https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4_scan/69203/

ART-10609 Fix scan sources

---

doozer/doozerlib/cli/scan_sources.py

Test build: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4_scan/69801/console

scan-sources: return _thread_does_image_need_change() result

---

.devcontainer/Containerfile
.github/workflows/unit-tests.yaml
Makefile
doozer/.devcontainer/dev.Dockerfile
doozer/Makefile
doozer/tox.ini
elliott/.devcontainer/dev.Dockerfile
elliott/Makefile
elliott/tox.ini
ocp-build-data-validator/deploy/Dockerfile.base
ocp-build-data-validator/tox.ini
pyartcd/Makefile
pyartcd/tox.ini

As part of https://issues.redhat.com/browse/ART-10297

ART-10297 Move python3.8 references to 3.11

---

doozer/doozerlib/comment_on_pr.py

To verify if the message was posted correctly on the PR

log PR link after successful comment

---

doozer/doozerlib/cli/release_gen_payload.py
doozer/tests/cli/test_gen_payload.py
pyartcd/pyartcd/pipelines/build_sync.py

Reverts openshift-eng/art-tools#527

Revert "[ART-9330] [ART-8971] new embargo process"

---

elliott/elliottlib/bzutil.py

bug https://bugzilla.redhat.com/show_bug.cgi?id=2309710 has component with vulnerability-draft, we need to also include this type as flaw

update flaw bug search requirement

---

doozer/doozerlib/cli/images_streams.py

Reverts openshift-eng/art-tools#905

Revert "ART-10624: added new fields for automatically created JIRAS"

---

artcommon/artcommonlib/bigquery.py
artcommon/artcommonlib/constants.py
artcommon/artcommonlib/konflux/konflux_db.py
artcommon/artcommonlib/runtime.py
artcommon/tests/test_big_query.py
artcommon/tests/test_konflux_db.py

Ref. [ART-10829](https://issues.redhat.com/browse/ART-10829)
Test build: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/hack/job/dpaolell/job/ocp4/11/console
Needs to go along with https://github.com/openshift-eng/aos-cd-jobs/pull/4250

Move GCP project, dataset and table ID to art-tools constants

---

doozer/doozerlib/cli/release_gen_payload.py
doozer/tests/cli/test_gen_payload.py

replace of https://github.com/openshift-eng/art-tools/pull/930, fix tests

Filter out build only for stream assembly

---

artcommon/artcommonlib/constants.py
artcommon/artcommonlib/redis.py
pyartcd/pyartcd/locks.py
pyartcd/pyartcd/pipelines/promote.py
pyartcd/tests/pipelines/test_promote.py

Test build: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/hack/job/dpaolell/job/ocp4/12/console
Ref. [ART-10829](https://issues.redhat.com/browse/ART-10829)
Needs to go along with https://github.com/openshift-eng/aos-cd-jobs/pull/4251

Move redis port and hostname to art-tools

---

artcommon/artcommonlib/assembly.py

Reverts openshift-eng/art-tools#935

Revert "Fix for assembly inheritance"

---

pyartcd/pyartcd/slack.py

this function is not used now, it was added along with report-rhcos but that job is also deprecated now

deprecate upload_image

---

doozer/doozerlib/backend/konflux_image_builder.py

[konflux] add comment for annotation

---

pyartcd/pyartcd/signatory.py

ref https://github.com/sigstore/cosign/issues/3158

fix cosign error

---

doozer/doozerlib/cli/release_gen_payload.py

Reverts openshift-eng/art-tools#980

Revert "Fix sticky revert when annotation is not present"

---

doozer/doozerlib/backend/konflux_image_builder.py

This issue was introduced from
https://github.com/openshift-eng/art-tools/pull/955/files and https://github.com/openshift-eng/art-tools/pull/972/files, where a build error raises an exception and skips the line to set build_event.
This PR also adds distgit key to the log message to make troubleshooting easier.

konflux build: Fix a deadlock when waiting for failed parents

---

doozer/doozerlib/backend/konflux_image_builder.py
pyartcd/pyartcd/pipelines/ocp4_konflux.py

Add this option to skip the rebase step in the ocp4_konflux job.
This option has been discussed on the Konflux team call for testing purposes.

ocp4_konflux: Add --skip-rebase option

---

doozer/doozerlib/backend/konflux_image_build_pipelinerun.yaml
doozer/doozerlib/backend/konflux_image_builder.py

- Increase retries
- Increase PipelineRun time out

[konflux] PipelineRun fixes

---

doozer/doozerlib/cli/images_health.py

https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/scanning/job/scanning%252Fimages-health/1299/console

Fix images-health

---

art-cluster/pipelines/config/argocd/project/art-cd/quay-doomsday-backup/base/doomsday-pipeline-task.yaml
pyartcd/pyartcd/pipelines/quay_doomsday_backup.py

follow up https://github.com/openshift-eng/art-tools/pull/997

fix quay-doomsday-backup name

---

art-cluster/pipelines/config/argocd/project/art-cd/quay-doomsday-backup/base/doomsday-pipeline-task.yaml

Reverting for now, since issues on cluster

quay-doomsday revert to script

---

artcommon/artcommonlib/util.py

- Change auth headers from `{"Authorization": f"token {token}"}` to `{"Authorization": token}`
- Add a retry block (up to 3 retries, 10 seconds sleep)
- Add logs

Fix download_file_from_github(); add a retry

---

artcommon/artcommonlib/util.py

Looks like the `'token '` string was needed

Fix download_file_from_github() again

---

doozer/doozerlib/cli/release_gen_assembly.py
pyartcd/pyartcd/pipelines/gen_assembly.py

Alongside https://github.com/openshift-eng/art-docs/pull/197, https://github.com/openshift-eng/aos-cd-jobs/pull/4266

deprecate advance release

---

artcommon/artcommonlib/bigquery.py

Follows https://github.com/openshift-eng/art-tools/pull/1034

Log Konflux queries with INFO level

---

art-cluster/pipelines/config/argocd/project/art-cd/quay-doomsday-backup/base/doomsday-pipeline-task.yaml
pyartcd/pyartcd/pipelines/quay_doomsday_backup.py

Use @adobes1's quay doomsday backup artcd command

[cluster] use artcd for quay backup

---

pyartcd/pyartcd/pipelines/build_microshift.py

fix `slack_sdk.errors.SlackRequestError: file parameter must be any of filepath, bytes, and io.IOBase`

Update path object to str

---

doozer/doozerlib/backend/konflux_image_builder.py

Apply an NVR tag for output images for convenience.

Konflux: Apply addtional-tags for output images

---

doozer/doozerlib/backend/rebaser.py

This function has changed to be async.

Fix konflux_db.get_latest_build calls

---

doozer/doozerlib/backend/konflux_image_builder.py

Follows https://github.com/openshift-eng/art-tools/pull/1053
```
,"details":{"name":"openshift-4-18-ose-cluster-kube-storage-version-migrator-operator","group":"appstudio.redhat.com","kind":"Component","causes":[{"reason":"FieldValueTooLong","message":"Too long: may not be longer than 63","field":"spec.componentName"}]}
````
Kubernetes resources has a maximum character length of [63 characters](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-label-names)

[konflux] reduce character name for Components

---

artcommon/artcommonlib/util.py
doozer/doozerlib/cli/images_okd.py
doozer/doozerlib/cli/scan_sources_konflux.py

Ref. [ART-11060](https://issues.redhat.com/browse/ART-11060)

[konflux] ART-11060 scan for config changes

---

doozer/doozerlib/backend/konflux_image_builder.py

Changes in the PR:
-  cosign and DB were storing all the arches defined for an image, instead of storing the arches that we are actually building for. 
- Temporarily do not fail for unsupported arches until we are on the new cluster
Test run [succeeded](https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4-konflux/231/console)

[konflux] fix bug arches

---

ocp-build-data-validator/validator/json_schemas/image_config.base.schema.json

For https://github.com/openshift-eng/ocp-build-data/pull/5564

[validator] update validator for Konflux field

---

doozer/doozerlib/cli/images_streams.py

ref https://issues.redhat.com/browse/ART-9249
Setting this will prevent the bug from showing up in the customer portal.

[ART-9249] Set reconciliation bugs as RH employee

---

doozer/doozerlib/cli/release_gen_payload.py

in parallel with this:
https://github.com/openshift/release/pull/58152

Set multi cadence to 6 hrs

---

doozer/doozerlib/cli/scan_sources_konflux.py
doozer/doozerlib/metadata.py
pyartcd/pyartcd/__main__.py
pyartcd/pyartcd/jenkins.py
pyartcd/pyartcd/pipelines/ocp4_scan_konflux.py
pyartcd/pyartcd/util.py

Ref. [ART-11168](https://issues.redhat.com/browse/ART-11168)
Needs https://github.com/openshift-eng/aos-cd-jobs/pull/4275

ART-11168 Add ocp4-scan for konflux artcd pipeline

---

doozer/doozerlib/cli/scan_sources_konflux.py

Ref. [ART-11061](https://issues.redhat.com/browse/ART-11061)

ART-11061 Scan for changes in an image's dependencies

---

doozer/doozerlib/cli/scan_sources_konflux.py

`scan_image()` runs a sequence of checks on each image to be scanned. As soon as a reason to rebuild is found, scan_image should return to avoid redundant checks on already changing image. Besides, `scan_image()` itself should be skipped if the image is already marked as changed (maybe because an ancestor has been found in need to rebuild, hence all its children have been marked as well).
This is obtained by introducing a `skip_check_if_changing` decorator that checks if the image is already marked as changing, and skips the check if that's the case.
An extra field is added within the `scan_images()` function that starts a pool of asynchronous `scan_image()` tasks. This prevents querying the Konflux DB to fetch latest builds for those images that are already marked as changing.
This …

Optimize checks when scanning images

---

artcommon/artcommonlib/konflux/konflux_db.py
artcommon/tests/test_konflux_db.py

Due to time drift between systems (Konflux and buildvm / local), a build which finishes can be missed 
when queried for immediately.
```
2024-11-08 15:02:16,769 artcommonlib.bigquery INFO Executing query: INSERT INTO `openshift-art.events.builds` 
(... `start_time`, `end_time`, ...) VALUES (... '2024-11-08T14:43:14', '2024-11-08T15:02:31', ...)
```
Here you can see, the log statement at `15:02:16` inserting that the build finished at `15:02:31`
So there is a 15 sec time difference between konflux and buildvm.
https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/hack/job/sidsharm-aos-cd-jobs/job/build%252Fbuild-microshift-bootc/3/console

find konflux builds: Do not constrain by end time in default search

---

doozer/doozerlib/backend/konflux_image_build_pipelinerun.yaml

To satisfy Enterprise Contract checks
Follows https://github.com/openshift-priv/art-konflux-template/pull/27

[konflux] Bump task SHAs

---

artcommon/artcommonlib/constants.py
doozer/doozerlib/telemetry.py
pyartcd/pyartcd/telemetry.py

define default value for sending traces, allow to override it via env variables

Add default value for otel endpoint

---

doozer/doozerlib/cli/scan_sources_konflux.py

test build: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4-scan-konflux/104/console

Fix ocp4-scan-konflux

---

pyartcd/pyartcd/pipelines/ocp4_konflux.py

Sometimes we need to run other builds even though the lock is held by one job, if we know for sure that there is no conflict.
Alongside https://github.com/openshift-eng/aos-cd-jobs/pull/4304

[konflux] add ignore locks function

---

doozer/doozerlib/backend/rebaser.py

Test jenkins [run](https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4-konflux/437/console)
Rebase [worked](https://github.com/openshift-priv/azure-service-operator/commit/c9eb506b89d6e3b314c0a9accfc7d562cd795416#diff-2f754321d62f08ba8392b9b168b83e24ea2852bb5d815d63e767f6c3d23c6ac5L14)

ART-11506: [konflux] update dockerignore to include oit dir

---

doozer/doozerlib/backend/konflux_image_builder.py

All arches are now supported, we can limit them if needed with the `LIMIT_ARCHES` param if necessary

[konflux] support all arches

---

pyartcd/pyartcd/pipelines/ocp4_scan_konflux.py

Follows https://github.com/openshift-eng/art-tools/pull/1178

[konflux] Enable all arches

---

pyartcd/pyartcd/pipelines/build_sync.py

Printing the assembly issues in slack is very useful, but as the report tend to be long repeated failures make the channel less readable. Proposing to print the report in the thread instead of being part of the main message

build-sync: when notifying failures, print the report in a slack thread

---

doozer/doozerlib/backend/konflux_client.py

Another process may create the same resource at the same time. Ignore this kind of error.

Konflux: Ignore ConflictError when creating a resource

---

doozer/doozerlib/backend/konflux_image_build_pipelinerun.yaml

From https://github.com/openshift-priv/art-konflux-template/pull/30

[konflux] bump task ref SHAs

---

pyartcd/pyartcd/pipelines/prepare_release.py

the batch release should align with advisory config, so load from erratatool.yml to get it aligned instead of using hardcode value.
In 4.13 the advisory release is updated to use "RHOSE ASYNC - Silent Release - AUTO"

load batch relase from config

---

pyartcd/pyartcd/pipelines/prepare_release.py

related to https://github.com/openshift-eng/art-tools/pull/1162

use global yaml

---

doozer/doozerlib/backend/konflux_image_builder.py

building_arches check moved to KonfluxClient.

konflux: a cleanup

---

doozer/doozerlib/backend/konflux_image_build_pipelinerun.yaml

To pull this fix in https://github.com/konflux-ci/build-definitions/pull/1737
Urgent for microshift-bootc

[konflux] bump task SHA

---

pyartcd/pyartcd/pipelines/ocp4_konflux.py

ocp4-konflux: update build title with group and `[TEST]` (if applicable)
Needs https://github.com/openshift-eng/aos-cd-jobs/pull/4307

Update the build title with version

---

pyartcd/pyartcd/pipelines/ocp4_konflux.py

Needs https://github.com/openshift-eng/aos-cd-jobs/pull/4311

ocp4-konflux: define "except" build strategy

---

artcommon/artcommonlib/konflux/konflux_build_record.py

Add KonfluxRecord.__repr__ to help displaying of builds in debugger

---

doozer/doozerlib/backend/konflux_image_builder.py

Follows https://github.com/openshift-eng/art-tools/pull/1213

[konflux] fix param

---

doozer/doozerlib/backend/konflux_client.py

Follows https://github.com/openshift-eng/art-tools/pull/1213

[konflux] fix minor param bug

---

art-cluster/pipelines/data/project/art-cd/image/Containerfile.base

Same as https://github.com/openshift-eng/art-tools/pull/879

art-cd: bump Python to 3.11

---

art-cluster/cloudflare/package-lock.json
art-cluster/cloudflare/package.json
art-cluster/cloudflare/src/index.ts

- update packages
- formatting

avoid forwarding user-supplied headers unconditionally

---

pyartcd/pyartcd/pipelines/ocp4_konflux.py

tested, [works](https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4-konflux/639/console)

[konflux] fix plr template override bug

---

art-cluster/pipelines/config/argocd/project/art-cd/quay-doomsday-backup/base/doomsday-pipeline-task.yaml

Follows https://github.com/openshift-eng/art-tools/pull/1170

[art-cluster] update art-cd config

---

pyartcd/pyartcd/pipelines/quay_doomsday_backup.py
pyartcd/pyartcd/slack.py

Reverts openshift-eng/art-tools#1170

Revert "Make quay-doomsday-backup async and send its results to Slack"

---

doozer/doozerlib/backend/rebaser.py

Move config digest calculation before we replace the Dockerfile

[konflux] override dockerfile after digest calculation

---

doozer/doozerlib/backend/rebaser.py

do not error out if dir already exists

[konflux] fix missing dir issue

---

doozer/doozerlib/backend/rebaser.py

The commented lines can be seen here: https://github.com/openshift-priv/console/blob/art-openshift-4.19-assembly-test-dgk-openshift-enterprise-console/Dockerfile#L46-L58

[konflux] comment out cachito lines during rebase

---

doozer/doozerlib/cli/images_health.py
pyartcd/pyartcd/pipelines/images_health.py

Sample messages: https://redhat-internal.slack.com/archives/C06625LHXQS/p1735820058044429

images-health: notify about Konflux failures too

---

doozer/doozerlib/cli/scan_sources_konflux.py

- check if any ART-managed RPMs need to be rebuilt because a new upstream commit exists.
- for all image metas, check if their installed packages include any of the changed ART built RPMs, and mark them for rebuild

ART-11063 Check for changes in ART built RPMs

---

doozer/doozerlib/backend/rebaser.py

Sometimes there will be && `yarn install ...` command, following the commented out lines. So replace the leading && with RUN, since we comment that out earlier
Follows https://github.com/openshift-eng/art-tools/pull/1244

[konflux] comment out cachito lines during rebase fix

---

doozer/doozerlib/backend/rebaser.py

Rebased line for review: https://github.com/openshift-priv/networking-console-plugin/blob/art-openshift-4.19-assembly-stream-dgk-networking-console-plugin/Dockerfile#L24
Follows: https://github.com/openshift-eng/art-tools/pull/1244
- Download yarn if its missing, instead of erroring out

[konflux] download yarn if missing, function refactor

---

doozer/doozerlib/cli/images_health.py

Follows https://github.com/openshift-eng/art-tools/pull/1253

images-health follow-up

---

doozer/doozerlib/rpm_builder.py

Test build https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4/13454/console stored the commitish in BigQuery:
```
SELECT commitish
FROM `openshift-art.events.builds`
WHERE start_time > TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 300 DAY)
AND `group` = 'openshift-4.14'
AND name = 'openshift-kuryr'
AND artifact_type = 'rpm'
ORDER BY start_time DESC
LIMIT 1;
```
yields `8926a294348d3791040748774b0ac0892b968494`

rpms: add changelog section to specfiles if missing

---

doozer/doozerlib/backend/rebaser.py

For https://github.com/openshift-eng/ocp-build-data/pull/5965

[konflux] cachito fix

---

artcommon/artcommonlib/konflux/konflux_db.py

successful test build: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4-scan-konflux/6479/console

Make start_search tz aware

---

doozer/doozerlib/cli/__init__.py
doozer/doozerlib/cli/scan_sources.py
doozer/doozerlib/metadata.py

Test build: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4_scan/97351/console

Define common entrypoint for metadata.get_latest_build

---

elliott/elliottlib/cli/find_bugs_kernel_clones_cli.py

Test build: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fscan-for-kernel-bugs/14274/console

Add retries to jira issue fetch

---

doozer/doozerlib/cli/release_gen_payload.py
pyartcd/pyartcd/pipelines/build_sync.py

Test run: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/hack/job/sidsharm-aos-cd-jobs/job/build%252Fbuild-sync/6/

Differentiate between unviable and failed build-sync run in title

---

artcommon/artcommonlib/runtime.py
doozer/doozerlib/backend/rebaser.py
doozer/doozerlib/cli/__init__.py
doozer/doozerlib/cli/images_konflux.py
doozer/doozerlib/runtime.py

Rebase commit https://github.com/openshift-priv/ironic-image/commit/e43a956d3d899412d97d0a221e05b5dd89fe9d0d
Test build: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4-konflux/2151/console

Get latest k build follow up

---

doozer/doozerlib/backend/konflux_client.py
doozer/doozerlib/backend/konflux_image_builder.py
doozer/doozerlib/backend/rebaser.py

Reverts openshift-eng/art-tools#1280

Revert "[konflux] network modes"

---

doozer/doozerlib/cli/release_gen_assembly.py
doozer/tests/cli/test_gen_assembly.py
pyartcd/pyartcd/pipelines/gen_assembly.py

add a gen-microshift parameter for gen-assembly command, unless it set true we will not create microshift entry in assembly config

[ART-11852] add microshift flag for gen assembly job

---

doozer/doozerlib/backend/konflux_client.py

Images will not be purged, if we do not specify images-expires-after

[konflux] persist images on quay repo

---

doozer/doozerlib/util.py

Give the sync version of oc_image_info the same auth capabilities that the async version already has.

Give oc_image_info() auth powers

---

elliott/elliottlib/cli/find_bugs_golang_cli.py

Make sure bugs have a valid cve_id otherwise the command crashes later.

[find-bugs:golang] Validate cve_id is set or skip

---

doozer/doozerlib/backend/rebaser.py

Ref. https://issues.redhat.com/browse/ART-11911
Test build: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4-konflux/3358/console

Fix update .dockerignore

---

doozer/doozerlib/cli/release_gen_payload.py

We are seeing a lot of EOF errors from quay. I triggered a test run by disabling async executions for the 
oc adm release new command and it looks to have worked. The hypothesis being that the async runs 
are resulting in the registry EOF errors.
https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fbuild-sync/14337/console using https://github.com/openshift-eng/art-tools/pull/1316/files

Run oc adm release new in sync mode

---

pyartcd/pyartcd/pipelines/ocp4_konflux.py

To fix this:
```
sync_images
exclude_arches = json.loads(out.strip())
^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib64/python3.11/json/__init__.py", line 346, in loads
return _default_decoder.decode(s)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib64/python3.11/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib64/python3.11/json/decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
```

ocp4-konflux: fix parse arches from group config

---

doozer/doozerlib/backend/rebaser.py

See
https://redhat-internal.slack.com/archives/C06Q309QUDV/p1739311993366579 for more info.

Konflux: Fix race condition in KonfluxRebaser

---

doozer/doozerlib/cli/scan_sources_konflux.py
pyartcd/pyartcd/pipelines/ocp4_scan_konflux.py

Reverts openshift-eng/art-tools#1304
Continuously build all arches

Revert "[konflux] Build only for x86 for now"

---

doozer/doozerlib/backend/konflux_client.py

ref [thread](https://redhat-internal.slack.com/archives/C06Q309QUDV/p1739502929506729)
Test [build](https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4-konflux/5110/console)

[konflux][ART-11576] refspec fix

---

pyartcd/pyartcd/pipelines/build_microshift_bootc.py

The pullspecs should refer to the public repo. In case of embargo, we don't sync those files at all.
Also the local bootc-pullspec.txt files will be created in TemporaryDirectory to avoid potential race condition.
Tested with https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fbuild-microshift-bootc/57/

microshift-buildc: bootc-pullspec.txt fixes

---

pyartcd/pyartcd/pipelines/update_golang.py

based on https://github.com/openshift-eng/art-tools/pull/1334
- Fix incorrect dictionary initialization syntax for builder_nvrs
- Fix comparison logic for go_version checks using 'in' operator
- Fix iteration over builder_nvrs using .items()
- Fix streams_content iteration to properly access nested dictionary
- Fix variable name conflict by renaming 'branch' to 'fork_branch'
- Add slack message info for important changes

Fix bugs in update_golang pipeline

---

doozer/doozerlib/backend/rebaser.py

- Copy base repo content into app/ directory
- Create .npmrc when NPM package manager is enabled
- Create registry-ca.pem

Improve cachito emulation mode for cachi2

---

elliott/elliottlib/cli/find_builds_cli.py

Address the issue discussed at https://redhat-internal.slack.com/archives/C07BD2S0XRN/p1740036756003709

elliott find-builds: skip builds that have no accepted brew tags

---

doozer/doozerlib/backend/rebaser.py

1. components should have tagging modes in metadata; tagging_mode:  `disabled | enabled | legacy` .
2. images should default to `disabled` / not tagging the repo (to reduce unnecessary noise)
3. `enabled`, for images, would be the new standard, including `+`.
4. `legacy`, for images, would not include the `+` .
5. rpms components should default to using `legacy`
ref [thread](https://redhat-internal.slack.com/archives/C06Q309QUDV/p1740423830628779) for details

[konflux] tagging mode

---

pyartcd/pyartcd/pipelines/build_sync.py

- create separate fail counters for Brew and Konflux
- explicitly state which build system failed to assemble a payload in pings
- do not ping public channels for Konflux (yet)
Ref. [ART-12161](https://issues.redhat.com/browse/ART-12161)

ART-12161 Handle brew/konflux sync failures separately

---

doozer/doozerlib/cli/release_gen_payload.py
pyartcd/pyartcd/pipelines/prepare_release.py

Reverts openshift-eng/art-tools#1355
build-sync failed due to this https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fbuild-sync/15291/console

Revert "ART-9439 - modifications in prepare-release"

---

artcommon/artcommonlib/konflux/konflux_build_record.py
artcommon/artcommonlib/util.py
doozer/doozerlib/backend/konflux_client.py
doozer/doozerlib/backend/konflux_image_builder.py

There is a master 12h spec.timeout set in the pipelinerun by doozer, but this is far more generous that we need in practice.  Allow each image metadata to specify a timeout in minutes like `konflux.build_timeout: 60` or default to 5 hours (enforced by doozer itself).  Doozer will also cancel the pipelinerun if it detects that a pod has been pending for over an hour.

Add configurable timeouts to pipelineruns

---

doozer/doozerlib/backend/konflux_client.py

Contained more arguments than %s substitutions.

Fixing logging message

---

artcommon/artcommonlib/constants.py
artcommon/artcommonlib/konflux/konflux_build_record.py
artcommon/artcommonlib/konflux/konflux_db.py
artcommon/tests/test_konflux_db.py
doozer/doozerlib/backend/konflux_olm_bundler.py
doozer/tests/backend/test_konflux_olm_bundler.py

- Adds bundle_package_name and bundle_csv_name fields to KonfluxBundleBuildRecord
- Adds KonfluxFbcBuildRecord for FBC build
- Fix type annotation for `add_build`.

artcommon: Update Konflux DB classes

---

artcommon/artcommonlib/metadata.py
artcommon/artcommonlib/runtime.py
elliott/tests/test_imagecfg.py

Konflux image builds do not have `-container` suffix. So adjust for that

Fix image component for Konflux builds

---

pyartcd/pyartcd/locks.py
pyartcd/pyartcd/pipelines/ocp4.py
pyartcd/pyartcd/pipelines/ocp4_konflux.py
pyartcd/pyartcd/util.py

Test build : https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4-konflux/5735/console

[konflux] add a mass rebuild lock

---

pyartcd/pyartcd/pipelines/build_microshift.py

Fix https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fbuild-microshift/1898/

build-microshift: Don't ping release artists

---

pyartcd/pyartcd/pipelines/scheduled/schedule_ocp4_scan_konflux.py

Reverts openshift-eng/art-tools#1442

Revert "Konflux: only scan 4.19"

---

doozer/doozerlib/backend/konflux_image_builder.py

Test
```
doozer --group openshift-4.18 --assembly 4.18.2 --latest-parent-version -i microshift-bootc 
--lock-upstream microshift-bootc HEAD beta:images:konflux:build 
--image-repo quay.io/redhat-user-workloads/ocp-art-tenant/art-images 
--konflux-kubeconfig ~/konflux.kubeconfig.priv --dry-run
...
ValueError: Successful NVR build microshift-bootc-v4.18.0-202503121435.p0.gc0eec47.assembly.4.18.2.el9 
already exists in DB! To rebuild, please do another rebase
```

Restrict rebuilding same nvr in konflux

---

doozer/doozerlib/backend/rebaser.py
doozer/tests/backend/test_konflux_cachi2.py
doozer/tests/backend/test_rebaser.py

ref ticket: https://issues.redhat.com/browse/ART-12120

[ART-12120][konflux] root permissions required for repo management

---

doozer/doozerlib/backend/rebaser.py

Follow up to https://github.com/openshift-eng/art-tools/pull/1314
[Test build](https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4-konflux/6133/console)

merge konflux config before rebase

---

doozer/doozerlib/cli/scan_sources.py

Test build: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4_scan/114215/console

[TEMP] Disable RPM check until pulp is up again

---

doozer/doozerlib/cli/scan_sources.py

Reverts openshift-eng/art-tools#1459

Revert "[TEMP] Disable RPM check until pulp is up again"

---

doozer/doozerlib/backend/rebaser.py
doozer/tests/backend/test_rebaser.py

ref [thread](https://redhat-internal.slack.com/archives/C06Q309QUDV/p1742914239326569?thread_ts=1742477914.887549&cid=C06Q309QUDV)

[konflux] fix yum line rebase

---

artcommon/artcommonlib/konflux/konflux_db.py
doozer/doozerlib/cli/release_gen_payload.py
doozer/tests/cli/test_gen_payload.py

Test build: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fbuild-sync/16256/console

[konflux] sync private builds

---

artcommon/artcommonlib/konflux/package_rpm_finder.py
doozer/doozerlib/build_info.py
doozer/doozerlib/cli/release_gen_payload.py

Test build: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fbuild-sync/16261/consoleFull

FIx installed RPMs check for Konflux

---

doozer/doozerlib/backend/rebaser.py

Follows https://github.com/openshift-eng/art-tools/pull/1480

[konflux] strip after checking go version

---

artcommon/artcommonlib/metadata.py
doozer/doozerlib/backend/rebaser.py

https://github.com/openshift-eng/art-tools/pull/1446#issuecomment-2738165059

[konflux] fix component_name

---

doozer/doozerlib/cli/release_gen_payload.py
pyartcd/pyartcd/pipelines/prepare_release.py

This reverts commit 974a4bd26676390650a4b35e4b383805e93855d7.

ART-9439 - fixes after rebase

---

doozer/doozerlib/backend/konflux_client.py
doozer/tests/backend/test_konflux_client.py

Follows https://github.com/openshift-eng/art-tools/pull/1491

[konflux] ui fix

---

artcommon/artcommonlib/konflux/package_rpm_finder.py
doozer/doozerlib/build_info.py
doozer/doozerlib/cli/release_gen_payload.py

Test build: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fbuild-sync/17020/console

[konflux] build-sync: enable check RHCOS consistency

---

doozer/doozerlib/cli/release_gen_payload.py

Test build: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fbuild-sync/17084/console

[konflux] gen-payload: enable all checks

---

doozer/doozerlib/cli/get_nightlies.py
doozer/doozerlib/runtime.py

Tested with:
```
$ doozer --group=openshift-4.18 --assembly=stream --build-system=konflux get-nightlies
4.18.0-0.konflux-nightly-arm64-2025-04-09-095620 4.18.0-0.konflux-nightly-2025-04-09-093813
```

[konflux] let doozer get-nightlies look at Konflux payloads

---

doozer/doozerlib/backend/konflux_client.py

`sast-shell-check` task failing without an error being reported. Increasing the memory seems to have fixed it.
ref slack [thread](https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1744126283427319) for details.

[konflux] more memory for sast task

---

doozer/doozerlib/distgit.py

Ref. [ART-12585](https://issues.redhat.com/browse/ART-12585)

ART-12585 Make cachito version configurable

---

pyartcd/pyartcd/pipelines/update_golang.py

Test run: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fgolang-builder/130/console
resulting PR: https://github.com/openshift-eng/ocp-build-data/pull/6504/files

Register and check stream aliases

---

elliott/elliottlib/bzutil.py
elliott/elliottlib/cli/attach_cve_flaws_cli.py
elliott/tests/test_util.py

Re: https://github.com/openshift-eng/ocp-build-data/pull/6553

Support multiple target releases for same MAJOR.MINOR

---

artcommon/artcommonlib/constants.py
artcommon/artcommonlib/gitdata.py
artcommon/artcommonlib/util.py
elliott/elliottlib/cli/common.py
elliott/elliottlib/cli/konflux_release_cli.py
elliott/elliottlib/cli/snapshot_cli.py
elliott/elliottlib/runtime.py
elliott/elliottlib/shipment_model.py
elliott/tests/test_konflux_release_cli.py
elliott/tests/test_snapshot_cli.py
ocp-build-data-validator/validator/json_schemas/shipment.schema.json

Shipment spec: https://docs.google.com/document/d/1caxU39_tRMNXKMlcGiQvRJwBdBN22MKtRisFim5XiT8/edit?tab=t.0
- Create shipment config using https://github.com/openshift-eng/art-tools/pull/1504
- Commit to your shipment Gitlab fork branch. Create an MR to your official shipment-repo where ART's Gitlab CI automation is running.
-  Gitlab CI validates shipment config and triggers job (for each shipment yaml in MR) in Jenkins to run the following command to cut a release. 
- Releases get created. CI reports back on job statuses and follows up appropriately.
- Regular shipment pipelines: https://gitlab.cee.redhat.com/hybrid-platforms/art/ocp-shipment-data/-/merge_requests/13/pipelines
- FBC shipment pipelines: https://gitlab.cee.redhat.com/hybrid-platforms/art/ocp-shipment-data/-/merge_requests/ …

Konflux - elliott release new

---

elliott/elliottlib/cli/__main__.py
elliott/elliottlib/cli/shipment_cli.py
elliott/elliottlib/shipment_model.py

Output a shipment config, optionally based on an erratatool.yml advisory-key
```
elliott -g openshift-4.18 --assembly 4.18.3 shipment init --advisory-key microshift
```

elliott shipment init

---

doozer/doozerlib/backend/rebaser.py

Follows https://github.com/openshift-eng/art-tools/pull/1523
Builds < 4.17 seems to be failing. Since we don't want this to be applied for all version, setting it at a group level
Alongside https://github.com/openshift-eng/ocp-build-data/pull/6582

[konflux] append gomod patch

---

doozer/doozerlib/backend/konflux_client.py

Since they are being switched to static VMs: https://github.com/redhat-appstudio/infra-deployments/pull/6181

[konflux] ppc to default flavor for static

---

pyartcd/pyartcd/util.py

To fix errors like [this](https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fbuild-sync-konflux/614/console):
```
File "/mnt/jenkins-workspace/_builds_build_build-sync-konflux/art-tools/pyartcd/pyartcd/util.py", line 210, in branch_arches
return group_config['konflux']['arches']
~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'arches'
```

Fix pyartcd.util.branch_arches()

---

doozer/doozerlib/cli/scan_sources.py
doozer/doozerlib/rhcos.py
doozer/tests/cli/test_scan_sources.py
doozer/tests/test_rhcos.py

Reverts openshift-eng/art-tools#1537

Revert "Revert "ART-12288: Support new rhcos node image and extensions""

---

doozer/doozerlib/source_modifications.py

The build system doesn't seem to be available always, default to brew if its missing

Fix modification error

---

Makefile
elliott/elliottlib/shipment_model.py
ocp-build-data-validator/validator/json_schemas/shipment.schema.json

Needed for https://github.com/openshift-eng/art-tools/pull/1546/files

Add liveID in shipment config

---

pyartcd/pyartcd/runtime.py

Follow up to https://github.com/openshift-eng/art-tools/pull/920
This is a fix to logs not showing up in debug.log

Fix pyartcd logging bug

---

doozer/doozerlib/cli/release_gen_assembly.py
doozer/doozerlib/cli/scan_sources.py
doozer/doozerlib/rhcos.py

Reverts openshift-eng/art-tools#1525

Revert "ART-12600: use group config to check layered rhcos"

---

doozer/doozerlib/backend/konflux_image_builder.py

rstrip will cut the nvr, should use removesuffix

fix nvr issue

---

doozer/doozerlib/cli/scan_sources_konflux.py

Follows https://github.com/openshift-eng/art-tools/pull/1570

[konflux] fix scan_network_mode_changes equality

---

pyartcd/pyartcd/pipelines/rebuild_golang_rpms.py

Similar issue to https://github.com/openshift-eng/art-tools/pull/1598

replace rstrip with removesuffix

---

doozer/doozerlib/backend/konflux_olm_bundler.py
doozer/tests/backend/test_konflux_olm_bundler.py

Follows https://github.com/openshift-eng/art-tools/pull/1527

Fix konflux OLM bundle builds

---

artcommon/artcommonlib/konflux/konflux_db.py

Temporarily add a fallback until we know for sure all builds have `-container` in their NVRs

add fallback for konflux builds

---

artcommon/artcommonlib/konflux/konflux_db.py

Reverts openshift-eng/art-tools#1605

Revert "add fallback for konflux builds"

---

doozer/requirements.txt
elliott/pyproject.toml
pyartcd/requirements.txt

Pinning `click` until https://github.com/pallets/click/pull/2912 gets merged (ref. https://github.com/pallets/click/issues/2897)

Fix elliott create cli

---

elliott/elliottlib/cli/konflux_release_cli.py

Log the URL so that we can navigate quickly to the UI page

log Release URL

---

doozer/doozerlib/backend/konflux_client.py

In case of a network outage, KonfluxClient may hang indefinitely without raising any exception. Adding request timeouts should resolve this issue.
See
https://redhat-internal.slack.com/archives/GDBRP5YJH/p1747817430982149 and https://github.com/kubernetes-client/python/blob/master/examples/watch/timeout-settings.md.

[Konflux] Add request timeouts to all API calls

---

doozer/doozerlib/backend/konflux_olm_bundler.py
doozer/tests/backend/test_konflux_olm_bundler.py

https://github.com/openshift-eng/art-tools/pull/1596 still has a few leftovers, which results in wrong NVR record.

Konflux: Fix NVR handling leftovers

---

pyartcd/pyartcd/pipelines/ocp4_konflux.py

Ref. [ART-13013](https://issues.redhat.com/browse/ART-13013)

ART-13013 ocp4_konflux: store rebase failures in Redis

---

pyartcd/pyartcd/__main__.py
pyartcd/pyartcd/jenkins.py
pyartcd/pyartcd/pipelines/build_microshift_bootc.py
pyartcd/pyartcd/pipelines/build_plashets.py
pyartcd/pyartcd/pipelines/ocp4.py
pyartcd/tests/pipelines/test_ocp4.py
pyartcd/tests/pipelines/test_plashets.py

Test build for 4.20 and `test` assembly: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/hack/job/dpaolell/job/build-plashets/5/console
Needs https://github.com/openshift-eng/aos-cd-jobs/pull/4405

Build plashets in a dedicated Jenkins job

---

pyartcd/pyartcd/pipelines/ocp4.py
pyartcd/tests/pipelines/test_ocp4.py

Test build: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4/19152/console

Fix skipping plashets for KONFLUX_IMAGESTREAM_OVERRIDE_VERSIONS

---

doozer/doozerlib/cli/scan_fips.py

Add `--retry` option to FIPS scan pipeline to retry the scan for failing NVRs. This should hopefully decrease the number of false positives

Add retry option to FIPS scan pipeline

---

pyartcd/pyartcd/pipelines/prepare_release.py
pyartcd/pyartcd/pipelines/prepare_release_konflux.py

Fix error seen at: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fprepare-release/843/console
Test build: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fprepare-release/844/console

Fix assembly merger in prepare-release

---

doozer/doozerlib/rhcos.py

Follow-up of https://github.com/openshift-eng/art-tools/pull/1689

Fix non-layered-rhcos detection

---

.devcontainer/Containerfile
.devcontainer/devcontainer.json
.devcontainer/docker-compose.yaml

Enhance the Containerfile and devcontainer configuration to streamline the development environment setup, including updated dependencies and user permissions. Adjustments to the docker-compose file improve integration with local configurations.

Refactor devcontainer setup for improved environment configuration

---

doozer/doozerlib/cli/scan_sources.py
doozer/doozerlib/rhcos.py

Test build: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4_scan/138179/console

Fix scan-sources

---

pyartcd/pyartcd/__main__.py
pyartcd/pyartcd/pipelines/art_notify.py
pyartcd/requirements.txt

Rebase failure notification: https://redhat-internal.slack.com/archives/C08J61YQNMU/p1750080797484279

ART-13013 Move art-notify to pyartcd

---

doozer/doozerlib/cli/release_gen_assembly.py
doozer/tests/cli/test_gen_assembly.py

Test builds:
- [4.20 ec.3](https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fgen-assembly/590/console) produced:
```yaml
releases:
ec.3:
assembly:
type: preview
basis:
time: "2025-06-16T06:49:16+00:00"
reference_releases:
x86_64: 4.20.0-0.nightly-2025-06-16-162515
group:
advisories:
rpm: 149403
release_jira: ART-12824
operator_index_mode: pre-release
shipment:
advisories:
- kind: image
- kind: extras
- kind: metadata
- kind: prerelease
upgrades: 4.19.0,4.20.0-ec.0,4.20.0-ec.2
rhcos:
rhel-coreos:
images:
x86_64: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:592466f9241980ded5d6436448f71932e1a2c300d6fe7157408b8034ce63a846
aarch64: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:28221ae33ee2cb831f348234513ff41bc37818cabd9b9152501 …
```

ART-13070 gen-assembly: populate shipment advisories placeholders for Konflux

---

pyartcd/pyartcd/pipelines/build_microshift.py

Test build: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fbuild-microshift/2354/console

Add skip_prepare_release param to the pipeline class

---

artcommon/artcommonlib/exectools.py

The limit_concurrency decorator had a flaw where semaphores were created at
import time. This fix creates per-event-loop semaphores using
WeakKeyDictionary to prevent memory leaks.
Additional improvements:
- Add proper type hints with TypeVar for better type safety
- Add parameter validation and async function checking
- Enhanced documentation with comprehensive docstring
- Import weakref and additional typing utilities for robust implementation

Improve(exectools): resolve event loop binding bug in limit_concurrency decorator

---

pyartcd/pyartcd/pipelines/build_microshift.py

Reverts openshift-eng/art-tools#1731

Revert "Add skip_prepare_release param to the pipeline class"

---

artcommon/artcommonlib/exectools.py
artcommon/tests/test_exectools.py
doozer/doozerlib/cli/images_konflux.py

Improve observability of async command execution with comprehensive telemetry enhancements. Add meaningful span names based on command context, detailed execution metrics, and better error tracking.
Key improvements:
- Generate semantic span names for doozer commands with assembly context
- Track execution duration, process PID, and output sizes
- Add success/failure events with timing information
- Truncate long error messages in span attributes
- Update konflux CLI spans with image count context
- Add concurrency limit test to verify execution constraints
These changes provide better visibility into command execution patterns and performance characteristics for debugging and monitoring purposes.

feat: enhance async command execution telemetry and tracing

---

elliott/elliottlib/bzutil.py
elliott/elliottlib/cli/attach_cve_flaws_cli.py
elliott/elliottlib/cli/verify_attached_bugs_cli.py
elliott/elliottlib/shipment_utils.py
elliott/tests/test_attach_cve_flaws_cli.py
elliott/tests/test_shipment_utils.py
pyartcd/pyartcd/pipelines/prepare_release_konflux.py

Ref. [ART-12052](https://issues.redhat.com/browse/ART-12052)
After hacking the first-fix check so that every bug is considered a first fix (removed from the PR), running:
```
elliott --build-system=konflux --group=openshift-4.20 --assembly=ec.3 attach-cve-flaws --use-default-advisory=image
```
prints out the updated release notes in JSON format:
```
{
"type": "RHSA",
"live_id": 9562,
"synopsis": "OpenShift Container Platform 4.20.0 bug fix update",
"topic": "Red Hat OpenShift Container Platform release 4.20.0 is now available with updates to packages and images that fix several bugs.\n",
"description": "Red Hat OpenShift Container Platform is Red Hat's cloud computing Kubernetes application platform solution designed for on-premise or private cloud deployments.\n\nThis advisory contains …
```

ART-12052 Elliott attach-cve-flaws for Konflux

---

doozer/doozerlib/backend/rebaser.py

Same as https://github.com/openshift-eng/art-tools/pull/1779

[konflux] curl before ADDing cert

---

elliott/elliottlib/cli/snapshot_cli.py

Context: https://redhat-internal.slack.com/archives/C06Q309QUDV/p1752775419354129?thread_ts=1752772604.815239&cid=C06Q309QUDV
Test
```
$ elliott -g openshift-4.18 snapshot new ose-sriov-network-metrics-exporter-
container-v4.18.0-202507170934.p2.gf54736e.assembly.stream.el9
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
name: ose-4-18-20250717182643245287-1
namespace: ocp-art-tenant
labels:
test.appstudio.openshift.io/type: override
appstudio.openshift.io/application: openshift-4-18
spec:
application: openshift-4-18
components:
- name: ose-4-18-ose-sriov-network-metrics-exporter
source:
git:
url: https://github.com/openshift-priv/sriov-network-metrics-exporter
revision: 3b677e248bc0e4d3fe5f974cb5f8d2c4fdb48579
containerImage: …
```

Support alt for multiple delivery repos when creating snapshot

---

pyartcd/pyartcd/pipelines/prepare_release_konflux.py
pyartcd/tests/pipelines/test_prepare_release_konflux.py

Create and prepare rpm advisory for konflux
test job: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Fprepare-release-konflux/123/console

ART-13271 create rpm advisory in prepare release konflux

---

ocp-build-data-validator/validator/json_schemas/image_config.base.schema.json

For https://github.com/openshift-eng/ocp-build-data/pull/7239

[konflux] network_mode add to validator

---

pyartcd/pyartcd/jenkins.py
pyartcd/pyartcd/pipelines/olm_bundle_konflux.py

Needs https://github.com/openshift-eng/aos-cd-jobs/pull/4438
Test: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Folm_bundle_konflux/3642/console

olm_bundle_konflux triggers build-fbc job

---

doozer/doozerlib/backend/konflux_olm_bundler.py

Follows https://github.com/openshift-eng/art-tools/pull/1822
We need to sync bundles as well, to art-images-share

ART-13339: sync bundles to art-images-share

---

pyartcd/pyartcd/pipelines/prepare_release_konflux.py
pyartcd/tests/pipelines/test_prepare_release_konflux.py

When testing with a custom assembly definition and creating a new MR, 
this flag makes the prep works in shipment-ci pipeline.

Inject build-repo in prep

---

doozer/doozerlib/backend/rebaser.py

**Summary**
Add generic artifact validation for hermetic builds to fix NPM GitHub artifact prefetch failures.
**Problem**
Before: Rebaser injects npm install -g https://github.com/... commands that fail in hermetic builds due to network access restrictions
After: Hermetic builds should pre-fetch GitHub npm packages via the existing generic-artifact-prefetch system, then install from local artifacts

feat(rebaser): add generic artifact validation for hermetic builds

---

artcommon/artcommonlib/util.py
pyartcd/pyartcd/pipelines/build_microshift_bootc.py

Follows https://github.com/openshift-eng/art-tools/pull/1888
To prevent garbage collection

tag konflux builds by tag

---

artcommon/artcommonlib/konflux/konflux_db.py
pyartcd/pyartcd/jenkins.py
pyartcd/pyartcd/pipelines/ocp4_scan_konflux.py

Test build: https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4-scan-konflux/27152
Started https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4-konflux/15527/

ocp4-scan-konflux must trigger RPM builds

---

pyartcd/pyartcd/pipelines/build_microshift.py
pyartcd/pyartcd/pipelines/prepare_release_konflux.py

get release date from assembly config

ART-14002 remove date parameter

---

ocp-build-data-validator/validator/schema/releases_schema.py

Ref. [ART-12601](https://issues.redhat.com/browse/ART-12601)

ART-12601 Forbid group! config which breaks the assembly group config override

---

doozer/doozerlib/coverity.py
doozer/doozerlib/distgit.py
doozer/doozerlib/osbs2_builder.py
doozer/tests/test_osbs2.py
pyartcd/pyartcd/pipelines/rebuild.py

Fix for failing builds in
- https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%25252Focp4/24454/console
- https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=68752030
Previous work:
- https://github.com/openshift-eng/art-tools/pull/1918
- https://github.com/openshift-eng/ocp-build-data/pull/7437

Support art prefix for .repo files in brew rebase

---

doozer/doozerlib/cli/images_streams.py

Test Platform is moving to an architecture where images are no longer used from their app.ci internal registry and instead always pulled from quay.io . The images we mirror to app.ci, therefore, specifically those that get added to the 4.x imagestream, must also show up in quay.io/openshift/ci . When CI promotes an image from an upstream build, this happens automatically. However, for images that only ART builds, we need to upload to QCI directly. An example is the 'base-rhel9' image, which gets added to the 4.x imagestreams and whose sha256 digest CI will try to resolve in quay.io/openshift/ci . 
We must have write credentials for QCI for this to work. `openshift+art_to_ci_promotion_robot` was created for this purpose, but I'm not certain it is in our credential store.

Add mirroring to quay.io/openshift/ci (QCI) to images that should be used in CI

---

doozer/doozerlib/cli/scan_sources_konflux.py

This PR introduces two main improvements to the Konflux `scan-sources` command, specifically concerning RPM build checks.
The logic for finding the commit hash of an RPM's source has been updated. Previously, the tool parsed `git log` output, which was prone to errors if the commit message format changed. The new implementation now uses `git rev-parse HEAD` within the source directory, providing a more direct and robust way to get the exact commit hash.
A new check has been added to see if the most recent build for an RPM has failed. 
- If a recent build has failed, the tool will now delay the next build attempt for a configurable interval (defaulting to 6 hours) to avoid rapid-fire build triggers on a persistently failing build.
- If the last failed build is older than the configured …

Konflux scan-sources: fix RPM check

---

elliott/elliottlib/cli/find_bugs_cli.py

support find-bugs cli to only find cve trackes

add cve-only to find-bugs cli

---

pyartcd/pyartcd/jenkins.py

Extract the parameters of a Jenkins build from its URL. Tested locally with:
```
from pyartcd import jenkins
jenkins.init_jenkins()
print(
jenkins.get_build_parameters(
'https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4-konflux/16686/'
)
)
print(
jenkins.is_build_running(
'https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4-konflux/16686/'
)
)
print(
jenkins.is_build_running(
'https://art-jenkins.apps.prod-stable-spoke1-dc-iad2.itup.redhat.com/job/aos-cd-builds/job/build%252Focp4-konflux/16710/'
)
)

jenkins.py: extract build params from URL

---

pyartcd/pyartcd/pipelines/ocp4_konflux.py

ref. [ART-14093](https://issues.redhat.com/browse/ART-14093)

ART-14093 notify about mass rebuild start/end

---

artcommon/artcommonlib/assembly.py
artcommon/artcommonlib/config/__init__.py
doozer/doozerlib/assembly_inspector.py
doozer/doozerlib/runtime.py
elliott/elliottlib/cli/find_bugs_golang_cli.py
elliott/elliottlib/cli/find_builds_cli.py
elliott/elliottlib/cli/find_unconsumed_rpms.py
elliott/elliottlib/runtime.py

Reverts openshift-eng/art-tools#1986

Revert "Revert "Add BuildDataLoader for loading configs from build data repo""

---

pyartcd/pyartcd/pipelines/promote.py
pyartcd/tests/pipelines/test_promote.py

Shouldn't affect promote since its the last step, after all the important bits complete

fix doc payload sha inserts

---

doozer/doozerlib/backend/konflux_client.py

prefetch-dependencies for yarn need more memory to run

Add resource for prefetch-dependencies step

---

pyartcd/pyartcd/pipelines/prepare_release_konflux.py
pyartcd/tests/pipelines/test_prepare_release_konflux.py

This reverts commit b04c2d6e1a483d9127d332a2ad705b3100648cd6.

Revert "Commit builds for each shipment individually (#2010)"

---

doozer/doozerlib/util.py
pyartcd/pyartcd/pipelines/promote.py

ref slack thread: https://redhat-internal.slack.com/archives/GDBRP5YJH/p1759157358407759

update workflow for hotfixes

---

artcommon/artcommonlib/util.py
doozer/doozerlib/backend/konflux_image_builder.py
pyartcd/pyartcd/pipelines/ocp4_konflux.py

ref. [ART-14153](https://issues.redhat.com/browse/ART-14153)

ART-14153 Sync image tags to art-images-share
